;from longhorn ntdll (ntdllnew) 
@ stdcall AlpcGetMessageAttribute(ptr long)
@ stdcall AlpcInitializeMessageAttribute(long ptr long ptr)
@ stdcall EtwDeliverDataBlock(long)
@ stdcall EtwEnumerateProcessRegGuids(ptr long long)
@ stdcall EtwpCreateEtwThread(ptr ptr)
@ stdcall EtwpGetCpuSpeed(long long) 
@ stdcall EtwProcessPrivateLoggerRequest(ptr)
@ stdcall EtwLogTraceEvent(long long long)
@ stdcall EtwNotificationRegister(long long long long long)
@ stdcall EtwNotificationUnregister(long long long)
@ stdcall EtwSendNotification(long long long long long)
@ stdcall ShipAssert(long long) 
@ stdcall LdrAddDllDirectory(wstr)
@ stdcall LdrQueryModuleServiceTags(ptr ptr long)
#@ stdcall LdrResolveDelayLoadsFromDll(ptr str long)
#@ stdcall LdrRemoveDllDirectory(ptr)
@ stdcall NtAlpcAcceptConnectPort(ptr ptr long ptr ptr ptr ptr ptr long) 
@ stdcall NtAlpcCancelMessage(ptr long ptr)	
@ stdcall NtAlpcConnectPort(ptr ptr ptr ptr long ptr ptr ptr ptr ptr ptr)
@ stdcall NtAlpcCreatePort(ptr ptr ptr)
@ stdcall NtAlpcCreatePortSection(ptr long ptr long ptr ptr) 
@ stdcall NtAlpcCreateSecurityContext(ptr long ptr)
@ stdcall NtAlpcDeletePortSection(ptr long ptr) 
@ stdcall NtAlpcDeleteSectionView(ptr long ptr) 
@ stdcall NtAlpcDeleteSecurityContext(ptr long ptr) 
@ stdcall NtAlpcDisconnectPort(ptr long)
@ stdcall NtAlpcCreateResourceReserve(ptr long long ptr)
@ stdcall NtAlpcImpersonateClientOfPort(ptr ptr ptr)
@ stdcall NtAlpcQueryInformation(ptr ptr ptr long ptr)
@ stdcall NtAlpcSendWaitReceivePort(ptr long ptr ptr ptr ptr ptr ptr)
@ stdcall NtAlpcSetInformation(ptr ptr ptr long)
@ stdcall NtAlpcCreateSectionView(ptr long ptr)
#@ stdcall NtCreateKeyTransacted(ptr long ptr long ptr long ptr ptr)
@ stdcall NtCreatePrivateNamespace(ptr long ptr ptr)
@ stdcall NtDeletePrivateNamespace(ptr)
@ stdcall NtLoadKeyEx(ptr ptr long ptr)
#@ stdcall NtOpenKeyTransacted(ptr long ptr ptr)
@ stdcall NtOpenPrivateNamespace(ptr long ptr ptr)
@ stdcall NtQueryOpenSubKeysEx(ptr long ptr ptr)
@ stdcall NtQuerySystemInformationEx(long ptr long ptr ptr ptr)
@ stdcall NtRemoveIoCompletionEx(ptr long long ptr ptr long) ;rever unresolved reference em misc.c
@ stdcall NtReplacePartitionUnit(wstr wstr long)
@ stdcall NtSetInformationVirtualMemory(ptr long long ptr ptr long)
@ stdcall NtTraceControl(long ptr long ptr long ptr) 
@ stdcall NtUnmapViewOfSectionEx(ptr ptr long)
#@ stdcall RtlAddResourceAttributeAce(ptr long long long ptr ptr ptr)
@ stdcall RtlInitializeSRWLock(ptr) 
@ stdcall RtlAddMandatoryAce(ptr long long long long ptr) 
#@ stdcall RtlAddSIDToBoundaryDescriptor(ptr ptr)
#@ stdcall RtlAddIntegrityLabelToBoundaryDescriptor(ptr ptr)
@ stdcall RtlDecodePointer(ptr) 
#@ stdcall RtlCheckTokenCapability(ptr ptr ptr)
#@ stdcall RtlCheckTokenMembershipEx(ptr ptr long ptr)
#@ stdcall RtlCreateBoundaryDescriptor(ptr long)
@ stdcall RtlCreateServiceSid(ptr ptr ptr) 
@ stdcall RtlEnableThreadProfiling(ptr long int64 ptr)
@ stdcall RtlCopyContext(ptr long ptr)
@ stdcall RtlCultureNameToLCID(ptr ptr) ;this functions already have implementation on vtdll
#@ stdcall RtlGetCurrentProcessorNumberEx(ptr)
#@ stdcall RtlGetEnabledExtendedFeatures(long long)
#@ stdcall RtlGetExtendedContextLength(long ptr)
#@ stdcall RtlGetExtendedFeaturesMask(ptr)
@ stdcall RtlDeleteBoundaryDescriptor(ptr)
#@ stdcall RtlDeregisterSecureMemoryCacheCallback(ptr)
#@ stdcall RtlDisableThreadProfiling(ptr)
@ stdcall RtlGetCurrentTransaction()
@ stdcall RtlGetFileMUIPath(long wstr wstr ptr wstr ptr ptr)
@ stdcall RtlGetIntegerAtom(long long)
@ stdcall RtlGetSystemPreferredUILanguages(long ptr wstr ptr)
@ stdcall RtlGetSystemTimePrecise()
@ stdcall RtlGetThreadPreferredUILanguages(long ptr ptr ptr)
#@ stdcall RtlGetUILanguageInfo(long wstr wstr ptr ptr)
#@ stdcall RtlGetUserPreferredUILanguages(long long ptr wstr ptr)
#@ stdcall RtlInitializeExtendedContext(ptr long ptr)
@ stdcall RtlIsNormalizedString(long wstr long wstr)
#@ stdcall RtlLocateExtendedFeature(long long ptr)
#@ stdcall RtlLocateLegacyContext(ptr long)
@ stdcall RtlNormalizeString(long wstr long wstr ptr)
@ stdcall RtlpQueryDefaultUILanguage(long long)
@ stdcall RtlProcessFlsData(long)
@ stdcall RtlpSetCurrentUserUILanguage(long)
#@ stdcall RtlQueryThreadProfiling(ptr ptr)
#@ stdcall RtlReadThreadProfilingData(ptr long ptr)
@ stdcall RtlRegisterSecureMemoryCacheCallback(ptr)
@ stdcall RtlRegisterThreadWithCsrss()
@ stdcall RtlRemovePrivileges(ptr ptr long)
@ stdcall RtlSetCurrentTransaction(ptr)
#@ stdcall RtlSetExtendedFeaturesMask(ptr int64)
#@ stdcall RtlUnsubscribeWnfStateChangeNotification(ptr)
@ stdcall TpReleasePool(ptr)
@ stdcall TpReleaseCleanupGroup(ptr)
@ stdcall TpAllocCleanupGroup(ptr)
#@ stdcall TpAllocPool(ptr ptr)
@ stdcall TpAllocTimer(ptr ptr ptr ptr)
@ stdcall TpAllocWait(ptr ptr ptr ptr)
@ stdcall TpAllocWork(ptr ptr ptr ptr)
@ stdcall TpCallbackMayRunLong(ptr)
#@ stdcall TpCallbackReleaseMutexOnCompletion(ptr ptr)
#@ stdcall TpCallbackReleaseSemaphoreOnCompletion(ptr ptr long)
#@ stdcall TpCallbackSetEventOnCompletion(ptr ptr)
#@ stdcall TpCallbackUnloadDllOnCompletion(ptr ptr)
@ stdcall TpCancelAsyncIoOperation(ptr)
#@ stdcall TpDisassociateCallback(ptr)
#@ stdcall TpIsTimerSet(ptr)
@ stdcall TpPostWork(ptr)
#@ stdcall TpQueryPoolStackInformation(ptr ptr)
@ stdcall TpReleaseCleanupGroupMembers(ptr long ptr)
@ stdcall TpReleaseIoCompletion(ptr)
@ stdcall TpReleaseTimer(ptr)
@ stdcall TpReleaseWait(ptr)
@ stdcall TpReleaseWork(ptr)
#@ stdcall TpSetPoolMaxThreads(ptr long)
@ stdcall TpSetPoolMinThreads(ptr long)
#@ stdcall TpSetPoolStackInformation(ptr ptr)
#@ stdcall TpSetTimer(ptr ptr long long)
#@ stdcall TpSetTimerEx(ptr ptr long long)
#@ stdcall TpSetWait(ptr ptr ptr)
#@ stdcall TpSetWaitEx(ptr ptr ptr ptr)
@ stdcall TpSimpleTryPost(ptr ptr ptr)
#@ stdcall TpStartAsyncIoOperation(ptr)
@ stdcall TpWaitForIoCompletion(ptr long)
@ stdcall TpWaitForTimer(ptr long)
@ stdcall TpWaitForWait(ptr long)
@ stdcall TpWaitForWork(ptr long)
@ stdcall TpCallbackLeaveCriticalSectionOnCompletion(ptr ptr)
@ stdcall WinSqmAddToStream(ptr long long ptr)
@ stdcall WinSqmAddToStreamEx(ptr long long long long) ;from Win7
@ stdcall WinSqmEndSession(ptr)
@ stdcall WinSqmIncrementDWORD(long long long)
#@ stdcall WinSqmIsOptedInEx(long)
@ stdcall WinSqmSetIfMaxDWORD(long long long)
@ stdcall WinSqmStartSession(long long long)

;current advapi32 and ntdll version is 5219. So, we don't need these functions for now
;@ stdcall EtwpIsProcessExiting() ;needed for advapi32 from 5112
;@ stdcall EtwpFinalizeLogFileHeader(long) ;needed for advapi32 from 5112
;@ stdcall EtwpFlushUmLogger(long long long long) ;needed for advapi32 from 5112
;@ stdcall EtwpQueryUmLogger(long long ptr ptr) ;needed for advapi32 from 5112
;@ stdcall EtwpStartUmLogger(long long long ptr)  ;needed for advapi32 from 5112
;@ stdcall EtwpStopUmLogger(long long long ptr)  ;needed for advapi32 from 5112
;@ stdcall EtwpUpdateUmLogger(long long long ptr)  ;needed for advapi32 from 5112
;@ stdcall EtwpAddLogHeaderToLogFile(long long long long) ;needed for advapi32 from 5112
;@ stdcall EtwpQueryLogger(ptr long) ;needed for advapi32 from 5112
;@ stdcall EtwpSendUmLogRequest() ;needed for advapi32 from 5112
;@ stdcall EtwpSendWmiKMRequest(long long long long long long long wstr) ;needed for advapi32 from 5112
;@ stdcall EtwProcessPrivateLoggerRequest() 
;@ stdcall EtwDeliverDataBlock()
;@ stdcall EtwTraceDiagnosticEvent() ltdll.EtwTraceDiagnosticEvent ;need longhorn pre-reset dll