@ stdcall Direct3DShaderValidatorCreate9()
@ stdcall PSGPError()
@ stdcall PSGPSampleTexture()
@ stdcall D3DPERF_BeginEvent(long wstr)
@ stdcall D3DPERF_EndEvent()
@ stdcall D3DPERF_GetStatus()
@ stdcall D3DPERF_QueryRepeatFrame()
@ stdcall D3DPERF_SetMarker(long wstr)
@ stdcall D3DPERF_SetOptions(long)
@ stdcall D3DPERF_SetRegion(long wstr)
@ stdcall DebugSetLevel()
@ stdcall DebugSetMute()
@ stdcall Direct3DCreate9(long)
@ stdcall Direct3DCreate9Ex(long ptr)
