@ stdcall AccessCheck(ptr long long ptr ptr ptr ptr ptr)
@ stdcall AddAccessAllowedAce(ptr long long ptr)
@ stdcall AllocateAndInitializeSid(ptr long long long long long long long long long ptr)
@ stdcall CreateProcessAsUserW(long str str ptr ptr long long ptr str ptr ptr)
@ stdcall CreateWellKnownSid(long ptr ptr ptr)
@ stdcall DuplicateTokenEx(long long ptr long long ptr) 
@ stdcall EqualSid(ptr ptr)
@ stdcall FreeSid(ptr)
@ stdcall GetFileSecurityA(str long ptr long ptr)
@ stdcall GetFileSecurityW(wstr long ptr long ptr)
@ stdcall GetLengthSid(ptr)
@ stdcall GetSecurityDescriptorControl(ptr ptr ptr)
@ stdcall GetSecurityDescriptorDacl(ptr ptr ptr ptr)
@ stdcall GetSecurityDescriptorLength(ptr) ntdll.RtlLengthSecurityDescriptor
@ stdcall GetSecurityDescriptorOwner(ptr ptr ptr)
@ stdcall GetTokenInformation(long long ptr long ptr)
@ stdcall ImpersonateLoggedOnUser(long)
@ stdcall InitializeAcl(ptr long long)
@ stdcall InitializeSecurityDescriptor(ptr long)
@ stdcall IsValidSecurityDescriptor(ptr)
@ stdcall IsValidSid(ptr)
@ stdcall IsWellKnownSid(ptr long)
@ stdcall MakeSelfRelativeSD(ptr ptr ptr)
@ stdcall OpenProcessToken(ptr long ptr) 
@ stdcall OpenThreadToken(ptr long long ptr) 
@ stdcall RevertToSelf()
@ stdcall SetFileSecurityA(str long ptr)
@ stdcall SetFileSecurityW(wstr long ptr)
@ stdcall SetSecurityDescriptorDacl(ptr long ptr long)
@ stdcall SetSecurityDescriptorGroup(ptr ptr long)
@ stdcall SetSecurityDescriptorOwner(ptr ptr long)
@ stdcall SetThreadToken(ptr ptr) 