#unknown system orign
@ stdcall WinStationEnumerateExW(ptr ptr ptr)
@ stdcall WinStationFreePropertyValue(ptr)
@ stdcall WinStationFreeUserCertificates(ptr) 
@ stdcall WinStationConnectEx(ptr ptr) 
@ stdcall WinStationFreeUserCredentials(ptr) 
@ stdcall WinStationGetConnectionProperty(ptr ptr ptr) 
@ stdcall WinStationGetDeviceId(ptr ptr ptr ptr)
@ stdcall WinStationGetInitialApplication(ptr ptr ptr ptr ptr) 
@ stdcall WinStationGetLoggedOnCount(ptr ptr) 
@ stdcall WinStationGetSessionIds(ptr ptr ptr)
@ stdcall WinStationGetUserCertificates(ptr) 
@ stdcall WinStationGetUserCredentials(ptr) 
@ stdcall WinStationGetUserProfile(ptr ptr ptr ptr) 
@ stdcall WinStationIsSessionPermitted() 
@ stdcall WinStationNegotiateSession(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall WinStationQueryAllowConcurrentConnections() 
@ stdcall WinStationQueryEnforcementCore(long ptr ptr ptr long ptr) 
@ stdcall WinStationQueryInformationW(ptr long long ptr long ptr)
@ stdcall WinStationReportUIResult(ptr ptr ptr)
@ stdcall WinStationRevertFromServicesSession()
@ stdcall WinStationSetAutologonPassword(ptr ptr)
@ stdcall WinStationSetConnectionProperty(ptr ptr ptr)
@ stdcall WinStationSwitchToServicesSession() 
@ stdcall WinStationSystemShutdownStarted() 
@ stdcall WinStationSystemShutdownWait(long ptr) 
@ stdcall WinStationUserLoginAccessCheck(ptr ptr ptr ptr) 
@ stdcall WinStationVerify(ptr ptr ptr ptr ptr ptr)
@ stdcall WinStationVirtualOpenEx(ptr ptr ptr long) 
