//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XTaskDlgDLL.rc
//
#define IDI_XTASKDIALOG_COMMANDLINK     130
#define IDI_XTASKDIALOG_SHIELD          131
#define IDI_XTASKDIALOG_HOT_COMMANDLINK 132
#define IDI_XTASKDIALOG_ERROR           201
#define IDI_XTASKDIALOG_WARNING         204
#define IDI_XTASKDIALOG_INFORMATION     205
#define IDS_XTASKDIALOG_BUTTON_CAPTION0 11000
#define IDS_XTASKDIALOG_BUTTON_CAPTION1 11001
#define IDS_XTASKDIALOG_BUTTON_CAPTION2 11002
#define IDS_XTASKDIALOG_BUTTON_CAPTION3 11003
#define IDS_XTASKDIALOG_BUTTON_CAPTION4 11004
#define IDS_XTASKDIALOG_BUTTON_CAPTION5 11005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
