@ stdcall CurrentIP()
@ stdcall ConstructPartialMsgIfA() ;pConstructPartialMsgIfA
@ stdcall ConstructPartialMsgIfW() ;pConstructPartialMsgIfW
@ stdcall ConstructPartialMsgVA() ;pConstructPartialMsgVA
@ stdcall ConstructPartialMsgVW() ;pConstructPartialMsgVW
;@ stdcall pConstructPartialMsgIfA() 
;@ stdcall pConstructPartialMsgIfW() 
;@ stdcall pConstructPartialMsgVA() 
;@ stdcall pConstructPartialMsgVW() 
@ stdcall pConstructPartialMsgIfA() ConstructPartialMsgIfA
@ stdcall pConstructPartialMsgIfW() ConstructPartialMsgIfW
@ stdcall pConstructPartialMsgVA() ConstructPartialMsgVA
@ stdcall pConstructPartialMsgVW() ConstructPartialMsgVW
@ stdcall WdsAbortBlackboardItemEnum() 
@ stdcall WdsAddModule() ;wdslegacy.WdsAddModule
@ stdcall WdsAllocCollection() ;wdslegacy.WdsAllocCollection
@ stdcall WdsCollectionAddValue() ;wdslegacy.WdsCollectionAddValue
@ stdcall WdsCollectionGetValue() ;wdslegacy.WdsCollectionGetValue
@ stdcall WdsCopyBlackboardItems()
@ stdcall WdsCopyBlackboardItemsEx()
@ stdcall WdsCreateBlackboard()
@ stdcall WdsDeleteBlackboardValue()
@ stdcall WdsDeleteEvent()
@ stdcall WdsDestroyBlackboard()
@ stdcall WdsDuplicateData()
@ stdcall WdsEnableExit()
@ stdcall WdsEnableExitEx()
@ stdcall WdsEnumFirstBlackboardItem()
@ stdcall WdsEnumFirstCollectionValue()
@ stdcall WdsEnumNextBlackboardItem()
@ stdcall WdsEnumNextCollectionValue()
;@ stdcall WdsERAddFile()
;@ stdcall WdsERSetApplicationName()
@ stdcall WdsExecuteWorkQueue() 
@ stdcall WdsExecuteWorkQueue2() 
@ stdcall WdsExecuteWorkQueueEx() 
@ stdcall WdsExitImmediately()
@ stdcall WdsExitImmediatelyEx()
@ stdcall WdsFreeCollection()
@ stdcall WdsFreeData()
@ stdcall WdsGetAssertFlags()
@ stdcall WdsGetBlackboardBinaryData()
@ stdcall WdsGetBlackboardStringA()
@ stdcall WdsGetBlackboardStringW()
@ stdcall WdsGetBlackboardUintPtr()
@ stdcall WdsGetBlackboardValue()
@ stdcall WdsGetCurrentExecutionGroup()
@ stdcall WdsGetPointer()
@ stdcall WdsGetSetupLog()
@ stdcall WdsGetTempDir()
@ stdcall WdsInitialize()
@ stdcall WdsInitializeCallbackArray()
@ stdcall WdsInitializeDataBinary()
@ stdcall WdsInitializeDataStringA()
@ stdcall WdsInitializeDataStringW()
@ stdcall WdsInitializeDataUInt32()
@ stdcall WdsInitializeDataUInt64()
@ stdcall WdsIsDiagnosticModeEnabled()
@ stdcall WdsIterateOfflineQueue()
@ stdcall WdsIterateQueue()
@ stdcall WdsLockBlackboardValue()
@ stdcall WdsLockExecutionGroup()
@ stdcall WdsLogCreate()
@ stdcall WdsLogDestroy()
@ stdcall WdsLogRegisterProvider()
@ stdcall WdsLogRegStockProviders()
@ stdcall WdsLogUnRegisterProvider()
@ stdcall WdsLogUnRegStockProviders()
@ stdcall WdsPackCollection()
@ stdcall WdsPublish()
@ stdcall WdsPublishEx()
@ stdcall WdsPublishImmediateAsync()
@ stdcall WdsPublishImmediateEx()
@ stdcall WdsPublishOffline()
@ stdcall WdsSeqAlloc()
@ stdcall WdsSeqFree()
@ stdcall WdsSetAssertFlags()
@ stdcall WdsSetBlackboardValue()
@ stdcall WdsSetNextExecutionGroup()
@ stdcall WdsSetupLogDestroy()
@ stdcall WdsSetupLogInit()
@ stdcall WdsSetupLogMessageA()
@ stdcall WdsSetupLogMessageW()
@ stdcall WdsSubscribeEx()
@ stdcall WdsTerminate()
@ stdcall WdsUnlockExecutionGroup()
@ stdcall WdsUnpackCollection()
@ stdcall WdsUnsubscribe()
@ stdcall WdsUnsubscribeEx()
@ stdcall WdsValidBlackboard()