@ stub CurrentIP
;@ stub pConstructPartialMsgIfA
;@ stub pConstructPartialMsgIfW
;@ stub pConstructPartialMsgVA
;@ stub pConstructPartialMsgVW
@ stub ConstructPartialMsgIfA
@ stub ConstructPartialMsgIfW
@ stub ConstructPartialMsgVA
@ stub ConstructPartialMsgVW
@ stub WdsAbortBlackboardItemEnum
@ stub WdsAddModule
@ stub WdsAllocCollection
@ stub WdsCollectionAddValue
@ stub WdsCollectionGetValue
@ stub WdsCopyBlackboardItems
@ stub WdsCopyBlackboardItemsEx
@ stub WdsCreateBlackboard
@ stub WdsDeleteBlackboardValue
@ stub WdsDeleteEvent
@ stub WdsDestroyBlackboard
@ stub WdsDuplicateData
@ stub WdsEnableExit
@ stub WdsEnableExitEx
@ stub WdsEnumFirstBlackboardItem
@ stub WdsEnumFirstCollectionValue
@ stub WdsEnumNextBlackboardItem
@ stub WdsEnumNextCollectionValue
@ stub WdsERAddFile
@ stub WdsERSetApplicationName
@ stub WdsExecuteWorkQueue
@ stub WdsExecuteWorkQueue2
;@ stub WdsExecuteWorkQueueEx
@ stub WdsExitImmediately
@ stub WdsExitImmediatelyEx
@ stub WdsFreeCollection
@ stub WdsFreeData
@ stub WdsGetAssertFlags
@ stub WdsGetBlackboardBinaryData
@ stub WdsGetBlackboardStringA
@ stub WdsGetBlackboardStringW
@ stub WdsGetBlackboardUintPtr
@ stub WdsGetBlackboardValue
@ stub WdsGetCurrentExecutionGroup
@ stub WdsGetPointer
@ stub WdsGetSetupLog
@ stub WdsGetTempDir
@ stub WdsInitialize
@ stub WdsInitializeCallbackArray
@ stub WdsInitializeDataBinary
@ stub WdsInitializeDataStringA
@ stub WdsInitializeDataStringW
@ stub WdsInitializeDataUInt32
@ stub WdsInitializeDataUInt64
@ stub WdsIterateOfflineQueue
@ stub WdsIterateQueue
@ stub WdsLockBlackboardValue
@ stub WdsLockExecutionGroup
@ stub WdsLogCreate
@ stub WdsLogDestroy
@ stub WdsLogRegisterProvider
@ stub WdsLogRegStockProviders
@ stub WdsLogUnRegisterProvider
@ stub WdsLogUnRegStockProviders
@ stub WdsPackCollection
@ stub WdsPublish
@ stub WdsPublishEx
@ stub WdsPublishImmediateAsync
@ stub WdsPublishImmediateEx
@ stub WdsPublishOffline
@ stub WdsSeqAlloc
@ stub WdsSeqFree
@ stub WdsSetAssertFlags
@ stub WdsSetBlackboardValue
@ stub WdsSetNextExecutionGroup
@ stub WdsSetupLogDestroy
@ stub WdsSetupLogInit
@ stub WdsSetupLogMessageA
@ stub WdsSetupLogMessageW
@ stub WdsSubscribeEx
@ stub WdsTerminate
@ stub WdsUnlockExecutionGroup
@ stub WdsUnpackCollection
@ stub WdsUnsubscribe
@ stub WdsUnsubscribeEx
@ stub WdsValidBlackboard