@ stdcall ChangeServiceConfig2A(long long ptr)
@ stdcall ChangeServiceConfig2W(long long ptr)
@ stdcall ChangeServiceConfigW(long long long long wstr wstr ptr wstr wstr wstr wstr)
@ stdcall CloseServiceHandle(long)
@ stdcall ControlService(long long ptr)
@ stdcall ControlServiceExA(ptr long long ptr) ;don't need for now 
@ stdcall ControlServiceExW(ptr long long ptr) ;don't need for now 
@ stdcall CreateServiceA(long str str long long long long str str ptr str str str)
@ stdcall I_QueryTagInformation(long long long)
@ stdcall I_ScQueryServiceConfig(long long long)
@ stdcall I_ScSendPnPMessage(long long long long long)
@ stdcall I_ScValidatePnPService(long long long)
@ stdcall NotifyServiceStatusChangeA(ptr long ptr) 
@ stdcall OpenSCManagerA(str str long)
@ stdcall OpenSCManagerW(wstr wstr long)
@ stdcall OpenServiceA(long str long)
@ stdcall OpenServiceW(long wstr long)
@ stdcall QueryServiceConfig2A(long long ptr long ptr)
@ stdcall QueryServiceConfigA(long ptr long ptr)
@ stdcall QueryServiceConfigW(long ptr long ptr)
@ stdcall QueryServiceStatus(long ptr)
@ stdcall RegisterServiceCtrlHandlerA(str ptr)
@ stdcall RegisterServiceCtrlHandlerExA(str ptr ptr)
@ stdcall RegisterServiceCtrlHandlerW(wstr ptr)
@ stdcall StartServiceA(long long ptr)
@ stdcall StartServiceW(long long ptr)
@ stdcall StartServiceCtrlDispatcherA(ptr)