1 stdcall -noname SfcInitPro(long wstr long long long long long ptr long)
2 stdcall -noname SfcTerminateWatcherThread()
3 stdcall -noname SfcConnectToServer(ptr)
4 stdcall -noname SfcClose(ptr)
5 stdcall -noname SfcFileException(long ptr long)
6 stdcall -noname SfcInitiateScan(ptr long)
7 stdcall -noname SfcInstallProtectedFiles(ptr wstr long long long ptr long)
@ stdcall SfcGetNextProtectedFile(ptr ptr)
@ stdcall SfcIsFileProtected(ptr wstr)
@ stdcall SfcIsKeyProtected(long wstr long)
@ stdcall SfcWLEventLogoff(ptr)
@ stdcall SfcWLEventLogon(ptr)