@ stdcall CheckSignatureInFile(str) advapi32.SystemFunction035
@ stdcall CryptAcquireContextA(ptr str str long long)
@ stdcall CryptAcquireContextW(ptr wstr wstr long long)
@ stdcall CryptContextAddRef(long ptr long)
@ stdcall CryptCreateHash(long long long long ptr)
@ stdcall CryptDecrypt(long long long long ptr ptr)
@ stdcall CryptDeriveKey(long long long long ptr)
@ stdcall CryptDestroyHash(long)
@ stdcall CryptDestroyKey(long)
@ stdcall CryptDuplicateHash(long ptr long ptr)
@ stdcall CryptDuplicateKey(long ptr long ptr)
@ stdcall CryptEncrypt(long long long long ptr ptr long)
@ stdcall CryptEnumProviderTypesA(long ptr long ptr ptr ptr)
@ stdcall CryptEnumProviderTypesW(long ptr long ptr ptr ptr)
@ stdcall CryptEnumProvidersA(long ptr long ptr ptr ptr)
@ stdcall CryptEnumProvidersW(long ptr long ptr ptr ptr)
@ stdcall CryptExportKey(long long long long ptr ptr)
@ stdcall CryptGenKey(long long long ptr)
@ stdcall CryptGenRandom(long long ptr)
@ stdcall CryptGetDefaultProviderA(long ptr long ptr ptr)
@ stdcall CryptGetDefaultProviderW(long ptr long ptr ptr)
@ stdcall CryptGetHashParam(long long ptr ptr long)
@ stdcall CryptGetKeyParam(long long ptr ptr long)
@ stdcall CryptGetProvParam(long long ptr ptr long)
@ stdcall CryptGetUserKey(long long ptr)
@ stdcall CryptHashData(long ptr long long)
@ stdcall CryptHashSessionKey(long long long)
@ stdcall CryptImportKey(long ptr long long long ptr)
@ stdcall CryptReleaseContext(long long)
@ stdcall CryptSetHashParam(long long ptr long)
@ stdcall CryptSetKeyParam(long long ptr long)
@ stdcall CryptSetProvParam(long long ptr long)
@ stdcall CryptSetProviderA(str long)
@ stdcall CryptSetProviderExA(str long ptr long)
@ stdcall CryptSetProviderExW(wstr long ptr long)
@ stdcall CryptSetProviderW(wstr long)
@ stdcall CryptSignHashA(long long ptr long ptr ptr)
@ stdcall CryptSignHashW(long long ptr long ptr ptr)
@ stdcall CryptVerifySignatureA(long ptr long long ptr long)
@ stdcall CryptVerifySignatureW(long ptr long long ptr long)
@ stdcall -import SystemFunction006(ptr ptr)
@ stdcall -import SystemFunction007(ptr ptr)
@ stdcall -import SystemFunction008(ptr ptr ptr)
@ stdcall -import SystemFunction009(ptr ptr ptr)
@ stdcall -import SystemFunction010(ptr ptr ptr)
@ stdcall -import SystemFunction011(ptr ptr ptr)
@ stdcall -import SystemFunction012(ptr ptr ptr)
@ stdcall -import SystemFunction013(ptr ptr ptr)
@ stdcall -import SystemFunction014(ptr ptr ptr)
@ stdcall -import SystemFunction015(ptr ptr ptr)
@ stdcall -import SystemFunction016(ptr ptr ptr)
@ stdcall -import SystemFunction018(ptr ptr ptr)
@ stdcall -import SystemFunction020(ptr ptr ptr)
@ stdcall -import SystemFunction021(ptr ptr ptr)
@ stdcall -import SystemFunction022(ptr ptr ptr)
@ stdcall -import SystemFunction023(ptr ptr ptr)
@ stdcall -import SystemFunction024(ptr ptr ptr)
@ stdcall -import SystemFunction025(ptr ptr ptr)
@ stdcall -import SystemFunction026(ptr ptr ptr)
@ stdcall -import SystemFunction027(ptr ptr ptr)
@ stdcall -import SystemFunction030(ptr ptr)
@ stdcall -import SystemFunction031(ptr ptr)
@ stdcall -import SystemFunction032(ptr ptr)
@ stdcall SystemFunction035(str)