@ stdcall -private DllGetClassObject(ptr ptr ptr)
@ stdcall IEnumString_Next_WIC_Proxy(ptr)
@ stdcall IEnumString_Reset_WIC_Proxy(ptr long str ptr)
@ stdcall IPropertyBag2_Write_Proxy(ptr long ptr ptr)
@ stdcall IWICBitmapClipper_Initialize_Proxy(ptr ptr ptr) 
@ stdcall IWICBitmapCodecInfo_DoesSupportAnimation_Proxy(ptr ptr) 
@ stdcall IWICBitmapCodecInfo_DoesSupportLossless_Proxy(ptr ptr) 
@ stdcall IWICBitmapCodecInfo_DoesSupportMultiframe_Proxy(ptr ptr) 
@ stdcall IWICBitmapCodecInfo_GetContainerFormat_Proxy(ptr ptr) 
@ stdcall IWICBitmapCodecInfo_GetDeviceManufacturer_Proxy(ptr long ptr ptr) 
@ stdcall IWICBitmapCodecInfo_GetDeviceModels_Proxy(ptr long ptr ptr) 
@ stdcall IWICBitmapCodecInfo_GetFileExtensions_Proxy(ptr long ptr ptr) 
@ stdcall IWICBitmapCodecInfo_GetMimeTypes_Proxy(ptr long ptr ptr) 
@ stdcall IWICBitmapDecoder_CopyPalette_Proxy(ptr ptr) 
@ stdcall IWICBitmapDecoder_GetColorContexts_Proxy(ptr long ptr ptr) 
@ stdcall IWICBitmapDecoder_GetDecoderInfo_Proxy(ptr ptr) 
@ stdcall IWICBitmapDecoder_GetFrameCount_Proxy(ptr ptr) 
@ stdcall IWICBitmapDecoder_GetFrame_Proxy(ptr long ptr) 
@ stdcall IWICBitmapDecoder_GetMetadataQueryReader_Proxy(ptr ptr) 
@ stdcall IWICBitmapDecoder_GetPreview_Proxy(ptr ptr) 
@ stdcall IWICBitmapDecoder_GetThumbnail_Proxy(ptr ptr) 
@ stdcall IWICBitmapEncoder_Commit_Proxy(ptr) 
@ stdcall IWICBitmapEncoder_CreateNewFrame_Proxy(ptr ptr ptr) 
@ stdcall IWICBitmapEncoder_GetEncoderInfo_Proxy(ptr ptr) 
@ stdcall IWICBitmapEncoder_GetMetadataQueryWriter_Proxy(ptr ptr) 
@ stdcall IWICBitmapEncoder_Initialize_Proxy(ptr ptr long) 
@ stdcall IWICBitmapEncoder_SetPalette_Proxy(ptr ptr) 
@ stdcall IWICBitmapEncoder_SetThumbnail_Proxy(ptr ptr) 
@ stdcall IWICBitmapFlipRotator_Initialize_Proxy(ptr ptr long) 
@ stdcall IWICBitmapFrameDecode_GetColorContexts_Proxy(ptr long ptr ptr) 
@ stdcall IWICBitmapFrameDecode_GetMetadataQueryReader_Proxy(ptr ptr) 
@ stdcall IWICBitmapFrameDecode_GetThumbnail_Proxy(ptr ptr) 
@ stdcall IWICBitmapFrameEncode_Commit_Proxy(ptr) 
@ stdcall IWICBitmapFrameEncode_GetMetadataQueryWriter_Proxy(ptr ptr) 
@ stdcall IWICBitmapFrameEncode_Initialize_Proxy(ptr ptr) 
@ stdcall IWICBitmapFrameEncode_SetColorContexts_Proxy(ptr long ptr) 
@ stdcall IWICBitmapFrameEncode_SetResolution_Proxy(ptr double double) 
@ stdcall IWICBitmapFrameEncode_SetSize_Proxy(ptr long long) 
@ stdcall IWICBitmapFrameEncode_SetThumbnail_Proxy(ptr ptr) 
@ stdcall IWICBitmapFrameEncode_WriteSource_Proxy(ptr ptr ptr) 
@ stdcall IWICBitmapLock_GetDataPointer_STA_Proxy(ptr ptr ptr) 
@ stdcall IWICBitmapLock_GetStride_Proxy(ptr ptr) 
@ stdcall IWICBitmapScaler_Initialize_Proxy(ptr ptr long long long) 
@ stdcall IWICBitmapSource_CopyPalette_Proxy(ptr ptr) 
@ stdcall IWICBitmapSource_CopyPixels_Proxy(ptr ptr long long ptr) 
@ stdcall IWICBitmapSource_GetPixelFormat_Proxy(ptr ptr) 
@ stdcall IWICBitmapSource_GetResolution_Proxy(ptr ptr ptr) 
@ stdcall IWICBitmapSource_GetSize_Proxy(ptr ptr ptr) 
@ stdcall IWICBitmap_Lock_Proxy(ptr ptr long ptr) 
@ stdcall IWICBitmap_SetPalette_Proxy(ptr ptr) 
@ stdcall IWICBitmap_SetResolution_Proxy(ptr double double) 
@ stdcall IWICColorContext_InitializeFromMemory_Proxy(ptr ptr long) 
@ stdcall IWICComponentFactory_CreateMetadataWriterFromReader_Proxy(ptr ptr ptr ptr) 
@ stdcall IWICComponentFactory_CreateQueryWriterFromBlockWriter_Proxy(ptr ptr ptr) 
@ stdcall IWICComponentInfo_GetAuthor_Proxy(ptr long ptr ptr) 
@ stdcall IWICComponentInfo_GetCLSID_Proxy(ptr ptr) 
@ stdcall IWICComponentInfo_GetFriendlyName_Proxy(ptr long ptr ptr) 
@ stdcall IWICComponentInfo_GetSpecVersion_Proxy(ptr long ptr ptr) 
@ stdcall IWICComponentInfo_GetVersion_Proxy(ptr long ptr ptr) 
@ stdcall IWICFastMetadataEncoder_Commit_Proxy(ptr) 
@ stdcall IWICFastMetadataEncoder_GetMetadataQueryWriter_Proxy(ptr ptr) 
@ stdcall IWICFormatConverter_Initialize_Proxy(ptr ptr ptr long ptr double long) 
@ stdcall IWICImagingFactory_CreateBitmapClipper_Proxy(ptr ptr) 
@ stdcall IWICImagingFactory_CreateBitmapFlipRotator_Proxy(ptr ptr) 
@ stdcall IWICImagingFactory_CreateBitmapFromHBITMAP_Proxy(ptr ptr ptr long ptr) 
@ stdcall IWICImagingFactory_CreateBitmapFromHICON_Proxy(ptr ptr ptr) 
@ stdcall IWICImagingFactory_CreateBitmapFromMemory_Proxy(ptr long long ptr long long ptr ptr) 
@ stdcall IWICImagingFactory_CreateBitmapFromSource_Proxy(ptr ptr long ptr)
@ stdcall IWICImagingFactory_CreateBitmapScaler_Proxy(ptr ptr) 
@ stdcall IWICImagingFactory_CreateBitmap_Proxy(ptr long long ptr long ptr) 
@ stdcall IWICImagingFactory_CreateComponentInfo_Proxy(ptr ptr ptr) 
@ stdcall IWICImagingFactory_CreateDecoderFromFileHandle_Proxy(ptr ptr ptr long ptr) 
@ stdcall IWICImagingFactory_CreateDecoderFromFilename_Proxy(ptr wstr ptr long long ptr) 
@ stdcall IWICImagingFactory_CreateDecoderFromStream_Proxy(ptr ptr ptr long ptr) 
@ stdcall IWICImagingFactory_CreateEncoder_Proxy(ptr ptr ptr ptr) 
@ stdcall IWICImagingFactory_CreateFastMetadataEncoderFromDecoder_Proxy(ptr ptr ptr) 
@ stdcall IWICImagingFactory_CreateFastMetadataEncoderFromFrameDecode_Proxy(ptr ptr ptr) 
@ stdcall IWICImagingFactory_CreateFormatConverter_Proxy(ptr ptr) 
@ stdcall IWICImagingFactory_CreatePalette_Proxy(ptr ptr) 
@ stdcall IWICImagingFactory_CreateQueryWriterFromReader_Proxy(ptr ptr ptr ptr) 
@ stdcall IWICImagingFactory_CreateQueryWriter_Proxy(ptr ptr ptr ptr) 
@ stdcall IWICImagingFactory_CreateStream_Proxy(ptr ptr) 
@ stdcall IWICMetadataBlockReader_GetCount_Proxy(ptr ptr) 
@ stdcall IWICMetadataBlockReader_GetReaderByIndex_Proxy(ptr long ptr) 
@ stdcall IWICMetadataQueryReader_GetContainerFormat_Proxy(ptr ptr) 
@ stdcall IWICMetadataQueryReader_GetEnumerator_Proxy(ptr ptr) 
@ stdcall IWICMetadataQueryReader_GetLocation_Proxy(ptr long ptr ptr) 
@ stdcall IWICMetadataQueryReader_GetMetadataByName_Proxy(ptr wstr ptr) 
@ stdcall IWICMetadataQueryWriter_RemoveMetadataByName_Proxy(ptr wstr) 
@ stdcall IWICMetadataQueryWriter_SetMetadataByName_Proxy(ptr wstr ptr) 
@ stdcall IWICPalette_GetColorCount_Proxy(ptr ptr) 
@ stdcall IWICPalette_GetColors_Proxy(ptr long ptr ptr) 
@ stdcall IWICPalette_GetType_Proxy(ptr ptr) 
@ stdcall IWICPalette_HasAlpha_Proxy(ptr ptr) 
@ stdcall IWICPalette_InitializeCustom_Proxy(ptr ptr long) 
@ stdcall IWICPalette_InitializeFromBitmap_Proxy(ptr ptr long long) 
@ stdcall IWICPalette_InitializeFromPalette_Proxy(ptr ptr) 
@ stdcall IWICPalette_InitializePredefined_Proxy(ptr long long) 
@ stdcall IWICPixelFormatInfo_GetBitsPerPixel_Proxy(ptr ptr)
@ stdcall IWICPixelFormatInfo_GetChannelCount_Proxy(ptr ptr)
@ stdcall IWICPixelFormatInfo_GetChannelMask_Proxy(ptr long long ptr ptr)
@ stdcall IWICStream_InitializeFromIStream_Proxy(ptr ptr) 
@ stdcall IWICStream_InitializeFromMemory_Proxy(ptr ptr long) 
@ stdcall WICConvertBitmapSource(ptr ptr ptr)
@ stdcall WICCreateBitmapFromSection(long long long ptr long long ptr)
@ stdcall WICCreateColorContext_Proxy(ptr ptr)
@ stdcall WICCreateImagingFactory_Proxy(long ptr)
@ stdcall WICGetMetadataContentSize(long ptr ptr)
@ stdcall WICMapGuidToShortName(long long wstr ptr)
@ stdcall WICMapSchemaToName(ptr wstr long wstr long)
@ stdcall WICMapShortNameToGuid(wstr ptr)
@ stdcall WICMatchMetadataContent(long ptr ptr ptr)
@ stdcall WICSerializeMetadataContent(long ptr long ptr)
@ stdcall WICSetEncoderFormat_Proxy(ptr ptr ptr ptr)
