@ stdcall EtwEventEnabled(long long ptr)
@ stdcall EtwEventRegister(ptr ptr ptr ptr)
@ stdcall EtwEventUnregister(long long)
@ stdcall EtwEventWrite(int64 ptr long ptr)
@ stdcall EtwEventWriteEndScenario(long long ptr long ptr)
@ stdcall EtwEventWriteStartScenario(long long ptr long ptr)
@ stdcall EtwReplyNotification(long)
@ stdcall IoDisconnectInterruptEx(ptr)
@ stdcall IoConnectInterruptEx(ptr)