# Undocumented functions - Names derived from debug symbols
1  stdcall -noname QueryThemeServices()
2  stdcall -noname OpenThemeFile(wstr wstr ptr ptr long)
3  stdcall -noname CloseThemeFile(ptr)
4  stdcall -noname ApplyTheme(ptr long ptr)
7  stdcall -noname GetThemeDefaults(wstr wstr long wstr long)
8  stdcall -noname EnumThemes(wstr ptr ptr)
9  stdcall -noname EnumThemeColors(wstr wstr long wstr)
10 stdcall -noname EnumThemeSizes(wstr wstr long ptr)
11 stdcall -noname ParseThemeIniFile(wstr wstr ptr ptr)
13 stdcall -noname DrawNCPreview(ptr long ptr wstr wstr wstr ptr ptr)
14 stdcall -noname RegisterDefaultTheme(wstr long)
15 stdcall -noname DumpLoadedThemeToTextFile(ptr wstr long long)
16 stdcall -noname OpenThemeDataFromFile(ptr ptr wstr long)
17 stdcall -noname OpenThemeFileFromData(ptr ptr)
18 stdcall -noname GetThemeSysSize96(long long)
19 stdcall -noname GetThemeSysFont96(long long ptr)
20 stdcall -noname SessionAllocate(ptr ptr ptr ptr ptr ptr ptr)
21 stdcall -noname SessionFree(ptr)
22 stdcall -noname ThemeHooksOn(ptr)
23 stdcall -noname ThemeHooksOff(ptr)
24 stdcall -noname AreThemeHooksActive(ptr)
25 stdcall -noname GetCurrentChangeNumber(ptr)
26 stdcall -noname GetNewChangeNumber(ptr)
27 stdcall -noname SetGlobalTheme(ptr ptr)
28 stdcall -noname GetGlobalTheme(ptr ptr)
29 stdcall -noname CheckThemeSignature(wstr)
30 stdcall -noname LoadTheme(long long long wstr long long long)
31 stdcall -noname InitUserTheme(ptr)
32 stdcall -noname InitUserRegistry()
33 stdcall -noname ReestablishServerConnection()
34 stdcall -noname ThemeHooksInstall()
35 stdcall -noname ThemeHooksRemove()
36 stdcall -noname RefreshThemeForTS()
43 stdcall -noname ClassicGetSystemMetrics(long)
44 stdcall -noname ClassicSystemParametersInfoA(long long ptr long)
45 stdcall -noname ClassicSystemParametersInfoW(long long ptr long)
46 stdcall -noname ClassicAdjustWindowRectEx(ptr long long long)
48 stdcall -noname GetThemeParseErrorInfo(ptr)
60 stdcall -noname CreateThemeDataFromObjects(ptr ptr long)
61 stdcall -noname OpenThemeDataEx(ptr wstr long)
62 stdcall -noname ServerClearStockObjects(ptr)
63 stdcall -noname MarkSection(ptr long long)
64 stdcall -noname ProcessLoadTheme_RunDLLW(long long ptr long)
65 stdcall -noname SetSystemVisualStyle(wstr long long ptr)
66 stdcall -noname ServiceClearStockObjects(long ptr)
73 stdcall -noname IsThemeActiveByPolicy()

# Standard functions
@ stdcall BeginBufferedPaint(ptr ptr long ptr ptr)
@ stdcall BufferedPaintInit()
@ stdcall BufferedPaintUnInit()
@ stdcall CloseThemeData(ptr)
@ stdcall DrawThemeBackground(ptr ptr long long ptr ptr)
@ stdcall DrawThemeBackgroundEx(ptr ptr long long ptr ptr)
@ stdcall DrawThemeEdge(ptr ptr long long ptr long long ptr)
@ stdcall DrawThemeIcon(ptr ptr long long ptr ptr long)
@ stdcall DrawThemeParentBackground(ptr ptr ptr)
@ stdcall DrawThemeText(ptr ptr long long wstr long long long ptr)
@ stdcall EnableThemeDialogTexture(ptr long)
@ stdcall EnableTheming(long)
@ stdcall EndBufferedPaint(ptr long)
@ stdcall GetCurrentThemeName(wstr long wstr long wstr long)
@ stdcall GetThemeAppProperties()
@ stdcall GetThemeBackgroundContentRect(ptr ptr long long ptr ptr)
@ stdcall GetThemeBackgroundExtent(ptr ptr long long ptr ptr)
@ stdcall GetThemeBackgroundRegion(ptr ptr long long ptr ptr)
@ stdcall GetThemeBool(ptr long long long ptr)
@ stdcall GetThemeColor(ptr long long long ptr)
@ stdcall GetThemeDocumentationProperty(wstr wstr wstr long)
@ stdcall GetThemeEnumValue(ptr long long long ptr)
@ stdcall GetThemeFilename(ptr long long long wstr long)
@ stdcall GetThemeFont(ptr ptr long long long ptr)
@ stdcall GetThemeInt(ptr long long long ptr)
@ stdcall GetThemeIntList(ptr long long long ptr)
@ stdcall GetThemeMargins(ptr ptr long long long ptr ptr)
@ stdcall GetThemeMetric(ptr ptr long long long ptr)
@ stdcall GetThemePartSize(ptr ptr long long ptr long ptr)
@ stdcall GetThemePosition(ptr long long long ptr)
@ stdcall GetThemePropertyOrigin(ptr long long long ptr)
@ stdcall GetThemeRect(ptr long long long ptr)
@ stdcall GetThemeString(ptr long long long wstr long)
@ stdcall GetThemeSysBool(ptr long)
@ stdcall GetThemeSysColor(ptr long)
@ stdcall GetThemeSysColorBrush(ptr long)
@ stdcall GetThemeSysFont(ptr long ptr)
@ stdcall GetThemeSysInt(ptr long ptr)
@ stdcall GetThemeSysSize(ptr long)
@ stdcall GetThemeSysString(ptr long wstr long)
@ stdcall GetThemeTextExtent(ptr ptr long long wstr long long ptr ptr)
@ stdcall GetThemeTextMetrics(ptr ptr long long ptr)
@ stdcall GetWindowTheme(ptr)
@ stdcall HitTestThemeBackground(ptr long long long long ptr long double ptr)
@ stdcall IsAppThemed()
@ stdcall IsThemeActive()
@ stdcall IsThemeBackgroundPartiallyTransparent(ptr long long)
@ stdcall IsThemeDialogTextureEnabled(ptr)
@ stdcall IsThemePartDefined(ptr long long)
@ stdcall OpenThemeData(ptr wstr)
@ stdcall SetThemeAppProperties(long)
@ stdcall SetWindowTheme(ptr wstr wstr)
@ stdcall ThemeInitApiHook(long ptr)
