@ stub EvtIntAssertConfig
@ stub EvtIntAssertConfigCommand
@ stub EvtIntClearLog
@ stub EvtIntClose
@ stub EvtIntCompileTemplate
@ stub EvtIntCreateBookmark
@ stub EvtIntCreateMessageRenderContext
@ stub EvtIntCreateValuesRenderContext
@ stub EvtIntDeleteChannelConfig
@ stub EvtIntExportLog
@ stub EvtIntGetChannelConfigProperty
@ stub EvtIntGetEventMetadataProperty
@ stub EvtIntGetExtendedStatus
@ stub EvtIntGetMatchedQueryIds
@ stub EvtIntGetNamedObjectInformation
@ stub EvtIntGetPublisherMetadataProperty
@ stub EvtIntMarshalTemplate
@ stub EvtIntMarshalXml
@ stub EvtIntNext
@ stub EvtIntNextBatch
@ stub EvtIntNextChannelPath
@ stub EvtIntNextEventMetadata
@ stub EvtIntNextPublisherId
@ stub EvtIntOpenChannelConfig
@ stub EvtIntOpenChannelEnum
@ stub EvtIntOpenEventMetadataEnum
@ stub EvtIntOpenPublisherEnum
@ stub EvtIntOpenPublisherMetadata
@ stub EvtIntQueryLog
@ stub EvtIntRegisterSubscription
@ stub EvtIntRender
@ stub EvtIntRenderBookmark
@ stub EvtIntRetractConfig
@ stub EvtIntSaveChannelConfig
@ stub EvtIntSeek
@ stub EvtIntSetChannelConfigProperty
@ stub EvtIntUpdateBookmark
@ stub EvtIntUpdateSubscription
