

386_OBJECTS=\
 $(OBJ_PATH)\$O\storahci.obj \


_RES_FILE=$(OBJ_PATH)\$O\storahci.res



# lowercased
BASEDIR=f:\develop\ddk\winddk\7600.16385.1
OBJECT_ROOT=f:\develop\ddk\winddk\7600.16385.1
MAKEDIR_LOWERCASE=f:\develop\one-core\one-core-api-new\drivers\storage\miniport\storahci
OBJ_PATH=f:\develop\one-core\one-core-api-new\drivers\storage\miniport\storahci
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
