@ fastcall WdEnterMonitoredSection(ptr)
@ fastcall WdExitMonitoredSection(ptr)
@ fastcall WdResetDeferredWatch(ptr)
@ fastcall WdResumeDeferredWatch(ptr ptr)
@ fastcall WdSuspendDeferredWatch(ptr)
@ stdcall WdAllocateDeferredWatchdog(ptr ptr long)
@ stdcall WdAllocateWatchdog(ptr ptr long)
@ stdcall WdAttachContext(ptr ptr)
@ stdcall WdCompleteEvent(ptr ptr)
@ stdcall WdDereferenceObject(ptr)
@ stdcall WdDetachContext(ptr)
@ stdcall WdFreeDeferredWatchdog(ptr)
@ stdcall WdFreeWatchdog(ptr)
@ stdcall WdGetDeviceObject(ptr)
@ stdcall WdGetLastEvent(ptr)
@ stdcall WdGetLowestDeviceObject(ptr)
@ stdcall WdMadeAnyProgress(ptr)
@ stdcall WdReferenceObject(ptr)
@ stdcall WdResetWatch(ptr)
@ stdcall WdResumeWatch(ptr ptr)
@ stdcall WdStartDeferredWatch(ptr ptr long)
@ stdcall WdStartWatch(ptr double ptr)
@ stdcall WdStopDeferredWatch(ptr)
@ stdcall WdStopWatch(ptr long)
@ stdcall WdSuspendWatch(ptr)
@ stdcall DMgrAcquireGdiViewId(ptr)
@ stdcall DMgrAcquireDisplayOwnership(long)
@ stdcall DMgrGetDisplayOwnership(ptr)
@ stdcall DMgrGetSmbiosInfo(ptr long)
@ stdcall DMgrIsSetupRunning()
@ stdcall DMgrReleaseDisplayOwnership(long)
@ stdcall DMgrReleaseGdiViewId(long long)
@ stdcall DMgrWriteDeviceCountToRegistry()

@ stdcall GTF_FloatToInteger(ptr ptr)
@ stdcall GTF_FloatToRational(ptr ptr ptr)
@ stdcall GTF_UsingVerticalRefreshFrequency_Stage1(long long long long long ptr)
@ stdcall SMgrGdiCallout(ptr long long)
@ stdcall SMgrRegisterSessionStartCallout(long)
@ stdcall SMgrUnregisterSessionStartCallout(long)
@ stdcall WdDbgCreateSnapshot(long long long long long)
@ stdcall WdDbgDestroySnapshot(ptr)
@ stdcall WdDbgReportCancel(ptr)
@ stdcall WdDbgReportComplete(ptr)
@ stdcall WdDbgReportCreate(long long long long long long)
@ stdcall WdDbgReportQueryInfo(ptr ptr)
@ stdcall WdDbgReportRecreate(long long long long long long ptr)
@ stdcall WdDbgReportSecondaryData(long ptr long)
@ stdcall WdDiagGetEtwHandle()
@ stdcall WdDiagInit(long)
@ stdcall WdDiagIsTracingEnabled(long)
@ stdcall WdDiagNotifyUser(long long long long)
@ stdcall WdDiagShutdown()
@ stdcall WdInitLogging()
@ stdcall WdLogEvent5(long long long long long long)
@ stdcall WdLogGetRecentEvents(long long long long)
@ stdcall WdpInterfaceReferenceNop(long)
@ stdcall WdQueryDebugFlag(long)