@ stdcall ChangeAccountPasswordA(wstr wstr wstr wstr wstr long long ptr)
@ stdcall ChangeAccountPasswordW(wstr wstr wstr wstr wstr long long ptr) 
@ stdcall CloseLsaPerformanceData()
@ stdcall CollectLsaPerformanceData(wstr ptr ptr ptr)
@ stdcall CredParseUserNameWithType(wstr ptr ptr long)
@ stdcall OpenLsaPerformanceData(ptr)
@ stdcall SeciAllocateAndSetCallFlags(ptr long)
@ stdcall SeciAllocateAndSetIPAddress(ptr long long)
@ stdcall SeciFreeCallContext()