@ stdcall CertAddCRLContextToStore(ptr ptr long ptr)
@ stdcall CertAddCTLContextToStore(ptr ptr long ptr)
@ stdcall CertAddCertificateContextToStore(ptr ptr long ptr)
@ stdcall CertAddCertificateLinkToStore(ptr ptr long ptr)
@ stdcall CertAddEncodedCRLToStore(ptr long ptr long long ptr)
@ stdcall CertAddEncodedCTLToStore(ptr long ptr long long ptr)
@ stdcall CertAddEncodedCertificateToStore(ptr long ptr long long ptr)
@ stdcall CertAddEncodedCertificateToSystemStoreA(str ptr long)
@ stdcall CertAddEncodedCertificateToSystemStoreW(wstr ptr long)
@ stdcall CertAddEnhancedKeyUsageIdentifier(ptr str)
@ stdcall CertAddSerializedElementToStore(ptr ptr long long long long ptr ptr)
@ stdcall CertAddStoreToCollection(ptr ptr long long)
@ stdcall CertAlgIdToOID(long)
@ stdcall CertCloseStore(ptr long)
@ stdcall CertCompareCertificate(long ptr ptr)
@ stdcall CertCompareCertificateName(long ptr ptr)
@ stdcall CertCompareIntegerBlob(ptr ptr)
@ stdcall CertComparePublicKeyInfo(long ptr ptr)
@ stdcall CertControlStore(ptr long long ptr)
@ stdcall CertCreateCRLContext(long ptr long)
@ stdcall CertCreateCTLContext(long ptr long)
@ stdcall CertCreateCertificateChainEngine(ptr ptr)
@ stdcall CertCreateCertificateContext(long ptr long)
@ stdcall CertCreateContext(long long ptr long long ptr)
@ stdcall CertCreateSelfSignCertificate(long ptr long ptr ptr ptr ptr ptr)
@ stdcall CertDeleteCRLFromStore(ptr)
@ stdcall CertDeleteCTLFromStore(ptr)
@ stdcall CertDeleteCertificateFromStore(ptr)
@ stdcall CertDuplicateCRLContext(ptr)
@ stdcall CertDuplicateCTLContext(ptr)
@ stdcall CertDuplicateCertificateChain(ptr)
@ stdcall CertDuplicateCertificateContext(ptr)
@ stdcall CertDuplicateStore(ptr)
@ stdcall CertEnumCRLContextProperties(ptr long)
@ stdcall CertEnumCRLsInStore(ptr ptr)
@ stdcall CertEnumCTLContextProperties(ptr long)
@ stdcall CertEnumCTLsInStore(ptr ptr)
@ stdcall CertEnumCertificateContextProperties(ptr long)
@ stdcall CertEnumCertificatesInStore(ptr ptr)
@ stdcall CertEnumPhysicalStore(ptr long ptr ptr)
@ stdcall CertEnumSystemStore(long ptr ptr ptr)
@ stdcall CertFindAttribute(str long ptr)
@ stdcall CertFindChainInStore(ptr long long long ptr ptr)
@ stdcall CertFindCRLInStore(ptr long long long ptr ptr)
@ stdcall CertFindCTLInStore(ptr long long long ptr ptr)
@ stdcall CertFindCertificateInStore(ptr long long long ptr ptr)
@ stdcall CertFindCertificateInCRL(ptr ptr long ptr ptr)
@ stdcall CertFindExtension(str long ptr)
@ stdcall CertFindRDNAttr(str ptr)
@ stdcall CertFindSubjectInCTL(long long ptr ptr long)
@ stdcall CertFreeCRLContext(ptr)
@ stdcall CertFreeCTLContext(ptr)
@ stdcall CertFreeCertificateChain(ptr)
@ stdcall CertFreeCertificateChainEngine(ptr)
@ stdcall CertFreeCertificateContext(ptr)
@ stdcall CertGetCRLContextProperty(ptr long ptr ptr)
@ stdcall CertGetCRLFromStore(ptr ptr ptr ptr)
@ stdcall CertGetCTLContextProperty(ptr long ptr ptr)
@ stdcall CertGetCertificateChain(ptr ptr ptr ptr ptr long ptr ptr)
@ stdcall CertGetCertificateContextProperty(ptr long ptr ptr)
@ stdcall CertGetEnhancedKeyUsage(ptr long ptr ptr)
@ stdcall CertGetIntendedKeyUsage(long ptr ptr long)
@ stdcall CertGetIssuerCertificateFromStore(ptr ptr ptr ptr)
@ stdcall CertGetNameStringA(ptr long long ptr ptr long)
@ stdcall CertGetNameStringW(ptr long long ptr ptr long)
@ stdcall CertGetPublicKeyLength(long ptr)
@ stdcall CertGetStoreProperty(ptr long ptr ptr)
@ stdcall CertGetSubjectCertificateFromStore(ptr long ptr)
@ stdcall CertGetValidUsages(long ptr ptr ptr ptr)
@ stdcall CertIsRDNAttrsInCertificateName(long long ptr ptr)
@ stdcall CertIsValidCRLForCertificate(ptr ptr long ptr)
@ stdcall CertNameToStrA(long ptr long ptr long)
@ stdcall CertNameToStrW(long ptr long ptr long)
@ stdcall CertOIDToAlgId(str)
@ stdcall CertOpenStore(str long long long ptr)
@ stdcall CertOpenSystemStoreA(long str)
@ stdcall CertOpenSystemStoreW(long wstr)
@ stdcall CertRDNValueToStrA(long ptr ptr long)
@ stdcall CertRDNValueToStrW(long ptr ptr long)
@ stdcall CertRegisterPhysicalStore(ptr long wstr ptr ptr)
@ stdcall CertRemoveEnhancedKeyUsageIdentifier(ptr str)
@ stdcall CertRemoveStoreFromCollection(ptr ptr)
@ stdcall CertSaveStore(ptr long long long ptr long)
@ stdcall CertSerializeCRLStoreElement(ptr long ptr ptr)
@ stdcall CertSerializeCTLStoreElement(ptr long ptr ptr)
@ stdcall CertSerializeCertificateStoreElement(ptr long ptr ptr)
@ stdcall CertSetCRLContextProperty(ptr long long ptr)
@ stdcall CertSetCTLContextProperty(ptr long long ptr)
@ stdcall CertSetCertificateContextProperty(ptr long long ptr)
@ stdcall CertSetEnhancedKeyUsage(ptr ptr)
@ stdcall CertSetStoreProperty(ptr long long ptr)
@ stdcall CertStrToNameA(long str long ptr ptr ptr ptr)
@ stdcall CertStrToNameW(long wstr long ptr ptr ptr ptr)
@ stdcall CertVerifyCertificateChainPolicy(str ptr ptr ptr)
@ stdcall CertVerifyCRLRevocation(long ptr long ptr)
@ stdcall CertVerifyCRLTimeValidity(ptr ptr)
@ stdcall CertVerifyCTLUsage(long long ptr ptr long ptr ptr)
@ stdcall CertVerifyRevocation(long long long ptr long ptr ptr)
@ stdcall CertVerifySubjectCertificateContext(ptr ptr ptr)
@ stdcall CertVerifyTimeValidity(ptr ptr)
@ stdcall CertVerifyValidityNesting(ptr ptr)
@ stdcall CreateFileU(wstr long long ptr long long ptr)
@ stdcall CryptBinaryToStringA(ptr long long ptr ptr)
@ stdcall CryptBinaryToStringW(ptr long long ptr ptr)
@ stdcall CryptStringToBinaryA(str long long ptr ptr ptr ptr)
@ stdcall CryptStringToBinaryW (wstr long long ptr ptr ptr ptr)
@ stdcall CryptAcquireContextU(ptr wstr wstr long long)
@ stdcall CryptAcquireCertificatePrivateKey(ptr long ptr ptr ptr ptr)
@ stdcall CryptCloseAsyncHandle(ptr)
@ stdcall CryptCreateAsyncHandle(long ptr)
@ stdcall CryptDecodeMessage(long ptr ptr long ptr long long long long ptr long ptr ptr)
@ stdcall CryptDecodeObject(long str ptr long long ptr ptr)
@ stdcall CryptDecodeObjectEx(long str ptr long long ptr ptr ptr)
@ stdcall CryptDecryptAndVerifyMessageSignature(ptr ptr long ptr long ptr long ptr ptr)
@ stdcall CryptDecryptMessage(ptr ptr long ptr ptr ptr)
@ stdcall CryptEncodeObject(long str ptr ptr ptr)
@ stdcall CryptEncodeObjectEx(long str ptr long ptr ptr ptr)
@ stdcall CryptEncryptMessage(ptr long ptr ptr long ptr ptr)
@ stdcall CryptEnumOIDFunction(long str str long ptr ptr)
@ stdcall CryptEnumOIDInfo(long long ptr ptr)
@ stdcall CryptEnumProvidersU(long long long ptr ptr ptr)
@ stdcall CryptExportPKCS8(ptr long str long ptr ptr ptr)
@ stdcall CryptExportPublicKeyInfo(long long long ptr ptr)
@ stdcall CryptExportPublicKeyInfoEx(long long long str long ptr ptr ptr)
@ stdcall CryptFindCertificateKeyProvInfo(ptr long ptr)
@ stdcall CryptFindLocalizedName(wstr)
@ stdcall CryptFindOIDInfo(long ptr long)
@ stdcall CryptFormatObject(long long long ptr str ptr long ptr ptr)
@ stdcall CryptFreeOIDFunctionAddress(long long)
@ stdcall CryptGetAsyncParam(ptr str ptr ptr)
@ stdcall CryptGetDefaultOIDDllList(long long ptr ptr)
@ stdcall CryptGetDefaultOIDFunctionAddress(long long wstr long ptr ptr)
@ stdcall CryptGetMessageCertificates(long ptr long ptr long)
@ stdcall CryptGetMessageSignerCount(long ptr long)
@ stdcall CryptGetOIDFunctionAddress(long long str long ptr ptr)
@ stdcall CryptGetOIDFunctionValue(long str str wstr ptr ptr ptr)
@ stdcall CryptHashCertificate(long long long ptr long ptr ptr)
@ stdcall CryptHashMessage(ptr long long ptr ptr ptr ptr ptr ptr)
@ stdcall CryptHashPublicKeyInfo(long long long long ptr ptr ptr)
@ stdcall CryptHashToBeSigned(ptr long ptr long ptr ptr)
@ stdcall CryptImportPKCS8(ptr long ptr ptr)
@ stdcall CryptImportPublicKeyInfo(long long ptr ptr)
@ stdcall CryptImportPublicKeyInfoEx(long long ptr long long ptr ptr)
@ stdcall CryptInitOIDFunctionSet(str long)
@ stdcall CryptInstallOIDFunctionAddress(ptr long str long ptr long)
@ stdcall CryptLoadSip(ptr long ptr)
@ stdcall CryptMemAlloc(long)
@ stdcall CryptMemFree(ptr)
@ stdcall CryptMemRealloc(ptr long)
@ stdcall CryptMsgCalculateEncodedLength(long long long ptr str long)
@ stdcall CryptMsgClose(ptr)
@ stdcall CryptMsgControl(ptr long long ptr)
@ stdcall CryptMsgCountersign(ptr long long ptr)
@ stdcall CryptMsgCountersignEncoded(long ptr long long ptr ptr ptr)
@ stdcall CryptMsgDuplicate(ptr)
@ stdcall CryptMsgEncodeAndSignCTL(long ptr ptr long ptr ptr)
@ stdcall CryptMsgGetAndVerifySigner(ptr long ptr long ptr ptr)
@ stdcall CryptMsgGetParam(ptr long long ptr ptr)
@ stdcall CryptMsgOpenToDecode(long long long long ptr ptr)
@ stdcall CryptMsgOpenToEncode(long long long ptr str ptr)
@ stdcall CryptMsgSignCTL(long ptr long ptr long ptr ptr)
@ stdcall CryptMsgUpdate(ptr ptr long long)
@ stdcall CryptMsgVerifyCountersignatureEncoded(ptr long ptr long ptr long ptr)
@ stdcall CryptMsgVerifyCountersignatureEncodedEx(ptr long ptr long ptr long long ptr long ptr)
@ stdcall CryptProtectData(ptr wstr ptr ptr ptr long ptr)
@ stdcall CryptQueryObject(long ptr long long long ptr ptr ptr ptr ptr ptr)
@ stdcall CryptRegisterDefaultOIDFunction(long str long wstr)
@ stdcall CryptRegisterOIDFunction(long str str wstr str)
@ stdcall CryptRegisterOIDInfo(ptr long)
@ stdcall CryptSIPAddProvider(ptr)
@ stdcall CryptSIPCreateIndirectData(ptr ptr ptr)
@ stdcall CryptSIPGetSignedDataMsg(ptr ptr long ptr ptr)
@ stdcall CryptSIPLoad(ptr long ptr)
@ stdcall CryptSIPPutSignedDataMsg(ptr long ptr long ptr)
@ stdcall CryptSIPRemoveProvider(ptr)
@ stdcall CryptSIPRemoveSignedDataMsg(ptr long)
@ stdcall CryptSIPRetrieveSubjectGuid(wstr long ptr)
@ stdcall CryptSIPVerifyIndirectData(ptr ptr)
@ stdcall CryptSetAsyncParam(ptr str ptr ptr)
@ stdcall CryptSetOIDFunctionValue(long str str wstr long ptr long)
@ stdcall CryptSetProviderU(wstr long)
@ stdcall CryptSignAndEncodeCertificate(long long long str ptr ptr ptr ptr ptr)
@ stdcall CryptSignAndEncryptMessage(ptr ptr long ptr ptr long ptr ptr)
@ stdcall CryptSignCertificate(long long long ptr long ptr ptr ptr ptr)
@ stdcall CryptSignHashU(ptr long wstr long ptr ptr)
@ stdcall CryptSignMessage(ptr long long ptr ptr ptr ptr)
@ stdcall CryptSignMessageWithKey(ptr ptr long ptr ptr)
@ stdcall CryptUnprotectData(ptr ptr ptr ptr ptr long ptr)
@ stdcall CryptUnregisterDefaultOIDFunction(long str wstr)
@ stdcall CryptUnregisterOIDFunction(long str str)
@ stdcall CryptUnregisterOIDInfo(ptr)
@ stdcall CryptVerifyCertificateSignature(long long ptr long ptr)
@ stdcall CryptVerifyCertificateSignatureEx(long long long ptr long ptr long ptr)
@ stdcall CryptVerifyDetachedMessageHash(ptr ptr long long ptr ptr ptr ptr)
@ stdcall CryptVerifyDetachedMessageSignature(ptr long ptr long long ptr ptr ptr)
@ stdcall CryptVerifyMessageHash(ptr ptr long ptr ptr ptr ptr)
@ stdcall CryptVerifyMessageSignature(ptr long ptr long ptr ptr ptr)
@ stdcall CryptVerifyMessageSignatureWithKey(ptr ptr ptr long ptr ptr)
@ stdcall CryptVerifySignatureU(ptr ptr long ptr wstr long)
@ stdcall I_CertUpdateStore(ptr ptr long long)
@ stdcall I_CryptAllocTls()
@ stdcall I_CryptCreateLruCache(ptr ptr)
@ stdcall I_CryptCreateLruEntry(ptr long long)
@ stdcall I_CryptDetachTls(long)
@ stdcall I_CryptFindLruEntry(long long)
@ stdcall I_CryptFindLruEntryData(long long long)
@ stdcall I_CryptFlushLruCache(ptr long long)
@ stdcall I_CryptFreeLruCache(ptr long long)
@ stdcall I_CryptFreeTls(long long)
@ stdcall I_CryptGetAsn1Decoder(long)
@ stdcall I_CryptGetAsn1Encoder(long)
@ stdcall I_CryptGetDefaultCryptProv(long)
@ stdcall I_CryptGetDefaultCryptProvForEncrypt(ptr long long)
@ stdcall I_CryptGetOssGlobal(long)
@ stdcall I_CryptGetTls(long)
@ stdcall I_CryptInsertLruEntry(ptr long)
@ stdcall I_CryptInstallAsn1Module(ptr long ptr)
@ stdcall I_CryptInstallOssGlobal(long long long)
@ stdcall I_CryptReadTrustedPublisherDWORDValueFromRegistry(wstr ptr)
@ stdcall I_CryptReleaseLruEntry(ptr)
@ stdcall I_CryptSetTls(long ptr)
@ stdcall I_CryptUninstallAsn1Module(long)
@ stdcall I_CryptUninstallOssGlobal(ptr)
@ stdcall PFXExportCertStore(ptr ptr ptr long)
@ stdcall PFXExportCertStoreEx(ptr ptr ptr ptr long)
@ stdcall PFXImportCertStore(ptr ptr long)
@ stdcall PFXIsPFXBlob(ptr)
@ stdcall PFXVerifyPassword(ptr wstr long)
@ stdcall RegCreateHKCUKeyExU(ptr ptr wstr long wstr long ptr ptr ptr ptr)
@ stdcall RegCreateKeyExU(ptr wstr long wstr long ptr ptr ptr ptr)
@ stdcall RegDeleteValueU(ptr wstr)
@ stdcall RegEnumValueU(ptr long wstr ptr ptr ptr ptr ptr)
@ stdcall RegOpenHKCUKeyExU(ptr long wstr long ptr ptr)
@ stdcall RegOpenKeyExU(ptr wstr long ptr ptr)
@ stdcall RegQueryInfoKeyU(ptr wstr ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr)
@ stdcall RegQueryValueExU(ptr wstr long ptr ptr ptr)
@ stdcall RegSetValueExU(ptr wstr long long ptr long)
@ stdcall CertAddCRLLinkToStore(ptr ptr long ptr)
@ stdcall CertAddCTLLinkToStore(ptr ptr long ptr)
@ stdcall CertCreateCTLEntryFromCertificateContextProperties(ptr long ptr long ptr ptr ptr)
@ stdcall CertEnumSubjectInSortedCTL(ptr ptr ptr ptr)
@ stdcall CertEnumSystemStoreLocation(long ptr ptr)
@ stdcall CertRegisterSystemStore(ptr long ptr ptr)
@ stdcall CertResyncCertificateChainEngine(ptr)
@ stdcall CertSetCertificateContextPropertiesFromCTLEntry(ptr ptr long)
@ stdcall CertUnregisterPhysicalStore(ptr long wstr)
@ stdcall CertUnregisterSystemStore(ptr long)
@ stdcall ChainWlxLogoffEvent(ptr)
@ stdcall CloseCertPerformanceData()
@ stdcall CollectCertPerformanceData(wstr ptr ptr ptr)
@ stdcall CryptCreateKeyIdentifierFromCSP(long str ptr long long ptr ptr ptr)
@ stdcall CryptEnumKeyIdentifierProperties(ptr long long wstr ptr ptr ptr)
@ stdcall CryptGetKeyIdentifierProperty(ptr long long wstr ptr ptr ptr)
@ stdcall CryptInstallDefaultContext(ptr long ptr long ptr ptr)
@ stdcall CryptProtectMemory(ptr long long)
@ stdcall CryptSetKeyIdentifierProperty(ptr long long wstr ptr ptr)
@ stdcall CryptSIPRetrieveSubjectGuidForCatalogFile(wstr ptr ptr)
@ stdcall CryptUninstallDefaultContext(ptr long ptr)
@ stdcall CryptUnprotectMemory(ptr long long)
@ stdcall I_CertProtectFunction(long long wstr ptr long ptr ptr)
@ stdcall I_CertSrvProtectFunction(ptr long long wstr ptr long ptr ptr ptr ptr)
@ stdcall I_CertSyncStore(ptr ptr)
@ stdcall I_CryptAddRefLruEntry(ptr)
@ stdcall I_CryptAddSmartCardCertToStore(ptr ptr wstr ptr ptr)
@ stdcall I_CryptDisableLruOfEntries(ptr)
@ stdcall I_CryptEnableLruOfEntries(ptr ptr)
@ stdcall I_CryptEnumMatchingLruEntries(ptr)
@ stdcall I_CryptFindSmartCardCertInStore(ptr ptr ptr ptr)
@ stdcall I_CryptGetFileVersion(wstr long long)
@ stdcall I_CryptGetLruEntryData(ptr)
@ stdcall I_CryptGetLruEntryIdentifier(ptr)
@ stdcall I_CryptRegisterSmartCardStore(wstr wstr long wstr long)
@ stdcall I_CryptRemoveLruEntry(ptr long ptr)
@ stdcall I_CryptTouchLruEntry(ptr long)
@ stdcall I_CryptUnregisterSmartCardStore(wstr)
@ stdcall I_CryptWalkAllLruCacheEntries(ptr ptr ptr)
@ stdcall OpenCertPerformanceData(wstr)
@ stdcall CertFindSubjectInSortedCTL(ptr long ptr ptr)
1001 stdcall -noname DbgInitOSS(ptr)
1002 stdcall -noname DbgPrintf(wstr)
1003 stdcall -noname RegCreateKeyW(ptr wstr ptr)	advapi32.RegCreateKeyW
1004 stdcall -noname RegCreateKeyExW(ptr wstr long wstr long ptr ptr ptr ptr) advapi32.RegCreateKeyExW
1005 stdcall -noname RegOpenKeyW(ptr wstr long ptr ptr) advapi32.RegOpenKeyW
1006 stdcall -noname RegOpenKeyExW(ptr wstr long ptr ptr) advapi32.RegOpenKeyExW
1007 stdcall -noname RegCreateKeyA(ptr wstr ptr) advapi32.RegCreateKeyA	
1008 stdcall -noname RegCreateKeyExA(ptr str long str long ptr ptr ptr ptr) advapi32.RegCreateKeyExA
1009 stdcall -noname RegOpenKeyA(ptr str long ptr ptr) advapi32.RegOpenKeyA
1010 stdcall -noname RegOpenKeyExA(ptr str long ptr ptr) advapi32.RegOpenKeyExA
1011 stdcall -noname RegCloseKey(ptr) advapi32.RegCloseKey