1   stdcall ParseURLA(str ptr)
2   stdcall ParseURLW(wstr ptr)
3   stdcall -noname PathFileExistsDefExtA(str long)
4   stdcall -noname PathFileExistsDefExtW(wstr long)
5   stdcall -noname PathFindOnPathExA(str ptr long)
6   stdcall -noname PathFindOnPathExW(wstr ptr long)
7   stdcall -ordinal SHAllocShared(ptr long long)
8   stdcall -ordinal SHLockShared(long long)
9   stdcall -ordinal SHUnlockShared(ptr)
10  stdcall -ordinal SHFreeShared(long long)
11  stdcall -noname SHMapHandle(long long long long long)
12  stdcall -noname SHCreateMemStream(ptr long)
13  stdcall -noname RegisterDefaultAcceptHeaders(ptr ptr)
14  stdcall -ordinal GetAcceptLanguagesA(ptr ptr)
15  stdcall -ordinal GetAcceptLanguagesW(ptr ptr)
16  stdcall -ordinal SHCreateThread(ptr ptr long ptr)
17  stdcall -noname SHWriteDataBlockList(ptr ptr)
18  stdcall -noname SHReadDataBlockList(ptr ptr)
19  stdcall -noname SHFreeDataBlockList(ptr)
20  stdcall -noname SHAddDataBlock(ptr ptr)
21  stdcall -noname SHRemoveDataBlock(ptr long)
22  stdcall -noname SHFindDataBlock(ptr long)
23  stdcall -noname SHStringFromGUIDA(ptr ptr long)
24  stdcall -noname SHStringFromGUIDW(ptr ptr long)
25  stdcall -noname IsCharAlphaWrapW(long) 
26  stdcall -noname IsCharUpperWrapW(long) 
27  stdcall -noname IsCharLowerWrapW(long) 
28  stdcall -noname IsCharAlphaNumericWrapW(long)
29  stdcall -ordinal IsCharSpaceW(long)
30  stdcall -noname IsCharBlankW(long)
31  stdcall -noname IsCharPunctW(long)
32  stdcall -noname IsCharCntrlW(ptr)
33  stdcall -noname IsCharDigitW(long)
34  stdcall -noname IsCharXDigitW(long)
35  stdcall -noname GetStringType3ExW(ptr long ptr)
36  stdcall -noname AppendMenuWrapW(long long long wstr) user32.AppendMenuW
37  stdcall -noname CallWindowProcWrapW(ptr long long long long) user32.CallWindowProcW
38  stdcall -noname CharLowerWrapW(wstr) user32.CharLowerW
39  stdcall -noname CharLowerBuffWrapW(wstr long) user32.CharLowerBuffW
40  stdcall -noname CharNextWrapW(wstr) user32.CharNextW
41  stdcall -noname CharPrevWrapW(wstr wstr) user32.CharPrevW
42  stdcall -noname CharToOemWrapW(wstr) user32.CharToOemW
43  stdcall -noname CharUpperWrapW(wstr) user32.CharUpperW
44  stdcall -noname CharUpperBuffWrapW(wstr long) user32.CharUpperBuffW
45  stdcall -noname CompareStringWrapW(long long wstr long wstr long) kernel32.CompareStringW
46  stdcall -noname CopyAcceleratorTableWrapW(long ptr long) user32.CopyAcceleratorTableW
47  stdcall -noname CreateAcceleratorTableWrapW(ptr long) user32.CreateAcceleratorTableW
48  stdcall -noname CreateDCWrapW(wstr wstr wstr ptr) gdi32.CreateDCW
49  stdcall -noname CreateDialogParamWrapW(long ptr long ptr long) user32.CreateDialogParamW
50  stdcall -noname CreateDirectoryWrapW(wstr ptr) kernel32.CreateDirectoryW
51  stdcall -noname CreateEventWrapW(ptr long long wstr) kernel32.CreateEventW
52  stdcall -noname CreateFileWrapW(wstr long long ptr long long long) kernel32.CreateFileW
53  stdcall -noname CreateFontIndirectWrapW(ptr) gdi32.CreateFontIndirectW
54  stdcall -noname CreateICWrapW(wstr wstr wstr ptr) gdi32.CreateICW
55  stdcall -noname CreateWindowExWrapW(long wstr wstr long long long long long long long long ptr) user32.CreateWindowExW
56  stdcall -noname DefWindowProcWrapW(long long long long) user32.DefWindowProcW
57  stdcall -noname DeleteFileWrapW(wstr) kernel32.DeleteFileW
58  stdcall -noname DialogBoxIndirectParamWrapW(long ptr long ptr long) user32.DialogBoxIndirectParamW
59  stdcall -noname DialogBoxParamWrapW(long wstr long ptr long) user32.DialogBoxParamW
60  stdcall -noname DispatchMessageWrapW(ptr) user32.DispatchMessageW
61  stdcall -noname DrawTextWrapW(long wstr long ptr long) user32.DrawTextW
62  stdcall -noname EnumFontFamiliesWrapW(long wstr ptr long) gdi32.EnumFontFamiliesW
63  stdcall -noname EnumFontFamiliesExWrapW(long ptr ptr long long) gdi32.EnumFontFamiliesExW
64  stdcall -noname EnumResourceNamesWrapW(long wstr ptr long) kernel32.EnumResourceNamesW
65  stdcall -noname FindFirstFileWrapW(wstr ptr) kernel32.FindFirstFileW
66  stdcall -noname FindResourceWrapW(long wstr wstr) kernel32.FindResourceW
67  stdcall -noname FindWindowWrapW(wstr wstr) user32.FindWindowW
68  stdcall -noname FormatMessageWrapW(long ptr long long ptr long ptr) kernel32.FormatMessageW
69  stdcall -noname GetClassInfoWrapW(long wstr ptr) user32.GetClassInfoW
70  stdcall -noname GetClassLongWrapW(long long) user32.GetClassLongW
71  stdcall -noname GetClassNameWrapW(long ptr long) user32.GetClassNameW
72  stdcall -noname GetClipboardFormatNameWrapW(long ptr long) user32.GetClipboardFormatNameW
73  stdcall -noname GetCurrentDirectoryWrapW(long ptr) kernel32.GetCurrentDirectoryW
74  stdcall -noname GetDlgItemTextWrapW(long long wstr long) user32.GetDlgItemTextW
75  stdcall -noname GetFileAttributesWrapW(wstr) kernel32.GetFileAttributesW
76  stdcall -noname GetFullPathNameWrapW(wstr long ptr ptr) kernel32.GetFullPathNameW
77  stdcall -noname GetLocaleInfoWrapW(long long ptr long) kernel32.GetLocaleInfoW
78  stdcall -noname GetMenuStringWrapW(long long ptr long long) user32.GetMenuStringW
79  stdcall -noname GetMessageWrapW(ptr long long long) user32.GetMessageW
80  stdcall -noname GetModuleFileNameWrapW(long ptr long) kernel32.GetModuleFileNameW
81  stdcall -noname GetSystemDirectoryWrapW(ptr long) kernel32.GetSystemDirectoryW
82  stdcall -noname SearchPathWrapW(wstr wstr wstr long ptr ptr) kernel32.SearchPathW
83  stdcall -noname GetModuleHandleWrapW(wstr) kernel32.GetModuleHandleW
84  stdcall -noname GetObjectWrapW(long long ptr) gdi32.GetObjectW
85  stdcall -noname GetPrivateProfileIntWrapW(wstr wstr long wstr) kernel32.GetPrivateProfileIntW
86  stdcall -noname GetProfileStringWrapW(wstr wstr wstr ptr long) kernel32.GetProfileStringW
87  stdcall -noname GetPropWrapW(long wstr) user32.GetPropW
88  stdcall -noname GetStringTypeExWrapW(long long wstr long ptr) kernel32.GetStringTypeExW
89  stdcall -noname GetTempFileNameWrapW(wstr wstr long ptr) kernel32.GetTempFileNameW
90  stdcall -noname GetTempPathWrapW(long ptr) kernel32.GetTempPathW
91  stdcall -noname GetTextExtentPoint32WrapW(long wstr long ptr) gdi32.GetTextExtentPoint32W
92  stdcall -noname GetTextFaceWrapW(long long ptr) gdi32.GetTextFaceW
93  stdcall -noname GetTextMetricsWrapW(long ptr) gdi32.GetTextMetricsW
94  stdcall -noname GetWindowLongWrapW(long long) user32.GetWindowLongW
95  stdcall -noname GetWindowTextWrapW(long ptr long) user32.GetWindowTextW
96  stdcall -noname GetWindowTextLengthWrapW(long) user32.GetWindowTextLengthW
97  stdcall -noname GetWindowsDirectoryWrapW(ptr long) kernel32.GetWindowsDirectoryW
98  stdcall -noname InsertMenuWrapW(long long long long ptr) user32.InsertMenuW
99  stdcall -noname IsDialogMessageWrapW(long ptr) user32.IsDialogMessageW
100 stdcall -noname LoadAcceleratorsWrapW(long wstr) user32.LoadAcceleratorsW
101 stdcall -noname LoadBitmapWrapW(long wstr) user32.LoadBitmapW
102 stdcall -noname LoadCursorWrapW(long wstr) user32.LoadCursorW
103 stdcall -noname LoadIconWrapW(long wstr) user32.LoadIconW
104 stdcall -noname LoadImageWrapW(long wstr long long long long) user32.LoadImageW
105 stdcall -noname LoadLibraryExWrapW(wstr long long) kernel32.LoadLibraryExW
106 stdcall -noname LoadMenuWrapW(long wstr) user32.LoadMenuW
107 stdcall -noname LoadStringWrapW(long long ptr long) user32.LoadStringW
108 stdcall -noname MessageBoxIndirectWrapW(ptr) user32.MessageBoxIndirectW
109 stdcall -noname ModifyMenuWrapW(long long long long ptr) user32.ModifyMenuW
110 stdcall -noname GetCharWidth32WrapW(long long long long) gdi32.GetCharWidth32W
111 stdcall -noname GetCharacterPlacementWrapW(long wstr long long ptr long) gdi32.GetCharacterPlacementW
112 stdcall -noname CopyFileWrapW(wstr wstr long) kernel32.CopyFileW
113 stdcall -noname MoveFileWrapW(wstr wstr) kernel32.MoveFileW
114 stdcall -noname OemToCharWrapW(ptr ptr) user32.OemToCharW
115 stdcall -noname OutputDebugStringWrapW(wstr) kernel32.OutputDebugStringW
116 stdcall -noname PeekMessageWrapW(ptr long long long long) user32.PeekMessageW
117 stdcall -noname PostMessageWrapW(long long long long) user32.PostMessageW
118 stdcall -noname PostThreadMessageWrapW(long long long long) user32.PostThreadMessageW
119 stdcall -noname RegCreateKeyWrapW(long wstr ptr) advapi32.RegCreateKeyW
120 stdcall -noname RegCreateKeyExWrapW(long wstr long ptr long long ptr ptr ptr) advapi32.RegCreateKeyExW
121 stdcall -noname RegDeleteKeyWrapW(long wstr) advapi32.RegDeleteKeyW
122 stdcall -noname RegEnumKeyWrapW(long long ptr long) advapi32.RegEnumKeyW
123 stdcall -noname RegEnumKeyExWrapW(long long ptr ptr ptr ptr ptr ptr) advapi32.RegEnumKeyExW
124 stdcall -noname RegOpenKeyWrapW(long wstr ptr) advapi32.RegOpenKeyW
125 stdcall -noname RegOpenKeyExWrapW(long wstr long long ptr) advapi32.RegOpenKeyExW
126 stdcall -noname RegQueryInfoKeyWrapW(long ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr) advapi32.RegQueryInfoKeyW
127 stdcall -noname RegQueryValueWrapW(long wstr ptr ptr) advapi32.RegQueryValueW
128 stdcall -noname RegQueryValueExWrapW(long wstr ptr ptr ptr ptr) advapi32.RegQueryValueExW
129 stdcall -noname RegSetValueWrapW(long wstr long ptr long) advapi32.RegSetValueW
130 stdcall -noname RegSetValueExWrapW(long wstr long long ptr long) advapi32.RegSetValueExW
131 stdcall -noname RegisterClassWrapW(ptr) user32.RegisterClassW
132 stdcall -noname RegisterClipboardFormatWrapW(wstr) user32.RegisterClipboardFormatW
133 stdcall -noname RegisterWindowMessageWrapW(wstr) user32.RegisterWindowMessageW
134 stdcall -noname RemovePropWrapW(long wstr) user32.RemovePropW
135 stdcall -noname SendDlgItemMessageWrapW(long long long long long) user32.SendDlgItemMessageW
136 stdcall -noname SendMessageWrapW(long long long long) user32.SendMessageW
137 stdcall -noname SetCurrentDirectoryWrapW(wstr) kernel32.SetCurrentDirectoryW
138 stdcall -noname SetDlgItemTextWrapW(long long wstr) user32.SetDlgItemTextW
139 stdcall -noname SetMenuItemInfoWrapW(long long long ptr) user32.SetMenuItemInfoW
140 stdcall -noname SetPropWrapW(long wstr long) user32.SetPropW
141 stdcall -noname SetWindowLongWrapW(long long long) user32.SetWindowLongW
142 stdcall -noname SetWindowsHookExWrapW(long long long long) user32.SetWindowsHookExW
143 stdcall -noname SetWindowTextWrapW(long wstr) user32.SetWindowTextW
144 stdcall -noname StartDocWrapW(long ptr) gdi32.StartDocW
145 stdcall -noname SystemParametersInfoWrapW(long long ptr long) user32.SystemParametersInfoW
146 stdcall -noname TranslateAcceleratorWrapW(long long ptr) user32.TranslateAcceleratorW
147 stdcall -noname UnregisterClassWrapW(wstr long) user32.UnregisterClassW
148 stdcall -noname VkKeyScanWrapW(long) user32.VkKeyScanW
149 stdcall -noname WinHelpWrapW(long wstr long long) user32.WinHelpW
150 stdcall -noname wvsprintfWrapW(ptr wstr ptr) user32.wvsprintfW
151 stdcall StrCmpNCA(str ptr long)
152 stdcall StrCmpNCW(wstr wstr long)
153 stdcall StrCmpNICA(long long long)
154 stdcall StrCmpNICW(wstr wstr long)
155 stdcall -ordinal StrCmpCA(str str)
156 stdcall -ordinal StrCmpCW(wstr wstr)
157 stdcall -ordinal StrCmpICA(str str)
158 stdcall -ordinal StrCmpICW(wstr wstr)
159 stdcall -noname CompareStringAltW(long long wstr long wstr long) kernel32.CompareStringW
160 stdcall -noname SHAboutInfoA(ptr long)
161 stdcall -noname SHAboutInfoW(ptr long)
162 stdcall -noname SHTruncateString(str long)
163 stdcall -noname IUnknown_QueryStatus(ptr ptr long ptr ptr)
164 stdcall -noname IUnknown_Exec(ptr ptr long long ptr ptr)
165 stdcall -noname SHSetWindowBits(long long long long)
166 stdcall -noname SHIsEmptyStream(ptr)
167 stdcall -noname SHSetParentHwnd(long ptr)
168 stdcall -noname ConnectToConnectionPoint(ptr ptr long ptr ptr ptr)
169 stdcall -noname IUnknown_AtomicRelease(long)
170 stdcall -noname PathSkipLeadingSlashesA(str)
171 stdcall -noname SHIsSameObject(ptr ptr)
172 stdcall -noname IUnknown_GetWindow(ptr ptr)
173 stdcall -noname IUnknown_SetOwner(ptr ptr)
174 stdcall -noname IUnknown_SetSite(ptr ptr)
175 stdcall -noname IUnknown_GetClassID(ptr ptr)
176 stdcall -noname IUnknown_QueryService(ptr ptr ptr ptr)
177 stdcall -noname SHLoadMenuPopup(ptr wstr)
178 stdcall -noname SHPropagateMessage(ptr long long long long)
179 stdcall -noname SHMenuIndexFromID(long long)
180 stdcall -noname SHRemoveAllSubMenus(long)
181 stdcall -noname SHEnableMenuItem(long long long)
182 stdcall -noname SHCheckMenuItem(long long long)
183 stdcall -noname SHRegisterClassA(ptr)
184 stdcall -noname IStream_Read(ptr ptr long) 
185 stdcall -noname SHMessageBoxCheckA(ptr str str long long str)
186 stdcall -noname SHSimulateDrop(ptr ptr long ptr ptr)
187 stdcall -noname SHLoadFromPropertyBag(ptr ptr)
188 stdcall -noname IUnknown_TranslateAcceleratorOCS(ptr ptr long)
189 stdcall -noname IUnknown_OnFocusOCS(ptr ptr)
190 stdcall -noname IUnknown_HandleIRestrict(ptr ptr ptr ptr ptr)
191 stdcall -noname SHMessageBoxCheckW(ptr wstr wstr long long wstr)
192 stdcall -noname SHGetMenuFromID(ptr long)
193 stdcall -noname SHGetCurColorRes()
194 stdcall -noname SHWaitForSendMessageThread(ptr long)
195 stdcall -noname SHIsExpandableFolder(ptr ptr)
196 stdcall -noname SHVerbExistsNA(str ptr ptr long)
197 stdcall -noname SHFillRectClr(long ptr long)
198 stdcall -noname SHSearchMapInt(ptr ptr long long)
199 stdcall -noname IUnknown_Set(ptr ptr)
200 stdcall -noname MayQSForward(ptr ptr ptr long ptr ptr)
201 stdcall -noname MayExecForward(ptr long ptr long long ptr ptr)
202 stdcall -noname IsQSForward(ptr long ptr)
203 stdcall -noname SHStripMneumonicA(str)
204 stdcall -noname SHIsChildOrSelf(long long)
205 stdcall -noname SHGetValueGoodBootA(long str str ptr ptr ptr)
206 stdcall -noname SHGetValueGoodBootW(long wstr wstr ptr ptr ptr)
207 stdcall -noname IContextMenu_Invoke(ptr ptr str long)
208 stdcall -noname FDSA_Initialize(long long ptr ptr long)
209 stdcall -noname FDSA_Destroy(ptr)
210 stdcall -noname FDSA_InsertItem(ptr long ptr)
211 stdcall -noname FDSA_DeleteItem(ptr long)
212 stdcall -noname IStream_Write(ptr ptr long) 
213 stdcall -noname IStream_Reset(ptr)
214 stdcall -noname IStream_Size(ptr ptr)
215 stdcall -noname SHAnsiToUnicode(str ptr long)
216 stdcall -noname SHAnsiToUnicodeCP(long str ptr long)
217 stdcall -noname SHUnicodeToAnsi(wstr ptr ptr)
218 stdcall -noname SHUnicodeToAnsiCP(long wstr ptr long)
219 stdcall QISearch(long long long long)
220 stdcall -noname SHSetDefaultDialogFont(ptr long)
221 stdcall -noname SHRemoveDefaultDialogFont(ptr)
222 stdcall -noname SHGlobalCounterCreate(long)
223 stdcall -noname SHGlobalCounterGetValue(long)
224 stdcall -noname SHGlobalCounterIncrement(long)
225 stdcall -noname SHStripMneumonicW(wstr)
226 stdcall -noname ZoneCheckPathA(str long long ptr)
227 stdcall -noname ZoneCheckPathW(wstr long long ptr)
228 stdcall -noname ZoneCheckUrlA(str long long ptr)
229 stdcall -noname ZoneCheckUrlW(wstr long long ptr)
230 stdcall -noname ZoneCheckUrlExA(str ptr long long long long long long)
231 stdcall -noname ZoneCheckUrlExW(wstr ptr long long long long long long)
232 stdcall -noname ZoneCheckUrlExCacheA(str ptr long ptr long long long ptr ptr)
233 stdcall -noname ZoneCheckUrlExCacheW(wstr ptr long ptr long long long ptr ptr)
234 stdcall -noname ZoneCheckHost(ptr long long)
235 stdcall -noname ZoneCheckHostEx(ptr ptr long ptr long long long)
236 stdcall -noname SHPinDllOfCLSID(ptr)
237 stdcall -noname SHRegisterClassW(ptr)
238 stdcall -noname SHUnregisterClassesA(ptr ptr long)
239 stdcall -noname SHUnregisterClassesW(ptr ptr long)
240 stdcall -noname SHDefWindowProc(long long long long)
241 stdcall -noname StopWatchMode()
242 stdcall -noname StopWatchFlush()
243 stdcall -noname StopWatchA(long str long long long)
244 stdcall -noname StopWatchW(long wstr long long long)
245 stdcall -noname StopWatch_TimerHandler(ptr ptr long ptr)
246 stdcall -noname StopWatch_CheckMsg(ptr ptr str)
247 stdcall -noname StopWatch_MarkFrameStart(str)
248 stdcall -noname StopWatch_MarkSameFrameStart(ptr)
249 stdcall -noname StopWatch_MarkJavaStop(wstr ptr long)
250 stdcall -noname GetPerfTime()
251 stdcall -noname StopWatch_DispatchTime(long ptr long)
252 stdcall -noname StopWatch_SetMsgLastLocation(long)
253 stdcall -noname StopWatchExA(long str long long long long)
254 stdcall -noname StopWatchExW(long wstr long long long long)
255 stdcall -noname EventTraceHandler(long ptr)
256 stdcall -noname IUnknown_GetSite(ptr ptr ptr)
257 stdcall -noname SHCreateWorkerWindowA(long ptr long long ptr long)
258 stdcall -noname SHRegisterWaitForSingleObject(ptr ptr ptr long str long)
259 stdcall -noname SHUnregisterWait(ptr)
260 stdcall -noname SHQueueUserWorkItem(long long long long long long long)
261 stdcall -noname SHCreateTimerQueue()
262 stdcall -noname SHDeleteTimerQueue(ptr)
263 stdcall -noname SHSetTimerQueueTimer(long ptr ptr long long str long)
264 stdcall -noname SHChangeTimerQueueTimer(ptr ptr long long)
265 stdcall -noname SHCancelTimerQueueTimer(ptr ptr)
266 stdcall -noname SHRestrictionLookup(long wstr ptr ptr)
267 stdcall -noname SHWeakQueryInterface(long long long long)
268 stdcall -noname SHWeakReleaseInterface(long long)
269 stdcall -noname GUIDFromStringA(str ptr)
270 stdcall -noname GUIDFromStringW(wstr ptr)
271 stdcall -noname SHGetRestriction(wstr wstr wstr)
272 stdcall -noname SHSetThreadPoolLimits(ptr)
273 stdcall -noname SHTerminateThreadPool()
274 stdcall -noname RegisterGlobalHotkeyW(long long wstr)
275 stdcall -noname RegisterGlobalHotkeyA(long long str)
276 stdcall -noname WhichPlatform()
277 stdcall -noname SHDialogBox(ptr wstr ptr ptr ptr)
278 stdcall -noname SHCreateWorkerWindowW(long long long long long long)
279 stdcall -noname SHInvokeDefaultCommand(ptr ptr ptr)
280 stdcall -noname SHRegGetIntW(ptr wstr long)
281 stdcall -noname SHPackDispParamsV(ptr ptr long ptr)
282 varargs -noname SHPackDispParams(ptr ptr long)
283 stdcall -noname IConnectionPoint_InvokeWithCancel(ptr long long long long)
284 stdcall -noname IConnectionPoint_SimpleInvoke(ptr long ptr)
285 stdcall -noname IConnectionPoint_OnChanged(ptr long)
286 varargs -noname IUnknown_CPContainerInvokeParam(ptr ptr long ptr long)
287 stdcall -noname IUnknown_CPContainerOnChanged(ptr long)
288 stdcall -noname IUnknown_CPContainerInvokeIndirect(ptr ptr ptr)
289 stdcall -noname PlaySoundWrapW(wstr long long)
290 stdcall -noname SHMirrorIcon(ptr ptr)
291 stdcall -noname SHMessageBoxCheckExA(ptr ptr ptr ptr ptr long str)
292 stdcall -noname SHMessageBoxCheckExW(ptr ptr ptr ptr ptr long wstr)
293 stdcall -noname SHCancelUserWorkItems(ptr long)
294 stdcall -noname SHGetIniStringW(wstr wstr ptr long wstr)
295 stdcall -noname SHSetIniStringW(wstr ptr wstr wstr)
296 stdcall -noname CreateURLFileContentsW(wstr ptr)
297 stdcall -noname CreateURLFileContentsA(str ptr)
298 stdcall -noname WritePrivateProfileStringWrapW(wstr wstr wstr wstr) kernel32.WritePrivateProfileStringW
299 stdcall -noname ExtTextOutWrapW(long long long long ptr wstr long ptr) gdi32.ExtTextOutW
300 stdcall -noname CreateFontWrapW(long long long long long long long long long long long long long wstr) gdi32.CreateFontW
301 stdcall -noname DrawTextExWrapW(long wstr long ptr long ptr) user32.DrawTextExW
302 stdcall -noname GetMenuItemInfoWrapW(long long long ptr) user32.GetMenuItemInfoW
303 stdcall -noname InsertMenuItemWrapW(long long long ptr) user32.InsertMenuItemW
304 stdcall -noname CreateMetaFileWrapW(wstr) gdi32.CreateMetaFileW
305 stdcall -noname CreateMutexWrapW(ptr long wstr) kernel32.CreateMutexW
306 stdcall -noname ExpandEnvironmentStringsWrapW(wstr ptr long) kernel32.ExpandEnvironmentStringsW
307 stdcall -noname CreateSemaphoreWrapW(ptr long long wstr) kernel32.CreateSemaphoreW
308 stdcall -noname IsBadStringPtrWrapW(ptr long) kernel32.IsBadStringPtrW
309 stdcall -noname LoadLibraryWrapW(wstr) kernel32.LoadLibraryW
310 stdcall -noname GetTimeFormatWrapW(long long ptr wstr ptr long) kernel32.GetTimeFormatW
311 stdcall -noname GetDateFormatWrapW(long long ptr wstr ptr long) kernel32.GetDateFormatW
312 stdcall -noname GetPrivateProfileStringWrapW(wstr wstr wstr ptr long wstr) kernel32.GetPrivateProfileStringW
313 stdcall -noname SHGetFileInfoWrapW(ptr long ptr long long)
314 stdcall -noname RegisterClassExWrapW(ptr) user32.RegisterClassExW
315 stdcall -noname GetClassInfoExWrapW(long wstr ptr) user32.GetClassInfoExW
316 stdcall -noname IShellFolder_GetDisplayNameOf(ptr ptr long str long)
317 stdcall -noname IShellFolder_ParseDisplayName(ptr ptr ptr str ptr ptr ptr)
318 stdcall -noname DragQueryFileWrapW(long long wstr long)
319 stdcall -noname FindWindowExWrapW(long long wstr wstr) user32.FindWindowExW
320 stdcall -noname RegisterMIMETypeForExtensionA(str str)
321 stdcall -noname RegisterMIMETypeForExtensionW(wstr wstr)
322 stdcall -noname UnregisterMIMETypeForExtensionA(str)
323 stdcall -noname UnregisterMIMETypeForExtensionW(wstr)
324 stdcall -noname RegisterExtensionForMIMETypeA(str str)
325 stdcall -noname RegisterExtensionForMIMETypeW(wstr wstr)
326 stdcall -noname UnregisterExtensionForMIMETypeA(str)
327 stdcall -noname UnregisterExtensionForMIMETypeW(wstr)
328 stdcall -noname GetMIMETypeSubKeyA(str ptr long)
329 stdcall -noname GetMIMETypeSubKeyW(wstr ptr long)
330 stdcall -noname MIME_GetExtensionA(str ptr long)
331 stdcall -noname MIME_GetExtensionW(wstr ptr long)
332 stdcall -noname CallMsgFilterWrapW(ptr long) user32.CallMsgFilterW
333 stdcall -noname SHBrowseForFolderWrapW(ptr)
334 stdcall -noname SHGetPathFromIDListWrapW(ptr ptr)
335 stdcall -noname ShellExecuteExWrapW(ptr)
336 stdcall -noname SHFileOperationWrapW(ptr)
337 stdcall -noname ExtractIconExWrapW(wstr long ptr ptr long) user32.PrivateExtractIconExW
338 stdcall -noname SetFileAttributesWrapW(wstr long) kernel32.SetFileAttributesW
339 stdcall -noname GetNumberFormatWrapW(long long wstr ptr ptr long) kernel32.GetNumberFormatW
340 stdcall -noname MessageBoxWrapW(long wstr wstr long) user32.MessageBoxW
341 stdcall -noname FindNextFileWrapW(long ptr) kernel32.FindNextFileW
342 stdcall -noname SHInterlockedCompareExchange(ptr ptr ptr)
343 stdcall -noname SHRegGetCLSIDKeyA(ptr str long long ptr)
344 stdcall -noname SHRegGetCLSIDKeyW(ptr wstr long long ptr)
345 stdcall -noname SHAnsiToAnsi(str ptr long)
346 stdcall -noname SHUnicodeToUnicode(wstr ptr long)
347 stdcall -noname RegDeleteValueWrapW(long wstr) advapi32.RegDeleteValueW
348 stdcall -noname SHGetFileDescriptionW(wstr wstr wstr wstr ptr)
349 stdcall -noname SHGetFileDescriptionA(str str str str ptr)
350 stdcall -noname GetFileVersionInfoSizeWrapW(wstr ptr)
351 stdcall -noname GetFileVersionInfoWrapW(wstr long long ptr)
352 stdcall -noname VerQueryValueWrapW(ptr wstr ptr ptr)
353 stdcall -noname SHFormatDateTimeA(ptr ptr str long)
354 stdcall -noname SHFormatDateTimeW(ptr ptr wstr long)
355 stdcall -noname IUnknown_EnableModeless(ptr long)
356 stdcall AssocCreate(int128 ptr ptr)
357 stdcall -noname SHGetNewLinkInfoWrapW(wstr wstr wstr long long)
358 stdcall -noname SHDefExtractIconWrapW(wstr long long ptr ptr long)
359 stdcall -noname OpenEventWrapW(long long wstr) kernel32.OpenEventW
360 stdcall -noname RemoveDirectoryWrapW(wstr) kernel32.RemoveDirectoryW
361 stdcall -noname GetShortPathNameWrapW(wstr ptr long) kernel32.GetShortPathNameW
362 stdcall -noname GetUserNameWrapW(ptr ptr) advapi32.GetUserNameW
363 stdcall -noname SHInvokeCommand(ptr ptr ptr long)
364 stdcall -noname DoesStringRoundTripA(str ptr long)
365 stdcall -noname DoesStringRoundTripW(wstr ptr long)
366 stdcall -noname RegEnumValueWrapW(long long ptr ptr ptr ptr ptr ptr) advapi32.RegEnumValueW
367 stdcall -noname WritePrivateProfileStructWrapW(wstr wstr ptr long wstr) kernel32.WritePrivateProfileStructW
368 stdcall -noname GetPrivateProfileStructWrapW(wstr wstr ptr long wstr) kernel32.GetPrivateProfileStructW
369 stdcall -noname CreateProcessWrapW(wstr wstr ptr ptr long long ptr wstr ptr ptr) kernel32.CreateProcessW
370 stdcall -noname ExtractIconWrapW(long wstr long)
371 stdcall -noname DdeInitializeWrapW(ptr ptr long long) user32.DdeInitializeW
372 stdcall -noname DdeCreateStringHandleWrapW(long ptr long) user32.DdeCreateStringHandleW
373 stdcall -noname DdeQueryStringWrapW(long ptr wstr long long) user32.DdeQueryStringW
374 stdcall -noname SHCheckDiskForMediaA(ptr ptr str long)
375 stdcall -noname SHCheckDiskForMediaW(ptr ptr wstr long)
376 stdcall -noname MLGetUILanguage()
377 stdcall -noname MLLoadLibraryA(str long long)
378 stdcall -noname MLLoadLibraryW(wstr long long)
379 stdcall -noname Shell_GetCachedImageIndexWrapW(wstr long long)
380 stdcall -noname Shell_GetCachedImageIndexWrapA(str long long)
381 stdcall -noname AssocCopyVerbs(ptr ptr)
382 stdcall -noname ZoneComputePaneSize(ptr)
383 stdcall -noname ZoneConfigureW(ptr wstr)
384 stdcall -noname SHRestrictedMessageBox(ptr)
385 stdcall -noname SHLoadRawAccelerators(ptr str)
386 stdcall -noname SHQueryRawAccelerator(ptr long long ptr ptr)
387 stdcall -noname SHQueryRawAcceleratorMsg(ptr ptr ptr)
388 varargs -noname ShellMessageBoxWrapW(long long wstr wstr long)
389 stdcall -noname GetSaveFileNameWrapW(ptr)
390 stdcall -noname WNetRestoreConnectionWrapW(long wstr)
391 stdcall -noname WNetGetLastErrorWrapW(ptr ptr long ptr long)
392 stdcall -noname EndDialogWrap(ptr ptr) user32.EndDialog
393 stdcall -noname CreateDialogIndirectParamWrapW(long ptr long ptr long) user32.CreateDialogIndirectParamW
394 stdcall -noname SHChangeNotifyWrap(long long ptr ptr)
395 stdcall -noname MLWinHelpA(ptr str long long)
396 stdcall -noname MLHtmlHelpA(ptr str long long long)
397 stdcall -noname MLWinHelpW(ptr wstr long long)
398 stdcall -noname MLHtmlHelpW(ptr wstr long long long)
399 stdcall -noname StrCpyNXA(ptr str long)
400 stdcall -noname StrCpyNXW(ptr wstr long)
401 stdcall -noname PageSetupDlgWrapW(ptr)
402 stdcall -noname PrintDlgWrapW(ptr)
403 stdcall -noname GetOpenFileNameWrapW(ptr)
404 stdcall -noname IShellFolder_EnumObjects(ptr ptr long ptr) 
405 stdcall -noname MLBuildResURLA(str ptr long str ptr long)
406 stdcall -noname MLBuildResURLW(wstr ptr long wstr ptr long)
407 stdcall -noname AssocMakeProgid(long wstr ptr ptr)
408 stdcall -noname AssocMakeShell(long ptr wstr ptr)
409 stdcall -noname AssocMakeApplicationByKeyW(long ptr wstr)
410 stdcall -noname AssocMakeApplicationByKeyA(long ptr str)
411 stdcall -noname AssocMakeFileExtsToApplicationW(long str str)
412 stdcall -noname AssocMakeFileExtsToApplicationA(long str str)
413 stdcall -noname SHGetMachineInfo(long)
414 stdcall -noname SHHtmlHelpOnDemandW(ptr wstr long long long long)
415 stdcall -noname SHHtmlHelpOnDemandA(ptr str long long long long)
416 stdcall -noname SHWinHelpOnDemandW(long wstr long ptr long)
417 stdcall -noname SHWinHelpOnDemandA(long str long ptr long)
418 stdcall -noname MLFreeLibrary(long)
419 stdcall -noname SHFlushSFCacheWrap()
420 stdcall -noname SHPersistDataObject(ptr ptr)
421 stdcall -noname SHLoadPersistedDataObject(ptr ptr)
422 stdcall -noname SHGlobalCounterCreateNamedA(str long)
423 stdcall -noname SHGlobalCounterCreateNamedW(wstr long)
424 stdcall -noname SHGlobalCounterDecrement(long)
425 stdcall -noname DeleteMenuWrap(ptr long long) user32.DeleteMenu
426 stdcall -noname DestroyMenuWrap(long) user32.DestroyMenu
427 stdcall -noname TrackPopupMenuWrap(long long long long long long ptr) user32.TrackPopupMenu
428 stdcall -noname TrackPopupMenuExWrap(long long long long long ptr) user32.TrackPopupMenuEx
429 stdcall -noname MLIsMLHInstance(long)
430 stdcall -noname MLSetMLHInstance(long long)
431 stdcall -noname MLClearMLHInstance(long)
432 stdcall -noname SHSendMessageBroadcastA(long long long)
433 stdcall -noname SHSendMessageBroadcastW(long long long)
434 stdcall -noname SendMessageTimeoutWrapW(long long long long long long ptr) user32.SendMessageTimeoutW
435 stdcall -noname CLSIDFromProgIDWrap(wstr ptr)
436 stdcall -noname CLSIDFromStringWrap(wstr ptr)
437 stdcall -noname IsOS(long)
438 stdcall -noname SHLoadRegUIStringA(ptr str str long)
439 stdcall -noname SHLoadRegUIStringW(ptr wstr ptr long)
440 stdcall -noname SHGetWebFolderFilePathA(str ptr long)
441 stdcall -noname SHGetWebFolderFilePathW(wstr ptr long)
442 stdcall -noname GetEnvironmentVariableWrapW(wstr ptr long) kernel32.GetEnvironmentVariableW
443 stdcall -noname SHGetSystemWindowsDirectoryA(ptr long) kernel32.GetSystemWindowsDirectoryA
444 stdcall -noname SHGetSystemWindowsDirectoryW(ptr long) kernel32.GetSystemWindowsDirectoryW
445 stdcall -noname PathFileExistsAndAttributesA(str ptr)
446 stdcall -noname PathFileExistsAndAttributesW(wstr ptr)
447 stdcall -noname FixSlashesAndColonA(str)
448 stdcall -noname FixSlashesAndColonW(wstr)
449 stdcall -noname NextPathA(str str long)
450 stdcall -noname NextPathW(wstr wstr long)
451 stdcall -noname CharUpperNoDBCSA(str)
452 stdcall -noname CharUpperNoDBCSW(wstr)
453 stdcall -noname CharLowerNoDBCSA(str)
454 stdcall -noname CharLowerNoDBCSW(wstr)
455 stdcall -noname PathIsValidCharA(long long)
456 stdcall -noname PathIsValidCharW(long long)
457 stdcall -noname GetLongPathNameWrapW(wstr ptr long) kernel32.GetLongPathNameW
458 stdcall -noname GetLongPathNameWrapA(str ptr long) kernel32.GetLongPathNameA
459 stdcall -noname SHExpandEnvironmentStringsA(str ptr long) 
460 stdcall -noname SHExpandEnvironmentStringsW(wstr ptr long)
461 stdcall -noname SHGetAppCompatFlags(long)
462 stdcall -noname UrlFixupW(wstr wstr long)
463 stdcall -noname SHExpandEnvironmentStringsForUserA(ptr str ptr long) 
464 stdcall -noname SHExpandEnvironmentStringsForUserW(ptr wstr ptr long)
465 stdcall -noname PathUnExpandEnvStringsForUserA(ptr str ptr long)
466 stdcall -noname PathUnExpandEnvStringsForUserW(ptr wstr ptr long)
467 stdcall -noname SHRunIndirectRegClientCommand(ptr wstr)
468 stdcall -noname RunIndirectRegCommand(ptr ptr wstr wstr)
469 stdcall -noname RunRegCommand(ptr ptr wstr)
470 stdcall -noname IUnknown_ProfferServiceOld(ptr ptr ptr ptr ptr)
471 stdcall -noname SHCreatePropertyBagOnRegKey(long wstr long ptr ptr)
472 stdcall -noname SHCreatePropertyBagOnProfileSelection(wstr long long long long)
473 stdcall -noname SHGetIniStringUTF7W(wstr wstr wstr long wstr)
474 stdcall -noname SHSetIniStringUTF7W(wstr wstr wstr wstr)
475 stdcall -noname GetShellSecurityDescriptor(ptr long)
476 stdcall -noname SHGetObjectCompatFlags(ptr ptr)
477 stdcall -noname SHCreatePropertyBagOnMemory(long ptr ptr)
478 stdcall -noname IUnknown_TranslateAcceleratorIO(ptr ptr)
479 stdcall -noname IUnknown_UIActivateIO(ptr long ptr)
480 stdcall -noname UrlCrackW(wstr long long ptr)
481 stdcall -noname IUnknown_HasFocusIO(ptr)
482 stdcall -noname SHMessageBoxHelpA(ptr str str long long ptr long)
483 stdcall -noname SHMessageBoxHelpW(ptr wstr str long long ptr long)
484 stdcall -noname IUnknown_QueryServiceExec(ptr ptr ptr long long long ptr)
485 stdcall -noname MapWin32ErrorToSTG(long)
486 stdcall -noname ModeToCreateFileFlags(long long ptr ptr ptr)
487 stdcall -ordinal SHLoadIndirectString(wstr ptr long ptr)
488 stdcall -noname SHConvertGraphicsFile(wstr wstr long)
489 stdcall -noname GlobalAddAtomWrapW(wstr) kernel32.GlobalAddAtomW
490 stdcall -noname GlobalFindAtomWrapW(wstr) kernel32.GlobalFindAtomW
491 stdcall -noname SHGetShellKey(long long long)
492 stdcall -noname PrettifyFileDescriptionW(wstr wstr wstr)
493 stdcall -noname SHPropertyBag_ReadType(ptr wstr ptr long)
494 stdcall -noname SHPropertyBag_ReadStr(ptr wstr wstr long)
495 stdcall -noname SHPropertyBag_WriteStr(ptr wstr wstr)
496 stdcall -noname SHPropertyBag_ReadLONG(ptr wstr ptr)
497 stdcall -noname SHPropertyBag_WriteLONG(ptr wstr long)
498 stdcall -noname SHPropertyBag_ReadBOOLOld(ptr wstr long)
499 stdcall -noname SHPropertyBag_WriteBOOL(ptr wstr long)
505 stdcall -noname SHPropertyBag_ReadGUID(ptr wstr ptr)
506 stdcall -noname SHPropertyBag_WriteGUID(ptr wstr long)
507 stdcall -noname SHPropertyBag_ReadDWORD(ptr wstr ptr)
508 stdcall -noname SHPropertyBag_WriteDWORD(ptr wstr long)
509 stdcall -noname IUnknown_OnFocusChangeIS(ptr ptr long)
510 stdcall -noname SHLockSharedEx(ptr long long)
511 stdcall -noname PathFileExistsDefExtAndAttributesW(wstr ptr ptr)
512 stdcall -noname -ordinal IStream_ReadPidl(ptr ptr)
513 stdcall -noname -ordinal IStream_WritePidl(ptr ptr)
514 stdcall -noname IUnknown_ProfferService(ptr ptr ptr ptr)
515 stdcall -ordinal SHGetViewStatePropertyBag(ptr wstr long ptr ptr)
516 stdcall -noname SKGetValueW(long wstr wstr ptr ptr ptr)
517 stdcall -noname SKSetValueW(long wstr wstr long ptr long)
518 stdcall -noname SKDeleteValueW(long wstr wstr)
519 stdcall -noname SKAllocValueW(long wstr wstr ptr ptr ptr)
520 stdcall -noname SHPropertyBag_ReadBSTR(ptr wstr ptr)
521 stdcall -noname SHPropertyBag_ReadPOINTL(ptr wstr ptr)
522 stdcall -noname SHPropertyBag_WritePOINTL(ptr wstr ptr)
523 stdcall -noname SHPropertyBag_ReadRECTL(ptr wstr ptr)
524 stdcall -noname SHPropertyBag_WriteRECTL(ptr wstr ptr)
525 stdcall -noname SHPropertyBag_ReadPOINTS(ptr wstr ptr)
526 stdcall -noname SHPropertyBag_WritePOINTS(ptr wstr ptr)
527 stdcall -noname SHPropertyBag_ReadSHORT(ptr wstr ptr)
528 stdcall -noname SHPropertyBag_WriteSHORT(ptr wstr ptr)
529 stdcall -noname SHPropertyBag_ReadInt(ptr wstr ptr)
530 stdcall -noname SHPropertyBag_WriteInt(ptr wstr long)
531 stdcall -noname SHPropertyBag_ReadStream(ptr wstr ptr)
532 stdcall -noname SHPropertyBag_WriteStream(ptr wstr ptr)
533 stdcall -noname SHGetPerScreenResName(wstr long long)
534 stdcall -noname SHPropertyBag_ReadBOOL(ptr wstr ptr)
535 stdcall -noname SHPropertyBag_Delete(ptr wstr)
536 stdcall -noname IUnknown_QueryServicePropertyBag(ptr long long ptr)
537 stdcall -noname SHBoolSystemParametersInfo(long ptr)
538 stdcall -noname IUnknown_QueryServiceForWebBrowserApp(ptr ptr ptr)
539 stdcall -noname IUnknown_ShowBrowserBar(ptr long long)
540 stdcall -noname SHInvokeCommandOnContextMenu(ptr ptr ptr long str)
541 stdcall -noname SHInvokeCommandsOnContextMenu(ptr ptr ptr long str long)
542 stdcall -noname GetUIVersion()
543 stdcall -noname CreateColorSpaceWrapW(ptr) gdi32.CreateColorSpaceW
544 stdcall -noname QuerySourceCreateFromKey(ptr wstr long ptr ptr)
545 stdcall -noname SHForwardContextMenuMsg(ptr long long ptr ptr long)
546 stdcall -noname IUnknown_DoContextMenuPopup(ptr ptr long ptr)
547 stdcall DelayLoadFailureHook(str str) kernel32.DelayLoadFailureHook
548 stdcall -noname SHAreIconsEqual(ptr ptr)
549 stdcall -noname SHCoCreateInstanceAC(ptr ptr long ptr ptr)
550 stdcall -noname GetTemplateInfoFromHandle(ptr ptr ptr)
551 stdcall -noname IShellFolder_CompareIDs(ptr ptr ptr ptr)
552 stdcall -noname SHEvaluateSystemCommandTemplate(wstr wstr wstr wstr)
553 stdcall IsInternetESCEnabled()
554 stdcall -noname SHGetAllAccessSA(ptr ptr)
556 stdcall -noname SHCoExtensionAllowed(ptr ptr)
557 stdcall -noname SHCoCreateExtension(ptr ptr long long ptr ptr)
558 stdcall -noname SHCoExtensionCollectStats(ptr str long)
559 stdcall -noname SHGetSignatureInfo(wstr str ptr)
560 stdcall -noname SHWindowsPolicyGetValue(ptr ptr ptr)
561 stdcall -noname AssocGetUrlAction(wstr)
562 stdcall -noname SHGetPrivateProfileInt(wstr long long wstr)
563 stdcall -noname SHGetPrivateProfileSection(wstr long long wstr)
564 stdcall -noname SHGetPrivateProfileSectionNames(long long wstr)
565 stdcall -noname SHGetPrivateProfileString(wstr long long long long wstr)
566 stdcall -noname SHGetPrivateProfileStruct(wstr long long long wstr)


#This ordinal is for x86
500 stdcall -i386 AssocGetPerceivedType(wstr ptr ptr ptr)
501 stdcall -i386 AssocIsDangerous(wstr)
502 stdcall -i386 AssocQueryKeyA(long long str str ptr)
503 stdcall -i386 AssocQueryKeyW(long long wstr wstr ptr)
504 stdcall -i386 AssocQueryStringA(long long str str ptr ptr)
555 stdcall -i386 AssocQueryStringByKeyA(long long ptr str ptr ptr)
567 stdcall -i386 AssocQueryStringByKeyW(long long ptr wstr ptr ptr)
568 stdcall -i386 AssocQueryStringW(long long wstr wstr ptr ptr)
569 stdcall -i386 ChrCmpIA(long long)
570 stdcall -i386 ChrCmpIW(long long)
571 stdcall -i386 ColorAdjustLuma(long long long)
572 stdcall -i386 ColorHLSToRGB(long long long)
573 stdcall -i386 ColorRGBToHLS(long ptr ptr ptr)
@ stdcall -i386 -private DllGetVersion(ptr)
575 stdcall -i386 GetMenuPosFromID(ptr long)
576 stdcall -i386 HashData(ptr long ptr long)
577 stdcall -i386 IntlStrEqWorkerA(long str str long) StrIsIntlEqualA
578 stdcall -i386 IntlStrEqWorkerW(long wstr wstr long) StrIsIntlEqualW
579 stdcall -i386 IsCharSpaceA(long)
580 stdcall -i386 PathAddBackslashA(str)
581 stdcall -i386 PathAddBackslashW(wstr)
582 stdcall -i386 PathAddExtensionA(str str)
583 stdcall -i386 PathAddExtensionW(wstr wstr)
584 stdcall -i386 PathAppendA(str str)
585 stdcall -i386 PathAppendW(wstr wstr)
586 stdcall -i386 PathBuildRootA(ptr long)
587 stdcall -i386 PathBuildRootW(ptr long)
588 stdcall -i386 PathCanonicalizeA(ptr str)
589 stdcall -i386 PathCanonicalizeW(ptr wstr)
590 stdcall -i386 PathCombineA(ptr str str)
591 stdcall -i386 PathCombineW(ptr wstr wstr)
592 stdcall -i386 PathCommonPrefixA(str str ptr)
593 stdcall -i386 PathCommonPrefixW(wstr wstr ptr)
594 stdcall -i386 PathCompactPathA(long str long)
595 stdcall -i386 PathCompactPathExA(ptr str long long)
596 stdcall -i386 PathCompactPathExW(ptr wstr long long)
597 stdcall -i386 PathCompactPathW(long wstr long)
598 stdcall -i386 PathCreateFromUrlA(str ptr ptr long)
599 stdcall -i386 PathCreateFromUrlW(wstr ptr ptr long)
600 stdcall -i386 PathFileExistsA(str)
601 stdcall -i386 PathFileExistsW(wstr)
602 stdcall -i386 PathFindExtensionA(str)
603 stdcall -i386 PathFindExtensionW(wstr)
604 stdcall -i386 PathFindFileNameA(str)
605 stdcall -i386 PathFindFileNameW(wstr)
606 stdcall -i386 PathFindNextComponentA(str)
607 stdcall -i386 PathFindNextComponentW(wstr)
608 stdcall -i386 PathFindOnPathA(str ptr)
609 stdcall -i386 PathFindOnPathW(wstr ptr)
610 stdcall -i386 PathFindSuffixArrayA(str ptr long)
611 stdcall -i386 PathFindSuffixArrayW(wstr ptr long)
612 stdcall -i386 PathGetArgsA(str)
613 stdcall -i386 PathGetArgsW(wstr)
614 stdcall -i386 PathGetCharTypeA(long)
615 stdcall -i386 PathGetCharTypeW(long)
616 stdcall -i386 PathGetDriveNumberA(str)
617 stdcall -i386 PathGetDriveNumberW(wstr)
618 stdcall -i386 PathIsContentTypeA(str str)
619 stdcall -i386 PathIsContentTypeW(wstr wstr)
620 stdcall -i386 PathIsDirectoryA(str)
621 stdcall -i386 PathIsDirectoryEmptyA(str)
622 stdcall -i386 PathIsDirectoryEmptyW(wstr)
623 stdcall -i386 PathIsDirectoryW(wstr)
624 stdcall -i386 PathIsFileSpecA(str)
625 stdcall -i386 PathIsFileSpecW(wstr)
626 stdcall -i386 PathIsLFNFileSpecA(str)
627 stdcall -i386 PathIsLFNFileSpecW(wstr)
628 stdcall -i386 PathIsNetworkPathA(str)
629 stdcall -i386 PathIsNetworkPathW(wstr)
630 stdcall -i386 PathIsPrefixA(str str)
631 stdcall -i386 PathIsPrefixW(wstr wstr)
632 stdcall -i386 PathIsRelativeA(str)
633 stdcall -i386 PathIsRelativeW(wstr)
634 stdcall -i386 PathIsRootA(str)
635 stdcall -i386 PathIsRootW(wstr)
636 stdcall -i386 PathIsSameRootA(str str)
637 stdcall -i386 PathIsSameRootW(wstr wstr)
638 stdcall -i386 PathIsSystemFolderA(str long)
639 stdcall -i386 PathIsSystemFolderW(wstr long)
640 stdcall -i386 PathIsUNCA(str)
641 stdcall -i386 PathIsUNCServerA(str)
642 stdcall -i386 PathIsUNCServerShareA(str)
643 stdcall -i386 PathIsUNCServerShareW(wstr)
644 stdcall -i386 PathIsUNCServerW(wstr)
645 stdcall -i386 PathIsUNCW(wstr)
646 stdcall -i386 PathIsURLA(str)
647 stdcall -i386 PathIsURLW(wstr)
648 stdcall -i386 PathMakePrettyA(str)
649 stdcall -i386 PathMakePrettyW(wstr)
650 stdcall -i386 PathMakeSystemFolderA(str)
651 stdcall -i386 PathMakeSystemFolderW(wstr)
652 stdcall -i386 PathMatchSpecA(str str)
653 stdcall -i386 PathMatchSpecW(wstr wstr)
654 stdcall -i386 PathParseIconLocationA(str)
655 stdcall -i386 PathParseIconLocationW(wstr)
656 stdcall -i386 PathQuoteSpacesA(str)
657 stdcall -i386 PathQuoteSpacesW(wstr)
658 stdcall -i386 PathRelativePathToA(ptr str long str long)
659 stdcall -i386 PathRelativePathToW(ptr wstr long wstr long)
660 stdcall -i386 PathRemoveArgsA(str)
661 stdcall -i386 PathRemoveArgsW(wstr)
662 stdcall -i386 PathRemoveBackslashA(str)
663 stdcall -i386 PathRemoveBackslashW(wstr)
664 stdcall -i386 PathRemoveBlanksA(str)
665 stdcall -i386 PathRemoveBlanksW(wstr)
666 stdcall -i386 PathRemoveExtensionA(str)
667 stdcall -i386 PathRemoveExtensionW(wstr)
668 stdcall -i386 PathRemoveFileSpecA(str)
669 stdcall -i386 PathRemoveFileSpecW(wstr)
670 stdcall -i386 PathRenameExtensionA(str str)
671 stdcall -i386 PathRenameExtensionW(wstr wstr)
672 stdcall -i386 PathSearchAndQualifyA(str ptr long)
673 stdcall -i386 PathSearchAndQualifyW(wstr ptr long)
674 stdcall -i386 PathSetDlgItemPathA(long long ptr)
675 stdcall -i386 PathSetDlgItemPathW(long long ptr)
676 stdcall -i386 PathSkipRootA(str)
677 stdcall -i386 PathSkipRootW(wstr)
678 stdcall -i386 PathStripPathA(str)
679 stdcall -i386 PathStripPathW(wstr)
680 stdcall -i386 PathStripToRootA(str)
681 stdcall -i386 PathStripToRootW(wstr)
682 stdcall -i386 PathUnExpandEnvStringsA(str ptr long)
683 stdcall -i386 PathUnExpandEnvStringsW(wstr ptr long)
684 stdcall -i386 PathUndecorateA(str)
685 stdcall -i386 PathUndecorateW(wstr)
686 stdcall -i386 PathUnmakeSystemFolderA(str)
687 stdcall -i386 PathUnmakeSystemFolderW(wstr)
688 stdcall -i386 PathUnquoteSpacesA(str)
689 stdcall -i386 PathUnquoteSpacesW(wstr)
690 stdcall -i386 SHAutoComplete(ptr long)
691 stdcall -i386 SHCopyKeyA(long str long long)
692 stdcall -i386 SHCopyKeyW(long wstr long long)
693 stdcall -i386 SHCreateShellPalette(long)
694 stdcall -i386 SHCreateStreamOnFileA(str long ptr)
695 stdcall -i386 SHCreateStreamOnFileEx(wstr long long long ptr ptr)
696 stdcall -i386 SHCreateStreamOnFileW(wstr long ptr)
697 stdcall -i386 SHCreateStreamWrapper(ptr ptr long ptr)
698 stdcall -i386 SHCreateThreadRef(ptr ptr)
699 stdcall -i386 SHDeleteEmptyKeyA(long ptr)
700 stdcall -i386 SHDeleteEmptyKeyW(long ptr)
701 stdcall -i386 SHDeleteKeyA(long str)
702 stdcall -i386 SHDeleteKeyW(long wstr)
703 stdcall -i386 SHDeleteOrphanKeyA(long str)
704 stdcall -i386 SHDeleteOrphanKeyW(long wstr)
705 stdcall -i386 SHDeleteValueA(long str str)
706 stdcall -i386 SHDeleteValueW(long wstr wstr)
707 stdcall -i386 SHEnumKeyExA(long long str ptr)
708 stdcall -i386 SHEnumKeyExW(long long wstr ptr)
709 stdcall -i386 SHEnumValueA(long long str ptr ptr ptr ptr)
710 stdcall -i386 SHEnumValueW(long long wstr ptr ptr ptr ptr)
711 stdcall -i386 SHGetInverseCMAP(ptr long)
712 stdcall -i386 SHGetThreadRef(ptr)
713 stdcall -i386 SHGetValueA(long str str ptr ptr ptr)
714 stdcall -i386 SHGetValueW(long wstr wstr ptr ptr ptr)
715 stdcall -i386 SHIsLowMemoryMachine(long)
716 stdcall -i386 SHOpenRegStream2A(long str str long)
717 stdcall -i386 SHOpenRegStream2W(long wstr wstr long)
718 stdcall -i386 SHOpenRegStreamA(long str str long)
719 stdcall -i386 SHOpenRegStreamW(long wstr wstr long)
720 stdcall -i386 SHQueryInfoKeyA(long ptr ptr ptr ptr)
721 stdcall -i386 SHQueryInfoKeyW(long ptr ptr ptr ptr)
722 stdcall -i386 SHQueryValueExA(long str ptr ptr ptr ptr)
723 stdcall -i386 SHQueryValueExW(long wstr ptr ptr ptr ptr)
724 stdcall -i386 SHRegCloseUSKey(ptr)
725 stdcall -i386 SHRegCreateUSKeyA(str long long ptr long)
726 stdcall -i386 SHRegCreateUSKeyW(wstr long long ptr long)
727 stdcall -i386 SHRegDeleteEmptyUSKeyA(long str long)
728 stdcall -i386 SHRegDeleteEmptyUSKeyW(long wstr long)
729 stdcall -i386 SHRegDeleteUSValueA(long str long)
730 stdcall -i386 SHRegDeleteUSValueW(long wstr long)
731 stdcall -i386 SHRegDuplicateHKey(long)
732 stdcall -i386 SHRegEnumUSKeyA(long long str ptr long)
733 stdcall -i386 SHRegEnumUSKeyW(long long wstr ptr long)
734 stdcall -i386 SHRegEnumUSValueA(long long ptr ptr ptr ptr ptr long)
735 stdcall -i386 SHRegEnumUSValueW(long long ptr ptr ptr ptr ptr long)
736 stdcall -i386 SHRegGetBoolUSValueA(str str long long)
737 stdcall -i386 SHRegGetBoolUSValueW(wstr wstr long long)
738 stdcall -i386 SHRegGetPathA(long str str ptr long)
739 stdcall -i386 SHRegGetPathW(long wstr wstr ptr long)
740 stdcall -i386 SHRegGetUSValueA(str str ptr ptr ptr long ptr long)
741 stdcall -i386 SHRegGetUSValueW(wstr wstr ptr ptr ptr long ptr long)
742 stdcall -i386 SHRegGetValueA(long str str long ptr ptr ptr) advapi32.RegGetValueA
743 stdcall -i386 SHRegGetValueW(long wstr wstr long ptr ptr ptr) advapi32.RegGetValueW
744 stdcall -i386 SHRegOpenUSKeyA(str long long long long)
745 stdcall -i386 SHRegOpenUSKeyW(wstr long long long long)
746 stdcall -i386 SHRegQueryInfoUSKeyA(long ptr ptr ptr ptr long)
747 stdcall -i386 SHRegQueryInfoUSKeyW(long ptr ptr ptr ptr long)
748 stdcall -i386 SHRegQueryUSValueA(long str ptr ptr ptr long ptr long)
749 stdcall -i386 SHRegQueryUSValueW(long wstr ptr ptr ptr long ptr long)
750 stdcall -i386 SHRegSetPathA(long str str str long)
751 stdcall -i386 SHRegSetPathW(long wstr wstr wstr long)
752 stdcall -i386 SHRegSetUSValueA(str str long ptr long long)
753 stdcall -i386 SHRegSetUSValueW(wstr wstr long ptr long long)
754 stdcall -i386 SHRegWriteUSValueA(long str long ptr long long)
755 stdcall -i386 SHRegWriteUSValueW(long wstr long ptr long long)
756 stdcall -i386 SHRegisterValidateTemplate(wstr long)
757 stdcall -i386 SHReleaseThreadRef()
758 stdcall -i386 SHSetThreadRef(ptr)
759 stdcall -i386 SHSetValueA(long str str long ptr long)
760 stdcall -i386 SHSetValueW(long wstr wstr long ptr long)
761 stdcall -i386 SHSkipJunction(ptr ptr)
762 stdcall -i386 SHStrDupA(str ptr)
763 stdcall -i386 SHStrDupW(wstr ptr)
764 stdcall -i386 StrCSpnA(str str)
765 stdcall -i386 StrCSpnIA(str str)
766 stdcall -i386 StrCSpnIW(wstr wstr)
767 stdcall -i386 StrCSpnW(wstr wstr)
768 stdcall -i386 StrCatBuffA(str str long)
769 stdcall -i386 StrCatBuffW(wstr wstr long)
770 stdcall -i386 StrCatChainW(wstr long long wstr)
771 stdcall -i386 StrCatW(ptr wstr)
772 stdcall -i386 StrChrA(str long)
773 stdcall -i386 StrChrIA(str long)
774 stdcall -i386 StrChrIW(wstr long)
775 stdcall -i386 StrChrNIW(wstr wstr long)
776 stdcall -i386 StrChrNW(wstr long long)
777 stdcall -i386 StrChrW(wstr long)
778 stdcall -i386 StrCmpIW(wstr wstr)
779 stdcall -i386 StrCmpLogicalW(wstr wstr)
780 stdcall -i386 StrCmpNA(str str long)
781 stdcall -i386 StrCmpNIA(str str long)
782 stdcall -i386 StrCmpNIW(wstr wstr long)
783 stdcall -i386 StrCmpNW(wstr wstr long)
784 stdcall -i386 StrCmpW(wstr wstr)
785 stdcall -i386 StrCpyNW(ptr wstr long)
786 stdcall -i386 StrCpyW(ptr wstr)
787 stdcall -i386 StrDupA(str)
788 stdcall -i386 StrDupW(wstr)
789 stdcall -i386 StrFormatByteSize64A(int64 ptr long)
790 stdcall -i386 StrFormatByteSizeA(long ptr long)
791 stdcall -i386 StrFormatByteSizeW(int64 ptr long)
792 stdcall -i386 StrFormatKBSizeA(int64 str long)
793 stdcall -i386 StrFormatKBSizeW(int64 wstr long)
794 stdcall -i386 StrFromTimeIntervalA(ptr long long long)
795 stdcall -i386 StrFromTimeIntervalW(ptr long long long)
796 stdcall -i386 StrIsIntlEqualA(long str str long)
797 stdcall -i386 StrIsIntlEqualW(long wstr wstr long)
798 stdcall -i386 StrNCatA(str str long)
799 stdcall -i386 StrNCatW(wstr wstr long)
800 stdcall -i386 StrPBrkA(str str)
801 stdcall -i386 StrPBrkW(wstr wstr)
802 stdcall -i386 StrRChrA(str str long)
803 stdcall -i386 StrRChrIA(str str long)
804 stdcall -i386 StrRChrIW(wstr wstr long)
805 stdcall -i386 StrRChrW(wstr wstr long)
806 stdcall -i386 StrRStrIA(str str str)
807 stdcall -i386 StrRStrIW(wstr wstr wstr)
808 stdcall -i386 StrRetToBSTR(ptr ptr ptr)
809 stdcall -i386 StrRetToBufA(ptr ptr ptr long)
810 stdcall -i386 StrRetToBufW(ptr ptr ptr long)
811 stdcall -i386 StrRetToStrA(ptr ptr ptr)
812 stdcall -i386 StrRetToStrW(ptr ptr ptr)
813 stdcall -i386 StrSpnA(str str)
814 stdcall -i386 StrSpnW(wstr wstr)
815 stdcall -i386 StrStrA(str str)
816 stdcall -i386 StrStrIA(str str)
817 stdcall -i386 StrStrIW(wstr wstr)
818 stdcall -i386 StrStrNIW(wstr wstr long)
819 stdcall -i386 StrStrNW(wstr wstr long)
820 stdcall -i386 StrStrW(wstr wstr)
821 stdcall -i386 StrToInt64ExA(str long ptr)
822 stdcall -i386 StrToInt64ExW(wstr long ptr)
823 stdcall -i386 StrToIntA(str)
824 stdcall -i386 StrToIntExA(str long ptr)
825 stdcall -i386 StrToIntExW(wstr long ptr)
826 stdcall -i386 StrToIntW(wstr)
827 stdcall -i386 StrTrimA(str str)
828 stdcall -i386 StrTrimW(wstr wstr)
829 stdcall -i386 UrlApplySchemeA(str ptr ptr long)
830 stdcall -i386 UrlApplySchemeW(wstr ptr ptr long)
831 stdcall -i386 UrlCanonicalizeA(str ptr ptr long)
832 stdcall -i386 UrlCanonicalizeW(wstr ptr ptr long)
833 stdcall -i386 UrlCombineA(str str ptr ptr long)
834 stdcall -i386 UrlCombineW(wstr wstr ptr ptr long)
835 stdcall -i386 UrlCompareA(str str long)
836 stdcall -i386 UrlCompareW(wstr wstr long)
837 stdcall -i386 UrlCreateFromPathA(str ptr ptr long)
838 stdcall -i386 UrlCreateFromPathW(wstr ptr ptr long)
839 stdcall -i386 UrlEscapeA(str ptr ptr long)
840 stdcall -i386 UrlEscapeW(wstr ptr ptr long)
841 stdcall -i386 UrlGetLocationA(str)
842 stdcall -i386 UrlGetLocationW(wstr)
843 stdcall -i386 UrlGetPartA(str ptr ptr long long)
844 stdcall -i386 UrlGetPartW(wstr ptr ptr long long)
845 stdcall -i386 UrlHashA(str ptr long)
846 stdcall -i386 UrlHashW(wstr ptr long)
847 stdcall -i386 UrlIsA(str long)
848 stdcall -i386 UrlIsNoHistoryA(str)
849 stdcall -i386 UrlIsNoHistoryW(wstr)
850 stdcall -i386 UrlIsOpaqueA(str)
851 stdcall -i386 UrlIsOpaqueW(wstr)
852 stdcall -i386 UrlIsW(wstr long)
853 stdcall -i386 UrlUnescapeA(str ptr ptr long)
854 stdcall -i386 UrlUnescapeW(wstr ptr ptr long)
855 varargs -i386 wnsprintfA(ptr long str)
856 varargs -i386 wnsprintfW(ptr long wstr)
857 stdcall -i386 wvnsprintfA(ptr long str ptr)
858 stdcall -i386 wvnsprintfW(ptr long wstr ptr)

#This ordinal is for x64
500 stdcall -arch=x86_64 -noname ualstrcpynW(wstr wstr long)
501 stdcall -arch=x86_64 -noname SHLWAPI_501(wstr wstr)
502 stdcall -arch=x86_64 -noname SHLWAPI_502(wstr wstr)
503 stdcall -arch=x86_64 -noname ualstrlenW(wstr)
504 stdcall -arch=x86_64 -noname ualstrcpyW(wstr wstr)

555 stdcall -arch=x86_64 AssocGetPerceivedType(wstr ptr ptr ptr)
567 stdcall -arch=x86_64 AssocIsDangerous(wstr)
568 stdcall -arch=x86_64 AssocQueryKeyA(long long str str ptr)
569 stdcall -arch=x86_64 AssocQueryKeyW(long long wstr wstr ptr)
570 stdcall -arch=x86_64 AssocQueryStringA(long long str str ptr ptr)
571 stdcall -arch=x86_64 AssocQueryStringByKeyA(long long ptr str ptr ptr)
572 stdcall -arch=x86_64 AssocQueryStringByKeyW(long long ptr wstr ptr ptr)
573 stdcall -arch=x86_64 AssocQueryStringW(long long wstr wstr ptr ptr)
574 stdcall -arch=x86_64 ChrCmpIA(long long)
575 stdcall -arch=x86_64 ChrCmpIW(long long)
576 stdcall -arch=x86_64 ColorAdjustLuma(long long long)
577 stdcall -arch=x86_64 ColorHLSToRGB(long long long)
578 stdcall -arch=x86_64 ColorRGBToHLS(long ptr ptr ptr)
579 stdcall -arch=x86_64 -private DllGetVersion(ptr)
580 stdcall -arch=x86_64 GetMenuPosFromID(ptr long)
581 stdcall -arch=x86_64 HashData(ptr long ptr long)
582 stdcall -arch=x86_64 IntlStrEqWorkerA(long str str long) StrIsIntlEqualA
583 stdcall -arch=x86_64 IntlStrEqWorkerW(long wstr wstr long) StrIsIntlEqualW
584 stdcall -arch=x86_64 IsCharSpaceA(long)
585 stdcall -arch=x86_64 PathAddBackslashA(str)
586 stdcall -arch=x86_64 PathAddBackslashW(wstr)
587 stdcall -arch=x86_64 PathAddExtensionA(str str)
588 stdcall -arch=x86_64 PathAddExtensionW(wstr wstr)
589 stdcall -arch=x86_64 PathAppendA(str str)
590 stdcall -arch=x86_64 PathAppendW(wstr wstr)
591 stdcall -arch=x86_64 PathBuildRootA(ptr long)
592 stdcall -arch=x86_64 PathBuildRootW(ptr long)
593 stdcall -arch=x86_64 PathCanonicalizeA(ptr str)
594 stdcall -arch=x86_64 PathCanonicalizeW(ptr wstr)
595 stdcall -arch=x86_64 PathCombineA(ptr str str)
596 stdcall -arch=x86_64 PathCombineW(ptr wstr wstr)
597 stdcall -arch=x86_64 PathCommonPrefixA(str str ptr)
598 stdcall -arch=x86_64 PathCommonPrefixW(wstr wstr ptr)
599 stdcall -arch=x86_64 PathCompactPathA(long str long)
600 stdcall -arch=x86_64 PathCompactPathExA(ptr str long long)
601 stdcall -arch=x86_64 PathCompactPathExW(ptr wstr long long)
602 stdcall -arch=x86_64 PathCompactPathW(long wstr long)
603 stdcall -arch=x86_64 PathCreateFromUrlA(str ptr ptr long)
604 stdcall -arch=x86_64 PathCreateFromUrlW(wstr ptr ptr long)
605 stdcall -arch=x86_64 PathFileExistsA(str)
606 stdcall -arch=x86_64 PathFileExistsW(wstr)
607 stdcall -arch=x86_64 PathFindExtensionA(str)
608 stdcall -arch=x86_64 PathFindExtensionW(wstr)
609 stdcall -arch=x86_64 PathFindFileNameA(str)
610 stdcall -arch=x86_64 PathFindFileNameW(wstr)
611 stdcall -arch=x86_64 PathFindNextComponentA(str)
612 stdcall -arch=x86_64 PathFindNextComponentW(wstr)
613 stdcall -arch=x86_64 PathFindOnPathA(str ptr)
614 stdcall -arch=x86_64 PathFindOnPathW(wstr ptr)
615 stdcall -arch=x86_64 PathFindSuffixArrayA(str ptr long)
616 stdcall -arch=x86_64 PathFindSuffixArrayW(wstr ptr long)
617 stdcall -arch=x86_64 PathGetArgsA(str)
618 stdcall -arch=x86_64 PathGetArgsW(wstr)
619 stdcall -arch=x86_64 PathGetCharTypeA(long)
620 stdcall -arch=x86_64 PathGetCharTypeW(long)
621 stdcall -arch=x86_64 PathGetDriveNumberA(str)
622 stdcall -arch=x86_64 PathGetDriveNumberW(wstr)
623 stdcall -arch=x86_64 PathIsContentTypeA(str str)
624 stdcall -arch=x86_64 PathIsContentTypeW(wstr wstr)
625 stdcall -arch=x86_64 PathIsDirectoryA(str)
626 stdcall -arch=x86_64 PathIsDirectoryEmptyA(str)
627 stdcall -arch=x86_64 PathIsDirectoryEmptyW(wstr)
628 stdcall -arch=x86_64 PathIsDirectoryW(wstr)
629 stdcall -arch=x86_64 PathIsFileSpecA(str)
630 stdcall -arch=x86_64 PathIsFileSpecW(wstr)
631 stdcall -arch=x86_64 PathIsLFNFileSpecA(str)
632 stdcall -arch=x86_64 PathIsLFNFileSpecW(wstr)
633 stdcall -arch=x86_64 PathIsNetworkPathA(str)
634 stdcall -arch=x86_64 PathIsNetworkPathW(wstr)
635 stdcall -arch=x86_64 PathIsPrefixA(str str)
636 stdcall -arch=x86_64 PathIsPrefixW(wstr wstr)
637 stdcall -arch=x86_64 PathIsRelativeA(str)
638 stdcall -arch=x86_64 PathIsRelativeW(wstr)
639 stdcall -arch=x86_64 PathIsRootA(str)
640 stdcall -arch=x86_64 PathIsRootW(wstr)
641 stdcall -arch=x86_64 PathIsSameRootA(str str)
642 stdcall -arch=x86_64 PathIsSameRootW(wstr wstr)
643 stdcall -arch=x86_64 PathIsSystemFolderA(str long)
644 stdcall -arch=x86_64 PathIsSystemFolderW(wstr long)
645 stdcall -arch=x86_64 PathIsUNCA(str)
646 stdcall -arch=x86_64 PathIsUNCServerA(str)
647 stdcall -arch=x86_64 PathIsUNCServerShareA(str)
648 stdcall -arch=x86_64 PathIsUNCServerShareW(wstr)
649 stdcall -arch=x86_64 PathIsUNCServerW(wstr)
650 stdcall -arch=x86_64 PathIsUNCW(wstr)
651 stdcall -arch=x86_64 PathIsURLA(str)
652 stdcall -arch=x86_64 PathIsURLW(wstr)
653 stdcall -arch=x86_64 PathMakePrettyA(str)
654 stdcall -arch=x86_64 PathMakePrettyW(wstr)
655 stdcall -arch=x86_64 PathMakeSystemFolderA(str)
656 stdcall -arch=x86_64 PathMakeSystemFolderW(wstr)
657 stdcall -arch=x86_64 PathMatchSpecA(str str)
658 stdcall -arch=x86_64 PathMatchSpecW(wstr wstr)
659 stdcall -arch=x86_64 PathParseIconLocationA(str)
660 stdcall -arch=x86_64 PathParseIconLocationW(wstr)
661 stdcall -arch=x86_64 PathQuoteSpacesA(str)
662 stdcall -arch=x86_64 PathQuoteSpacesW(wstr)
663 stdcall -arch=x86_64 PathRelativePathToA(ptr str long str long)
664 stdcall -arch=x86_64 PathRelativePathToW(ptr wstr long wstr long)
665 stdcall -arch=x86_64 PathRemoveArgsA(str)
666 stdcall -arch=x86_64 PathRemoveArgsW(wstr)
667 stdcall -arch=x86_64 PathRemoveBackslashA(str)
668 stdcall -arch=x86_64 PathRemoveBackslashW(wstr)
669 stdcall -arch=x86_64 PathRemoveBlanksA(str)
670 stdcall -arch=x86_64 PathRemoveBlanksW(wstr)
671 stdcall -arch=x86_64 PathRemoveExtensionA(str)
672 stdcall -arch=x86_64 PathRemoveExtensionW(wstr)
673 stdcall -arch=x86_64 PathRemoveFileSpecA(str)
674 stdcall -arch=x86_64 PathRemoveFileSpecW(wstr)
675 stdcall -arch=x86_64 PathRenameExtensionA(str str)
676 stdcall -arch=x86_64 PathRenameExtensionW(wstr wstr)
677 stdcall -arch=x86_64 PathSearchAndQualifyA(str ptr long)
678 stdcall -arch=x86_64 PathSearchAndQualifyW(wstr ptr long)
679 stdcall -arch=x86_64 PathSetDlgItemPathA(long long ptr)
680 stdcall -arch=x86_64 PathSetDlgItemPathW(long long ptr)
681 stdcall -arch=x86_64 PathSkipRootA(str)
682 stdcall -arch=x86_64 PathSkipRootW(wstr)
683 stdcall -arch=x86_64 PathStripPathA(str)
684 stdcall -arch=x86_64 PathStripPathW(wstr)
685 stdcall -arch=x86_64 PathStripToRootA(str)
686 stdcall -arch=x86_64 PathStripToRootW(wstr)
687 stdcall -arch=x86_64 PathUnExpandEnvStringsA(str ptr long)
688 stdcall -arch=x86_64 PathUnExpandEnvStringsW(wstr ptr long)
689 stdcall -arch=x86_64 PathUndecorateA(str)
690 stdcall -arch=x86_64 PathUndecorateW(wstr)
691 stdcall -arch=x86_64 PathUnmakeSystemFolderA(str)
692 stdcall -arch=x86_64 PathUnmakeSystemFolderW(wstr)
693 stdcall -arch=x86_64 PathUnquoteSpacesA(str)
694 stdcall -arch=x86_64 PathUnquoteSpacesW(wstr)
695 stdcall -arch=x86_64 SHAutoComplete(ptr long)
696 stdcall -arch=x86_64 SHCopyKeyA(long str long long)
697 stdcall -arch=x86_64 SHCopyKeyW(long wstr long long)
698 stdcall -arch=x86_64 SHCreateShellPalette(long)
699 stdcall -arch=x86_64 SHCreateStreamOnFileA(str long ptr)
700 stdcall -arch=x86_64 SHCreateStreamOnFileEx(wstr long long long ptr ptr)
701 stdcall -arch=x86_64 SHCreateStreamOnFileW(wstr long ptr)
702 stdcall -arch=x86_64 SHCreateStreamWrapper(ptr ptr long ptr)
703 stdcall -arch=x86_64 SHCreateThreadRef(ptr ptr)
704 stdcall -arch=x86_64 SHDeleteEmptyKeyA(long ptr)
705 stdcall -arch=x86_64 SHDeleteEmptyKeyW(long ptr)
706 stdcall -arch=x86_64 SHDeleteKeyA(long str)
707 stdcall -arch=x86_64 SHDeleteKeyW(long wstr)
708 stdcall -arch=x86_64 SHDeleteOrphanKeyA(long str)
709 stdcall -arch=x86_64 SHDeleteOrphanKeyW(long wstr)
710 stdcall -arch=x86_64 SHDeleteValueA(long str str)
711 stdcall -arch=x86_64 SHDeleteValueW(long wstr wstr)
712 stdcall -arch=x86_64 SHEnumKeyExA(long long str ptr)
713 stdcall -arch=x86_64 SHEnumKeyExW(long long wstr ptr)
714 stdcall -arch=x86_64 SHEnumValueA(long long str ptr ptr ptr ptr)
715 stdcall -arch=x86_64 SHEnumValueW(long long wstr ptr ptr ptr ptr)
716 stdcall -arch=x86_64 SHGetInverseCMAP(ptr long)
717 stdcall -arch=x86_64 SHGetThreadRef(ptr)
718 stdcall -arch=x86_64 SHGetValueA(long str str ptr ptr ptr)
719 stdcall -arch=x86_64 SHGetValueW(long wstr wstr ptr ptr ptr)
720 stdcall -arch=x86_64 SHIsLowMemoryMachine(long)
721 stdcall -arch=x86_64 SHOpenRegStream2A(long str str long)
722 stdcall -arch=x86_64 SHOpenRegStream2W(long wstr wstr long)
723 stdcall -arch=x86_64 SHOpenRegStreamA(long str str long)
724 stdcall -arch=x86_64 SHOpenRegStreamW(long wstr wstr long)
725 stdcall -arch=x86_64 SHQueryInfoKeyA(long ptr ptr ptr ptr)
726 stdcall -arch=x86_64 SHQueryInfoKeyW(long ptr ptr ptr ptr)
727 stdcall -arch=x86_64 SHQueryValueExA(long str ptr ptr ptr ptr)
728 stdcall -arch=x86_64 SHQueryValueExW(long wstr ptr ptr ptr ptr)
729 stdcall -arch=x86_64 SHRegCloseUSKey(ptr)
730 stdcall -arch=x86_64 SHRegCreateUSKeyA(str long long ptr long)
731 stdcall -arch=x86_64 SHRegCreateUSKeyW(wstr long long ptr long)
732 stdcall -arch=x86_64 SHRegDeleteEmptyUSKeyA(long str long)
733 stdcall -arch=x86_64 SHRegDeleteEmptyUSKeyW(long wstr long)
734 stdcall -arch=x86_64 SHRegDeleteUSValueA(long str long)
735 stdcall -arch=x86_64 SHRegDeleteUSValueW(long wstr long)
736 stdcall -arch=x86_64 SHRegDuplicateHKey(long)
737 stdcall -arch=x86_64 SHRegEnumUSKeyA(long long str ptr long)
738 stdcall -arch=x86_64 SHRegEnumUSKeyW(long long wstr ptr long)
739 stdcall -arch=x86_64 SHRegEnumUSValueA(long long ptr ptr ptr ptr ptr long)
740 stdcall -arch=x86_64 SHRegEnumUSValueW(long long ptr ptr ptr ptr ptr long)
741 stdcall -arch=x86_64 SHRegGetBoolUSValueA(str str long long)
742 stdcall -arch=x86_64 SHRegGetBoolUSValueW(wstr wstr long long)
743 stdcall -arch=x86_64 SHRegGetPathA(long str str ptr long)
744 stdcall -arch=x86_64 SHRegGetPathW(long wstr wstr ptr long)
745 stdcall -arch=x86_64 SHRegGetUSValueA(str str ptr ptr ptr long ptr long)
746 stdcall -arch=x86_64 SHRegGetUSValueW(wstr wstr ptr ptr ptr long ptr long)
747 stdcall -arch=x86_64 SHRegGetValueA(long str str long ptr ptr ptr) advapi32.RegGetValueA
748 stdcall -arch=x86_64 SHRegGetValueW(long wstr wstr long ptr ptr ptr) advapi32.RegGetValueW
749 stdcall -arch=x86_64 SHRegOpenUSKeyA(str long long long long)
750 stdcall -arch=x86_64 SHRegOpenUSKeyW(wstr long long long long)
751 stdcall -arch=x86_64 SHRegQueryInfoUSKeyA(long ptr ptr ptr ptr long)
752 stdcall -arch=x86_64 SHRegQueryInfoUSKeyW(long ptr ptr ptr ptr long)
753 stdcall -arch=x86_64 SHRegQueryUSValueA(long str ptr ptr ptr long ptr long)
754 stdcall -arch=x86_64 SHRegQueryUSValueW(long wstr ptr ptr ptr long ptr long)
755 stdcall -arch=x86_64 SHRegSetPathA(long str str str long)
756 stdcall -arch=x86_64 SHRegSetPathW(long wstr wstr wstr long)
757 stdcall -arch=x86_64 SHRegSetUSValueA(str str long ptr long long)
758 stdcall -arch=x86_64 SHRegSetUSValueW(wstr wstr long ptr long long)
759 stdcall -arch=x86_64 SHRegWriteUSValueA(long str long ptr long long)
760 stdcall -arch=x86_64 SHRegWriteUSValueW(long wstr long ptr long long)
761 stdcall -arch=x86_64 SHRegisterValidateTemplate(wstr long)
762 stdcall -arch=x86_64 SHReleaseThreadRef()
763 stdcall -arch=x86_64 SHSetThreadRef(ptr)
764 stdcall -arch=x86_64 SHSetValueA(long str str long ptr long)
765 stdcall -arch=x86_64 SHSetValueW(long wstr wstr long ptr long)
766 stdcall -arch=x86_64 SHSkipJunction(ptr ptr)
767 stdcall -arch=x86_64 SHStrDupA(str ptr)
768 stdcall -arch=x86_64 SHStrDupW(wstr ptr)
769 stdcall -arch=x86_64 StrCSpnA(str str)
770 stdcall -arch=x86_64 StrCSpnIA(str str)
771 stdcall -arch=x86_64 StrCSpnIW(wstr wstr)
772 stdcall -arch=x86_64 StrCSpnW(wstr wstr)
773 stdcall -arch=x86_64 StrCatBuffA(str str long)
774 stdcall -arch=x86_64 StrCatBuffW(wstr wstr long)
775 stdcall -arch=x86_64 StrCatChainW(wstr long long wstr)
776 stdcall -arch=x86_64 StrCatW(ptr wstr)
777 stdcall -arch=x86_64 StrChrA(str long)
778 stdcall -arch=x86_64 StrChrIA(str long)
779 stdcall -arch=x86_64 StrChrIW(wstr long)
780 stdcall -arch=x86_64 StrChrNIW(wstr wstr long)
781 stdcall -arch=x86_64 StrChrNW(wstr long long)
782 stdcall -arch=x86_64 StrChrW(wstr long)
783 stdcall -arch=x86_64 StrCmpIW(wstr wstr)
784 stdcall -arch=x86_64 StrCmpLogicalW(wstr wstr)
785 stdcall -arch=x86_64 StrCmpNA(str str long)
786 stdcall -arch=x86_64 StrCmpNIA(str str long)
787 stdcall -arch=x86_64 StrCmpNIW(wstr wstr long)
788 stdcall -arch=x86_64 StrCmpNW(wstr wstr long)
789 stdcall -arch=x86_64 StrCmpW(wstr wstr)
790 stdcall -arch=x86_64 StrCpyNW(ptr wstr long)
791 stdcall -arch=x86_64 StrCpyW(ptr wstr)
792 stdcall -arch=x86_64 StrDupA(str)
793 stdcall -arch=x86_64 StrDupW(wstr)
794 stdcall -arch=x86_64 StrFormatByteSize64A(int64 ptr long)
795 stdcall -arch=x86_64 StrFormatByteSizeA(long ptr long)
796 stdcall -arch=x86_64 StrFormatByteSizeW(int64 ptr long)
797 stdcall -arch=x86_64 StrFormatKBSizeA(int64 str long)
798 stdcall -arch=x86_64 StrFormatKBSizeW(int64 wstr long)
799 stdcall -arch=x86_64 StrFromTimeIntervalA(ptr long long long)
800 stdcall -arch=x86_64 StrFromTimeIntervalW(ptr long long long)
801 stdcall -arch=x86_64 StrIsIntlEqualA(long str str long)
802 stdcall -arch=x86_64 StrIsIntlEqualW(long wstr wstr long)
803 stdcall -arch=x86_64 StrNCatA(str str long)
804 stdcall -arch=x86_64 StrNCatW(wstr wstr long)
805 stdcall -arch=x86_64 StrPBrkA(str str)
806 stdcall -arch=x86_64 StrPBrkW(wstr wstr)
807 stdcall -arch=x86_64 StrRChrA(str str long)
808 stdcall -arch=x86_64 StrRChrIA(str str long)
809 stdcall -arch=x86_64 StrRChrIW(wstr wstr long)
810 stdcall -arch=x86_64 StrRChrW(wstr wstr long)
811 stdcall -arch=x86_64 StrRStrIA(str str str)
812 stdcall -arch=x86_64 StrRStrIW(wstr wstr wstr)
813 stdcall -arch=x86_64 StrRetToBSTR(ptr ptr ptr)
814 stdcall -arch=x86_64 StrRetToBufA(ptr ptr ptr long)
815 stdcall -arch=x86_64 StrRetToBufW(ptr ptr ptr long)
816 stdcall -arch=x86_64 StrRetToStrA(ptr ptr ptr)
817 stdcall -arch=x86_64 StrRetToStrW(ptr ptr ptr)
818 stdcall -arch=x86_64 StrSpnA(str str)
819 stdcall -arch=x86_64 StrSpnW(wstr wstr)
820 stdcall -arch=x86_64 StrStrA(str str)
821 stdcall -arch=x86_64 StrStrIA(str str)
822 stdcall -arch=x86_64 StrStrIW(wstr wstr)
823 stdcall -arch=x86_64 StrStrNIW(wstr wstr long)
824 stdcall -arch=x86_64 StrStrNW(wstr wstr long)
825 stdcall -arch=x86_64 StrStrW(wstr wstr)
826 stdcall -arch=x86_64 StrToInt64ExA(str long ptr)
827 stdcall -arch=x86_64 StrToInt64ExW(wstr long ptr)
828 stdcall -arch=x86_64 StrToIntA(str)
829 stdcall -arch=x86_64 StrToIntExA(str long ptr)
830 stdcall -arch=x86_64 StrToIntExW(wstr long ptr)
831 stdcall -arch=x86_64 StrToIntW(wstr)
832 stdcall -arch=x86_64 StrTrimA(str str)
833 stdcall -arch=x86_64 StrTrimW(wstr wstr)
834 stdcall -arch=x86_64 UrlApplySchemeA(str ptr ptr long)
835 stdcall -arch=x86_64 UrlApplySchemeW(wstr ptr ptr long)
836 stdcall -arch=x86_64 UrlCanonicalizeA(str ptr ptr long)
837 stdcall -arch=x86_64 UrlCanonicalizeW(wstr ptr ptr long)
838 stdcall -arch=x86_64 UrlCombineA(str str ptr ptr long)
839 stdcall -arch=x86_64 UrlCombineW(wstr wstr ptr ptr long)
840 stdcall -arch=x86_64 UrlCompareA(str str long)
841 stdcall -arch=x86_64 UrlCompareW(wstr wstr long)
842 stdcall -arch=x86_64 UrlCreateFromPathA(str ptr ptr long)
843 stdcall -arch=x86_64 UrlCreateFromPathW(wstr ptr ptr long)
844 stdcall -arch=x86_64 UrlEscapeA(str ptr ptr long)
845 stdcall -arch=x86_64 UrlEscapeW(wstr ptr ptr long)
846 stdcall -arch=x86_64 UrlGetLocationA(str)
847 stdcall -arch=x86_64 UrlGetLocationW(wstr)
848 stdcall -arch=x86_64 UrlGetPartA(str ptr ptr long long)
849 stdcall -arch=x86_64 UrlGetPartW(wstr ptr ptr long long)
850 stdcall -arch=x86_64 UrlHashA(str ptr long)
851 stdcall -arch=x86_64 UrlHashW(wstr ptr long)
852 stdcall -arch=x86_64 UrlIsA(str long)
853 stdcall -arch=x86_64 UrlIsNoHistoryA(str)
854 stdcall -arch=x86_64 UrlIsNoHistoryW(wstr)
855 stdcall -arch=x86_64 UrlIsOpaqueA(str)
856 stdcall -arch=x86_64 UrlIsOpaqueW(wstr)
857 stdcall -arch=x86_64 UrlIsW(wstr long)
858 stdcall -arch=x86_64 UrlUnescapeA(str ptr ptr long)
859 stdcall -arch=x86_64 UrlUnescapeW(wstr ptr ptr long)
860 varargs -arch=x86_64 wnsprintfA(ptr long str)
861 varargs -arch=x86_64 wnsprintfW(ptr long wstr)
862 stdcall -arch=x86_64 wvnsprintfA(ptr long str ptr)
863 stdcall -arch=x86_64 wvnsprintfW(ptr long wstr ptr)

@ stdcall ShellMessageBoxA(ptr str str long) user32.MessageBoxA
@ stdcall ShellMessageBoxW(ptr str str long) user32.MessageBoxW

#Windows Vista Functions
@ stdcall PathMatchSpecExA(str str long)
@ stdcall PathMatchSpecExW(wstr wstr long)
@ stdcall PathCreateFromUrlAlloc(wstr wstr long)
@ stdcall StrFormatByteSizeEx(long long long wstr long)
@ stdcall SHAutoCompGetPidl(ptr ptr long ptr)

;@ varargs ShellMessageBoxW(long long wstr wstr long) shell32.ShellMessageBoxW
;@ varargs ShellMessageBoxA(long long str str long) shell32.ShellMessageBoxA