@ stdcall AddUsersToEncryptedFileEx(long long long long)
@ stdcall AuditComputeEffectivePolicyBySid(ptr ptr long ptr)
@ stdcall AuditComputeEffectivePolicyByToken(ptr ptr long ptr)
@ stdcall AuditEnumerateCategories(ptr ptr)
@ stdcall AuditEnumeratePerUserPolicy(ptr)
@ stdcall AuditEnumerateSubCategories(ptr long ptr ptr)
@ stdcall AuditFree(ptr)
@ stdcall AuditLookupCategoryGuidFromCategoryId(ptr ptr)
@ stdcall AuditLookupCategoryIdFromCategoryGuid(ptr ptr)
@ stdcall AuditLookupCategoryNameA(ptr str)
@ stdcall AuditLookupCategoryNameW(ptr wstr)
@ stdcall AuditLookupSubCategoryNameA(ptr str)
@ stdcall AuditLookupSubCategoryNameW(ptr str)
@ stdcall AuditQueryPerUserPolicy(ptr ptr long ptr)
@ stdcall AuditQuerySecurity(long ptr)
@ stdcall AuditQuerySystemPolicy(ptr long ptr)
@ stdcall AuditSetPerUserPolicy(ptr ptr long)
@ stdcall AuditSetSecurity(ptr long)
@ stdcall AuditSetSystemPolicy(ptr long)
@ stdcall CheckAppInitBlockedServiceIdentity(long)
@ stdcall CloseThreadWaitChainSession(ptr)
@ stdcall ControlServiceExA(ptr long long ptr)
@ stdcall ControlServiceExW(ptr long long ptr)
;@ stdcall CreateProcessWithTokenW(ptr long wstr wstr long ptr wstr ptr ptr)
@ stdcall CredBackupCredentials(long ptr ptr long long)
@ stdcall CredEncryptAndMarshalBinaryBlob(long long long)
@ stdcall CredFindBestCredentialA(str long long ptr) 
@ stdcall CredFindBestCredentialW(wstr long long ptr)
@ stdcall CredIsProtectedA(str ptr)
@ stdcall CredIsProtectedW(wstr ptr)
@ stdcall CredpConvertOneCredentialSize(long long)
@ stdcall CredpEncodeSecret(long ptr long long long)
@ stdcall CredProfileUnloaded()
@ stdcall CredProtectA(long str long str long ptr)
@ stdcall CredProtectW(long wstr long wstr long ptr)
@ stdcall CredReadByTokenHandle(long ptr long long long)
@ stdcall CredRestoreCredentials(ptr ptr long long)
@ stdcall CredUnprotectA(long str long str ptr)
@ stdcall CredUnprotectW(long wstr long wstr ptr)
@ stdcall ElfReportEventAndSourceW(ptr long wstr long long long ptr wstr long long wstr ptr long ptr ptr)
@ stdcall EnableTraceEx(ptr ptr int64 long long long long long long long ptr) 
@ stdcall EnumerateTraceGuidsEx(long ptr long ptr long ptr)
@ stdcall EventAccessControl(ptr long ptr long long)
@ stdcall EventAccessQuery(ptr ptr ptr)
@ stdcall EventAccessRemove(ptr)
@ stdcall FlushEfsCache(ptr)
@ stdcall FreeEncryptedFileMetadata(ptr)
@ stdcall GetEncryptedFileMetadata(wstr ptr ptr)
@ stdcall GetThreadWaitChain(ptr long long long ptr ptr ptr)
@ stdcall I_QueryTagInformation(long long long)
@ stdcall I_ScQueryServiceConfig(long long long)
@ stdcall I_ScSendPnPMessage(long long long long long)
@ stdcall I_ScValidatePnPService(long long long)
@ stdcall InitiateShutdownA(str str long long long)
@ stdcall InitiateShutdownW(wstr wstr long long long)
@ stdcall IsValidRelativeSecurityDescriptor(ptr long long)
@ stdcall LogonUserExExW(str str str long long ptr ptr ptr ptr ptr ptr)
@ stdcall LsaManageSidNameMapping(long ptr ptr)
@ stdcall NotifyServiceStatusChange(ptr long ptr) 
@ stdcall NotifyServiceStatusChangeA(ptr long ptr) NotifyServiceStatusChange
@ stdcall NotifyServiceStatusChangeW(ptr long ptr) NotifyServiceStatusChange
@ stdcall PerfAddCounters(ptr ptr long)
@ stdcall PerfCloseQueryHandle(ptr)
@ stdcall PerfCreateInstance(ptr ptr wstr long)
@ stdcall PerfDecrementULongCounterValue(ptr ptr long long)
@ stdcall PerfDecrementULongLongCounterValue(ptr ptr long long long)
@ stdcall PerfDeleteCounters(ptr ptr long)
@ stdcall PerfDeleteInstance(ptr ptr)
@ stdcall PerfEnumerateCounterSet(long ptr long long)
@ stdcall PerfEnumerateCounterSetInstances(long ptr ptr long long)
@ stdcall PerfIncrementULongCounterValue(ptr ptr long long)
@ stdcall PerfIncrementULongLongCounterValue(ptr ptr long long long)
@ stdcall PerfQueryInstance(ptr ptr wstr long)
@ stdcall PerfOpenQueryHandle(long ptr)
@ stdcall PerfQueryCounterData(ptr ptr long long)
@ stdcall PerfQueryCounterInfo(ptr ptr long long)
@ stdcall PerfQueryCounterSetRegistrationInfo(long long long long long long long)
@ stdcall PerfSetCounterSetInfo(ptr ptr long)
@ stdcall PerfSetCounterRefValue(ptr ptr long ptr)
@ stdcall PerfSetULongCounterValue(ptr ptr long long)
@ stdcall PerfSetULongLongCounterValue(ptr ptr long long long)
@ stdcall PerfStartProvider(ptr ptr ptr)
@ stdcall PerfStartProviderEx(ptr ptr ptr)
@ stdcall PerfStopProvider(ptr)
@ stdcall QuerySecurityAccessMask(long ptr)
@ stdcall OpenThreadWaitChainSession(long ptr)
;@ stdcall RegConnectRegistryExA(str ptr long ptr)
;@ stdcall RegConnectRegistryExW(wstr ptr long ptr)
;@ stdcall RegCopyTreeA(ptr str ptr)
;@ stdcall RegCopyTreeW(ptr str ptr)
@ stdcall RegCreateKeyExA(ptr str long ptr long long ptr ptr ptr) 
@ stdcall RegCreateKeyExW(ptr wstr long ptr long long ptr ptr ptr) 
@ stdcall RegCreateKeyTransactedA(ptr str long str long long ptr ptr ptr ptr ptr)
@ stdcall RegCreateKeyTransactedW(ptr wstr long wstr long long ptr ptr ptr ptr ptr)
@ stdcall RegDeleteKeyExA(long str long long)
@ stdcall RegDeleteKeyExW(long wstr long long)
@ stdcall RegDeleteKeyTransactedA(ptr str long long ptr ptr)
@ stdcall RegDeleteKeyTransactedW(ptr wstr long long ptr ptr)
;@ stdcall RegDeleteKeyValueA(ptr str str)
@ stdcall RegDeleteKeyValueW(ptr wstr wstr) 
@ stdcall RegDeleteTreeA(long str)
@ stdcall RegDeleteTreeW(long wstr)
@ stdcall RegDisablePredefinedCacheEx()
@ stdcall RegDisableReflectionKey(ptr)
@ stdcall RegEnableReflectionKey(ptr)
@ stdcall RegGetValueA(long str str long ptr ptr ptr)
@ stdcall RegGetValueW(long wstr wstr long ptr ptr ptr)
;@ stdcall RegisterServiceCtrlHandlerExA(str ptr ptr)
;@ stdcall RegisterServiceCtrlHandlerExW(wstr ptr ptr)
@ stdcall RegisterWaitChainCOMCallback(ptr ptr)
@ stdcall RegLoadAppKeyA(str ptr long long long)
@ stdcall RegLoadAppKeyW(wstr ptr long long long)
@ stdcall RegLoadKeyA(ptr str str)
@ stdcall RegLoadKeyW(ptr wstr wstr)
;@ stdcall RegLoadMUIStringA(ptr str str long ptr long str)
;@ stdcall RegLoadMUIStringW(ptr str str long ptr long str)
@ stdcall RegOpenKeyTransactedA(ptr str long long ptr ptr ptr)
@ stdcall RegOpenKeyTransactedW(ptr wstr long long ptr ptr ptr)
@ stdcall RegQueryReflectionKey(ptr ptr)
@ stdcall RegRenameKey(ptr wstr wstr)
;@ stdcall RegSetKeyValueA(ptr str str long ptr long)
;@ stdcall RegSetKeyValueW(ptr wstr wstr long ptr long)
@ stdcall SetEncryptedFileMetadata(wstr ptr ptr ptr long ptr)
@ stdcall SetSecurityAccessMask(long ptr)
@ stdcall SetUserFileEncryptionKeyEx(ptr long long ptr)
@ stdcall TreeSetNamedSecurityInfoA(str long long ptr ptr ptr ptr long)
@ stdcall TreeSetNamedSecurityInfoW(wstr long long ptr ptr ptr ptr long)
@ stdcall UsePinForEncryptedFilesA(long long long)
@ stdcall UsePinForEncryptedFilesW(long long long)
@ stdcall RegOpenKeyExA(long str long long ptr)
@ stdcall RegOpenKeyExW(long wstr long long ptr)
@ stdcall RegQueryValueExA(long str ptr ptr ptr ptr)
@ stdcall RegQueryValueExW(long wstr ptr ptr ptr ptr)
101 stdcall CreateRestrictedToken(long long long ptr long ptr long ptr ptr)
582 stdcall SetThreadToken(ptr ptr)
284 stdcall GetTokenInformation(long long ptr long ptr)