@ stdcall A_SHAFinal(ptr ptr)
@ stdcall A_SHAInit(ptr)
@ stdcall A_SHAUpdate(ptr ptr long)
@ stdcall AbortSystemShutdownA(ptr)
@ stdcall AbortSystemShutdownW(ptr)
@ stdcall AccessCheck(ptr long long ptr ptr ptr ptr ptr)
@ stdcall AccessCheckAndAuditAlarmA(str ptr str str ptr long ptr long ptr ptr ptr)
@ stdcall AccessCheckAndAuditAlarmW(wstr ptr wstr wstr ptr long ptr long ptr ptr ptr)
@ stdcall AccessCheckByType(ptr ptr long long ptr long ptr ptr ptr ptr ptr)
@ stdcall AccessCheckByTypeAndAuditAlarmA(str ptr str str ptr ptr long long long ptr long ptr long ptr ptr ptr)
@ stdcall AccessCheckByTypeAndAuditAlarmW(wstr ptr wstr wstr ptr ptr long long long ptr long ptr long ptr ptr ptr)
@ stdcall AccessCheckByTypeResultList(ptr ptr ptr long ptr long ptr ptr ptr ptr ptr)
@ stdcall AccessCheckByTypeResultListAndAuditAlarmA(str ptr str str ptr long long long long ptr long ptr long ptr ptr ptr)
@ stdcall AccessCheckByTypeResultListAndAuditAlarmByHandleA(str ptr ptr str str ptr long long long long ptr long ptr long ptr ptr ptr)
@ stdcall AccessCheckByTypeResultListAndAuditAlarmByHandleW(wstr ptr ptr wstr wstr ptr long long long long ptr long ptr long ptr ptr ptr)
@ stdcall AccessCheckByTypeResultListAndAuditAlarmW(wstr ptr wstr wstr ptr long long long long ptr long ptr long ptr ptr ptr)
@ stdcall AddAccessAllowedAce(ptr long long ptr)
@ stdcall AddAccessAllowedAceEx(ptr long long long ptr)
@ stdcall AddAccessAllowedObjectAce(ptr long long long ptr ptr ptr)
@ stdcall AddAccessDeniedAce(ptr long long ptr)
@ stdcall AddAccessDeniedAceEx(ptr long long long ptr)
@ stdcall AddAccessDeniedObjectAce(ptr long long long ptr ptr ptr)
@ stdcall AddAce(ptr long long ptr long)
@ stdcall AddAuditAccessAce(ptr long long ptr long long)
@ stdcall AddAuditAccessAceEx(ptr long long long ptr long long)
@ stdcall AddAuditAccessObjectAce(ptr long long long ptr ptr ptr long long)
@ stdcall AddUsersToEncryptedFile(wstr ptr)
@ stdcall AdjustTokenGroups(long long ptr long ptr ptr)
@ stdcall AdjustTokenPrivileges(long long ptr long ptr ptr)
@ stdcall AllocateAndInitializeSid(ptr long long long long long long long long long ptr)
@ stdcall AllocateLocallyUniqueId(ptr)
@ stdcall AreAllAccessesGranted(long long)
@ stdcall AreAnyAccessesGranted(long long)
@ stdcall BackupEventLogA(long str)
@ stdcall BackupEventLogW(long wstr)
@ stdcall BuildExplicitAccessWithNameA(ptr str long long long)
@ stdcall BuildExplicitAccessWithNameW(ptr wstr long long long)
@ stdcall BuildImpersonateExplicitAccessWithNameA(ptr str ptr long long long)
@ stdcall BuildImpersonateExplicitAccessWithNameW(ptr wstr ptr long long long)
@ stdcall BuildImpersonateTrusteeA(ptr ptr)
@ stdcall BuildImpersonateTrusteeW(ptr ptr)
@ stdcall BuildSecurityDescriptorA(ptr ptr long ptr long ptr ptr ptr ptr)
@ stdcall BuildSecurityDescriptorW(ptr ptr long ptr long ptr ptr ptr ptr)
@ stdcall BuildTrusteeWithNameA(ptr str)
@ stdcall BuildTrusteeWithNameW(ptr wstr)
@ stdcall BuildTrusteeWithObjectsAndNameA(ptr ptr long str str str)
@ stdcall BuildTrusteeWithObjectsAndNameW(ptr ptr long wstr wstr wstr)
@ stdcall BuildTrusteeWithObjectsAndSidA(ptr ptr ptr ptr ptr)
@ stdcall BuildTrusteeWithObjectsAndSidW(ptr ptr ptr ptr ptr)
@ stdcall BuildTrusteeWithSidA(ptr ptr)
@ stdcall BuildTrusteeWithSidW(ptr ptr)
@ stdcall CancelOverlappedAccess(ptr)
@ stdcall ChangeServiceConfig2A(long long ptr)
@ stdcall ChangeServiceConfig2W(long long ptr)
@ stdcall ChangeServiceConfigA(long long long long wstr str ptr str str str str)
@ stdcall ChangeServiceConfigW(long long long long wstr wstr ptr wstr wstr wstr wstr)
@ stdcall CheckTokenMembership(long ptr ptr)
@ stdcall ClearEventLogA(long str)
@ stdcall ClearEventLogW(long wstr)
@ stdcall CloseCodeAuthzLevel(ptr)
@ stdcall CloseEncryptedFileRaw(ptr)
@ stdcall CloseEventLog(long)
@ stdcall CloseServiceHandle(long)
@ stdcall CloseTrace(long long) 
@ stdcall CommandLineFromMsiDescriptor(wstr ptr ptr)
@ stdcall ComputeAccessTokenFromCodeAuthzLevel(ptr long)
@ stdcall ControlService(long long ptr)
@ stdcall ControlTraceA(double str ptr long)
@ stdcall ControlTraceW(double wstr ptr long)
@ stdcall ConvertAccessToSecurityDescriptorA(ptr ptr str str ptr)
@ stdcall ConvertAccessToSecurityDescriptorW(ptr ptr wstr wstr ptr)
@ stdcall ConvertSDToStringSDRootDomainA(long ptr long long str long)
@ stdcall ConvertSDToStringSDRootDomainW(long ptr long long wstr long)
@ stdcall ConvertSecurityDescriptorToAccessA(ptr long ptr ptr ptr str str)
@ stdcall ConvertSecurityDescriptorToAccessNamedA(str long ptr ptr ptr str str)
@ stdcall ConvertSecurityDescriptorToAccessNamedW(wstr long ptr ptr ptr wstr wstr)
@ stdcall ConvertSecurityDescriptorToAccessW(ptr long ptr ptr ptr wstr wstr)
@ stdcall ConvertSecurityDescriptorToStringSecurityDescriptorA(ptr long long ptr ptr)
@ stdcall ConvertSecurityDescriptorToStringSecurityDescriptorW(ptr long long ptr ptr)
@ stdcall ConvertSidToStringSidA(ptr ptr)
@ stdcall ConvertSidToStringSidW(ptr ptr)
@ stdcall ConvertStringSDToSDDomainA(ptr long str long long long) ;need implement
@ stdcall ConvertStringSDToSDDomainW(ptr long wstr long long long) ;need implement
@ stdcall ConvertStringSDToSDRootDomainA(long long long long long)
@ stdcall ConvertStringSDToSDRootDomainW(long long long long long)
@ stdcall ConvertStringSecurityDescriptorToSecurityDescriptorA(str long ptr ptr)
@ stdcall ConvertStringSecurityDescriptorToSecurityDescriptorW(wstr long ptr ptr)
@ stdcall ConvertStringSidToSidA(ptr ptr)
@ stdcall ConvertStringSidToSidW(ptr ptr)
@ stdcall ConvertToAutoInheritPrivateObjectSecurity(ptr ptr ptr ptr long ptr)
@ stdcall CopySid(long ptr ptr)
@ stdcall CreateCodeAuthzLevel()
@ stdcall CreatePrivateObjectSecurity(ptr ptr ptr long long ptr)
@ stdcall CreatePrivateObjectSecurityEx(ptr ptr ptr ptr long long ptr ptr)
@ stdcall CreatePrivateObjectSecurityWithMultipleInheritance(ptr ptr ptr ptr long long long ptr ptr)
@ stdcall CreateProcessAsUserA(long str str ptr ptr long long ptr str ptr ptr)
@ stdcall CreateProcessAsUserW(long str str ptr ptr long long ptr str ptr ptr)
@ stdcall CreateProcessWithLogonW(wstr wstr wstr long wstr wstr long ptr wstr ptr ptr)
@ stdcall CreateRestrictedToken(long long long ptr long ptr long ptr ptr)
@ stdcall CreateServiceA(long str str long long long long str str ptr str str str)
@ stdcall CreateServiceW(long wstr wstr long long long long wstr wstr ptr wstr wstr wstr)
@ stdcall CreateTraceInstanceId(ptr ptr)
@ stdcall CreateWellKnownSid(long ptr ptr ptr)
@ stdcall CredDeleteA(str long long)
@ stdcall CredDeleteW(wstr long long)
@ stdcall CredEnumerateA(str long ptr ptr)
@ stdcall CredEnumerateW(wstr long ptr ptr)
@ stdcall CredFree(ptr)
@ stdcall CredGetSessionTypes(long ptr)
@ stdcall CredGetTargetInfoA(str long ptr)
@ stdcall CredGetTargetInfoW(wstr long ptr)
@ stdcall CredIsMarshaledCredentialA(str)
@ stdcall CredIsMarshaledCredentialW(wstr)
@ stdcall CredMarshalCredentialA(long ptr str)
@ stdcall CredMarshalCredentialW(long ptr wstr)
@ stdcall CredProfileLoaded()
@ stdcall CredReadA(str long long ptr)
@ stdcall CredReadDomainCredentialsA(ptr long ptr ptr)
@ stdcall CredReadDomainCredentialsW(ptr long ptr ptr)
@ stdcall CredReadW(wstr long long ptr)
@ stdcall CredRenameA(str str long long)
@ stdcall CredRenameW(wstr wstr long long)
@ stdcall CredUnmarshalCredentialA(str ptr ptr)
@ stdcall CredUnmarshalCredentialW(wstr ptr ptr)
@ stdcall CredWriteA(ptr long)
@ stdcall CredWriteDomainCredentialsA(ptr ptr long)
@ stdcall CredWriteDomainCredentialsW(ptr ptr long)
@ stdcall CredWriteW(ptr long)
@ stdcall CredpConvertCredential(long long long ptr)
@ stdcall CredpConvertTargetInfo(long long ptr long) ;need implement
@ stdcall CredpDecodeCredential(ptr) ;need implement
@ stdcall CredpEncodeCredential(ptr) ;need implement
@ stdcall CryptAcquireContextA(ptr str str long long)
@ stdcall CryptAcquireContextW(ptr wstr wstr long long)
@ stdcall CryptContextAddRef(long ptr long)
@ stdcall CryptCreateHash(long long long long ptr)
@ stdcall CryptDecrypt(long long long long ptr ptr)
@ stdcall CryptDeriveKey(long long long long ptr)
@ stdcall CryptDestroyHash(long)
@ stdcall CryptDestroyKey(long)
@ stdcall CryptDuplicateHash(long ptr long ptr)
@ stdcall CryptDuplicateKey(long ptr long ptr)
@ stdcall CryptEncrypt(long long long long ptr ptr long)
@ stdcall CryptEnumProviderTypesA(long ptr long ptr ptr ptr)
@ stdcall CryptEnumProviderTypesW(long ptr long ptr ptr ptr)
@ stdcall CryptEnumProvidersA(long ptr long ptr ptr ptr)
@ stdcall CryptEnumProvidersW(long ptr long ptr ptr ptr)
@ stdcall CryptExportKey(long long long long ptr ptr)
@ stdcall CryptGenKey(long long long ptr)
@ stdcall CryptGenRandom(long long ptr)
@ stdcall CryptGetDefaultProviderA(long ptr long ptr ptr)
@ stdcall CryptGetDefaultProviderW(long ptr long ptr ptr)
@ stdcall CryptGetHashParam(long long ptr ptr long)
@ stdcall CryptGetKeyParam(long long ptr ptr long)
@ stdcall CryptGetProvParam(long long ptr ptr long)
@ stdcall CryptGetUserKey(long long ptr)
@ stdcall CryptHashData(long ptr long long)
@ stdcall CryptHashSessionKey(long long long)
@ stdcall CryptImportKey(long ptr long long long ptr)
@ stdcall CryptReleaseContext(long long)
@ stdcall CryptSetHashParam(long long ptr long)
@ stdcall CryptSetKeyParam(long long ptr long)
@ stdcall CryptSetProvParam(long long ptr long)
@ stdcall CryptSetProviderA(str long)
@ stdcall CryptSetProviderExA(str long ptr long)
@ stdcall CryptSetProviderExW(wstr long ptr long)
@ stdcall CryptSetProviderW(wstr long)
@ stdcall CryptSignHashA(long long ptr long ptr ptr)
@ stdcall CryptSignHashW(long long ptr long ptr ptr)
@ stdcall CryptVerifySignatureA(long ptr long long ptr long)
@ stdcall CryptVerifySignatureW(long ptr long long ptr long)
@ stdcall DecryptFileA(str long)
@ stdcall DecryptFileW(wstr long)
@ stdcall DeleteAce(ptr long)
@ stdcall DeleteService(long)
@ stdcall DeregisterEventSource(long)
@ stdcall DestroyPrivateObjectSecurity(ptr)
@ stdcall DuplicateEncryptionInfoFile(wstr wstr long long ptr)
@ stdcall DuplicateToken(long long ptr)
@ stdcall DuplicateTokenEx(long long ptr long long ptr)
@ stdcall ElfBackupEventLogFileA(ptr str)
@ stdcall ElfBackupEventLogFileW(ptr wstr)
@ stdcall ElfChangeNotify(ptr ptr)
@ stdcall ElfClearEventLogFileA(ptr str)
@ stdcall ElfClearEventLogFileW(ptr wstr)
@ stdcall ElfCloseEventLog(ptr)
@ stdcall ElfDeregisterEventSource(ptr)
@ stdcall ElfFlushEventLog(ptr)
@ stdcall ElfNumberOfRecords(ptr ptr)
@ stdcall ElfOldestRecord(ptr ptr)
@ stdcall ElfOpenBackupEventLogA(str str ptr)
@ stdcall ElfOpenBackupEventLogW(wstr wstr ptr) 
@ stdcall ElfOpenEventLogA(str str ptr)
@ stdcall ElfOpenEventLogW(wstr wstr ptr) 
@ stdcall ElfReadEventLogA(ptr long long ptr long ptr ptr) 
@ stdcall ElfReadEventLogW(ptr long long ptr long ptr ptr) 
@ stdcall ElfRegisterEventSourceA(str str ptr)
@ stdcall ElfRegisterEventSourceW(wstr wstr ptr)
@ stdcall ElfReportEventA(ptr long long long ptr long long str ptr long ptr ptr)
@ stdcall ElfReportEventW(ptr long long long ptr long long wstr ptr long ptr ptr) 
@ stdcall EnableTrace(long long long ptr double)
@ stdcall EncryptFileA(str)
@ stdcall EncryptFileW(wstr)
@ stdcall EncryptedFileKeyInfo(long long long)
@ stdcall EncryptionDisable(wstr long)
@ stdcall EnumDependentServicesA(long long ptr long ptr ptr)
@ stdcall EnumDependentServicesW(long long ptr long ptr ptr)
@ stdcall EnumServiceGroupW(ptr long long ptr long ptr ptr ptr wstr)
@ stdcall EnumServicesStatusA(long long long ptr long ptr ptr ptr)
@ stdcall EnumServicesStatusExA(long long long long ptr long ptr ptr ptr str)
@ stdcall EnumServicesStatusExW(long long long long ptr long ptr ptr ptr wstr)
@ stdcall EnumServicesStatusW(long long long ptr long ptr ptr ptr)
@ stdcall EnumerateTraceGuids(ptr long ptr)
@ stdcall EqualDomainSid(ptr ptr ptr)
@ stdcall EqualPrefixSid(ptr ptr)
@ stdcall EqualSid(ptr ptr)
@ stdcall FileEncryptionStatusA(str ptr)
@ stdcall FileEncryptionStatusW(wstr ptr)
@ stdcall FindFirstFreeAce(ptr ptr)
@ stdcall FlushTraceA(long long str ptr)
@ stdcall FlushTraceW(long long wstr ptr)
@ stdcall FreeEncryptedFileKeyInfo(long)
@ stdcall FreeEncryptionCertificateHashList(ptr)
@ stdcall FreeInheritedFromArray(ptr long ptr)
@ stdcall FreeSid(ptr)
@ stdcall GetAccessPermissionsForObjectA(str long str str ptr ptr ptr ptr ptr)
@ stdcall GetAccessPermissionsForObjectW(wstr long wstr wstr ptr ptr ptr ptr ptr)
@ stdcall GetAce(ptr long ptr)
@ stdcall GetAclInformation(ptr ptr long long)
@ stdcall GetAuditedPermissionsFromAclA(ptr ptr ptr ptr)
@ stdcall GetAuditedPermissionsFromAclW(ptr ptr ptr ptr)
@ stdcall GetCurrentHwProfileA(ptr)
@ stdcall GetCurrentHwProfileW(ptr)
@ stdcall GetEffectiveRightsFromAclA(ptr ptr ptr)
@ stdcall GetEffectiveRightsFromAclW(ptr ptr ptr)
@ stdcall GetEventLogInformation(long long ptr long ptr)
@ stdcall GetExplicitEntriesFromAclA(ptr ptr ptr) advapi32.GetExplicitEntriesFromAclW
@ stdcall GetExplicitEntriesFromAclW(ptr ptr ptr)
@ stdcall GetFileSecurityA(str long ptr long ptr)
@ stdcall GetFileSecurityW(wstr long ptr long ptr)
@ stdcall GetInformationCodeAuthzLevelW()
@ stdcall GetInformationCodeAuthzPolicyW()
@ stdcall GetInheritanceSourceA(str long long long ptr long ptr ptr ptr ptr)
@ stdcall GetInheritanceSourceW(wstr long long long ptr long ptr ptr ptr ptr)
@ stdcall GetKernelObjectSecurity(long long ptr long ptr)
@ stdcall GetLengthSid(ptr)
@ stdcall GetLocalManagedApplicationData(wstr wstr wstr)
@ stdcall GetLocalManagedApplications(long ptr ptr)
@ stdcall GetManagedApplicationCategories(long ptr)
@ stdcall GetManagedApplications(ptr long long ptr ptr)
@ stdcall GetMultipleTrusteeA(ptr)
@ stdcall GetMultipleTrusteeOperationA(ptr)
@ stdcall GetMultipleTrusteeOperationW(ptr)
@ stdcall GetMultipleTrusteeW(ptr)
@ stdcall GetNamedSecurityInfoA(str long long ptr ptr ptr ptr ptr)
@ stdcall GetNamedSecurityInfoExA(str long long str str ptr ptr str str)
@ stdcall GetNamedSecurityInfoExW(wstr long long wstr wstr ptr ptr wstr wstr)
@ stdcall GetNamedSecurityInfoW(wstr long long ptr ptr ptr ptr ptr)
@ stdcall GetNumberOfEventLogRecords(long ptr)
@ stdcall GetOldestEventLogRecord(long ptr)
@ stdcall GetOverlappedAccessResults(ptr long ptr ptr)
@ stdcall GetPrivateObjectSecurity(ptr long ptr long ptr)
@ stdcall GetSecurityDescriptorControl(ptr ptr ptr)
@ stdcall GetSecurityDescriptorDacl(ptr ptr ptr ptr)
@ stdcall GetSecurityDescriptorGroup(ptr ptr ptr)
@ stdcall GetSecurityDescriptorLength(ptr) ntdll.RtlLengthSecurityDescriptor
@ stdcall GetSecurityDescriptorOwner(ptr ptr ptr)
@ stdcall GetSecurityDescriptorRMControl(ptr ptr)
@ stdcall GetSecurityDescriptorSacl(ptr ptr ptr ptr)
@ stdcall GetSecurityInfo(long long long ptr ptr ptr ptr ptr)
@ stdcall GetSecurityInfoExA(long long long str str ptr ptr ptr ptr)
@ stdcall GetSecurityInfoExW(long long long wstr wstr ptr ptr ptr ptr)
@ stdcall GetServiceDisplayNameA(ptr str ptr ptr)
@ stdcall GetServiceDisplayNameW(ptr wstr ptr ptr)
@ stdcall GetServiceKeyNameA(long str ptr ptr)
@ stdcall GetServiceKeyNameW(long wstr ptr ptr)
@ stdcall GetSidIdentifierAuthority(ptr)
@ stdcall GetSidLengthRequired(long)
@ stdcall GetSidSubAuthority(ptr long)
@ stdcall GetSidSubAuthorityCount(ptr)
@ stdcall GetTokenInformation(long long ptr long ptr)
@ stdcall GetTraceEnableFlags(double)
@ stdcall GetTraceEnableLevel(double)
@ stdcall GetTraceLoggerHandle(ptr)
@ stdcall GetTrusteeFormA(ptr)
@ stdcall GetTrusteeFormW(ptr)
@ stdcall GetTrusteeNameA(ptr)
@ stdcall GetTrusteeNameW(ptr)
@ stdcall GetTrusteeTypeA(ptr)
@ stdcall GetTrusteeTypeW(ptr)
@ stdcall GetUserNameA(ptr ptr)
@ stdcall GetUserNameW(ptr ptr)
@ stdcall GetWindowsAccountDomainSid(ptr ptr ptr)
@ stdcall I_ScGetCurrentGroupStateW(ptr ptr ptr)
@ stdcall I_ScIsSecurityProcess()
@ stdcall I_ScPnPGetServiceName(long str long)
@ stdcall I_ScSendTSMessage(long long long long)
@ stdcall I_ScSetServiceBitsA(ptr long long long str)
@ stdcall I_ScSetServiceBitsW(ptr long long long wstr)
@ stdcall IdentifyCodeAuthzLevelW()
@ stdcall ImpersonateAnonymousToken(ptr)
@ stdcall ImpersonateLoggedOnUser(long)
@ stdcall ImpersonateNamedPipeClient(long)
@ stdcall ImpersonateSelf(long)
@ stdcall InitializeAcl(ptr long long)
@ stdcall InitializeSecurityDescriptor(ptr long)
@ stdcall InitializeSid(ptr ptr long)
@ stdcall InitiateSystemShutdownA(str str long long long)
@ stdcall InitiateSystemShutdownExA(str str long long long long)
@ stdcall InitiateSystemShutdownExW(wstr wstr long long long long)
@ stdcall InitiateSystemShutdownW(str str long long long)
@ stdcall InstallApplication(ptr)
@ stdcall IsTextUnicode(ptr long ptr) 
@ stdcall IsTokenRestricted(long)
@ stdcall IsTokenUntrusted(ptr)
@ stdcall IsValidAcl(ptr)
@ stdcall IsValidSecurityDescriptor(ptr)
@ stdcall IsValidSid(ptr)
@ stdcall IsWellKnownSid(ptr long)
@ stdcall LockServiceDatabase(ptr)
@ stdcall LogonUserA(str str str long long ptr)
@ stdcall LogonUserExA(str str str long long ptr ptr ptr ptr ptr)
@ stdcall LogonUserExW(wstr wstr wstr long long ptr ptr ptr ptr ptr)
@ stdcall LogonUserW(wstr wstr wstr long long ptr)
@ stdcall LookupAccountNameA(str str ptr ptr ptr ptr ptr)
@ stdcall LookupAccountNameW(wstr wstr ptr ptr ptr ptr ptr)
@ stdcall LookupAccountSidA(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall LookupAccountSidW(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall LookupPrivilegeDisplayNameA(str str str ptr ptr)
@ stdcall LookupPrivilegeDisplayNameW(wstr wstr wstr ptr ptr)
@ stdcall LookupPrivilegeNameA(str ptr ptr long)
@ stdcall LookupPrivilegeNameW(wstr ptr ptr long)
@ stdcall LookupPrivilegeValueA(ptr ptr ptr)
@ stdcall LookupPrivilegeValueW(ptr ptr ptr)
@ stdcall LookupSecurityDescriptorPartsA(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall LookupSecurityDescriptorPartsW(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall LsaAddAccountRights(ptr ptr ptr long)
@ stdcall LsaAddPrivilegesToAccount(ptr ptr)
@ stdcall LsaClearAuditLog(ptr)
@ stdcall LsaClose(ptr)
@ stdcall LsaCreateAccount(ptr ptr long ptr)
@ stdcall LsaCreateSecret(ptr ptr long ptr)
@ stdcall LsaCreateTrustedDomain(ptr ptr long ptr)
@ stdcall LsaCreateTrustedDomainEx(ptr ptr ptr long ptr)
@ stdcall LsaDelete(ptr)
@ stdcall LsaDeleteTrustedDomain(ptr ptr)
@ stdcall LsaEnumerateAccountRights(ptr ptr ptr ptr)
@ stdcall LsaEnumerateAccounts(ptr ptr ptr long ptr)
@ stdcall LsaEnumerateAccountsWithUserRight(ptr ptr ptr ptr)
@ stdcall LsaEnumeratePrivileges(ptr ptr ptr long ptr)
@ stdcall LsaEnumeratePrivilegesOfAccount(ptr ptr)
@ stdcall LsaEnumerateTrustedDomains(ptr ptr ptr long ptr)
@ stdcall LsaEnumerateTrustedDomainsEx(ptr ptr ptr long ptr)
@ stdcall LsaFreeMemory(ptr)
@ stdcall LsaGetQuotasForAccount(ptr ptr)
@ stdcall LsaGetRemoteUserName(ptr ptr ptr)
@ stdcall LsaGetSystemAccessAccount(ptr ptr)
@ stdcall LsaGetUserName(ptr ptr)
@ stdcall LsaICLookupNames(long long long ptr ptr long long long long long)
@ stdcall LsaICLookupNamesWithCreds(wstr wstr long long ptr long long long long long long long)
@ stdcall LsaICLookupSids(long long long ptr ptr long long long long)
@ stdcall LsaICLookupSidsWithCreds(wstr wstr long long ptr long long long long long long long)
@ stdcall LsaLookupNames(long long ptr ptr ptr)
@ stdcall LsaLookupNames2(ptr long long ptr ptr ptr)
@ stdcall LsaLookupPrivilegeDisplayName(ptr ptr ptr ptr)
@ stdcall LsaLookupPrivilegeName(ptr ptr ptr)
@ stdcall LsaLookupPrivilegeValue(ptr ptr ptr)
@ stdcall LsaLookupSids(ptr long ptr ptr ptr)
@ stdcall LsaNtStatusToWinError(long)
@ stdcall LsaOpenAccount(ptr ptr long ptr)
@ stdcall LsaOpenPolicy(ptr ptr long ptr)
@ stdcall LsaOpenPolicySce(ptr ptr long ptr)
@ stdcall LsaOpenSecret(ptr ptr long ptr)
@ stdcall LsaOpenTrustedDomain(ptr ptr long ptr)
@ stdcall LsaOpenTrustedDomainByName(ptr ptr long ptr)
@ stdcall LsaQueryDomainInformationPolicy(ptr long ptr)
@ stdcall LsaQueryForestTrustInformation(ptr ptr ptr)
@ stdcall LsaQueryInfoTrustedDomain(long long long)
@ stdcall LsaQueryInformationPolicy(ptr long ptr)
@ stdcall LsaQuerySecret(ptr ptr ptr ptr ptr)
@ stdcall LsaQuerySecurityObject(ptr long ptr)
@ stdcall LsaQueryTrustedDomainInfo(ptr ptr long ptr)
@ stdcall LsaQueryTrustedDomainInfoByName(ptr ptr long ptr)
@ stdcall LsaRemoveAccountRights(ptr ptr long ptr long)
@ stdcall LsaRemovePrivilegesFromAccount(ptr long ptr)
@ stdcall LsaRetrievePrivateData(ptr ptr ptr)
@ stdcall LsaSetDomainInformationPolicy(ptr long ptr)
@ stdcall LsaSetForestTrustInformation(ptr ptr ptr long ptr)
@ stdcall LsaSetInformationPolicy(long long ptr)
@ stdcall LsaSetInformationTrustedDomain(ptr long ptr)
@ stdcall LsaSetQuotasForAccount(ptr ptr)
@ stdcall LsaSetSecret(ptr ptr ptr)
@ stdcall LsaSetSecurityObject(ptr long ptr)
@ stdcall LsaSetSystemAccessAccount(ptr long)
@ stdcall LsaSetTrustedDomainInfoByName(ptr ptr long ptr)
@ stdcall LsaSetTrustedDomainInformation(ptr ptr long ptr)
@ stdcall LsaStorePrivateData(ptr ptr ptr)
@ stdcall MD4Final(ptr)
@ stdcall MD4Init(ptr)
@ stdcall MD4Update(ptr ptr long)
@ stdcall MD5Final(ptr)
@ stdcall MD5Init(ptr)
@ stdcall MD5Update(ptr ptr long)
@ stdcall MSChapSrvChangePassword(wstr wstr long ptr ptr ptr ptr)
@ stdcall MSChapSrvChangePassword2(wstr wstr ptr ptr long ptr ptr)
@ stdcall MakeAbsoluteSD(ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr)
@ stdcall MakeAbsoluteSD2(ptr ptr)
@ stdcall MakeSelfRelativeSD(ptr ptr ptr)
@ stdcall MapGenericMask(ptr ptr) ntdll.RtlMapGenericMask
@ stdcall NotifyBootConfigStatus(long)
@ stdcall NotifyChangeEventLog(long long)
@ stdcall ObjectCloseAuditAlarmA(str ptr long)
@ stdcall ObjectCloseAuditAlarmW(wstr ptr long)
@ stdcall ObjectDeleteAuditAlarmA(str ptr long)
@ stdcall ObjectDeleteAuditAlarmW(wstr ptr long)
@ stdcall ObjectOpenAuditAlarmA(str ptr str str ptr long long long ptr long long ptr)
@ stdcall ObjectOpenAuditAlarmW(wstr ptr wstr wstr ptr long long long ptr long long ptr)
@ stdcall ObjectPrivilegeAuditAlarmA(str ptr long long ptr long)
@ stdcall ObjectPrivilegeAuditAlarmW(wstr ptr long long ptr long)
@ stdcall OpenBackupEventLogA(str str)
@ stdcall OpenBackupEventLogW(wstr wstr)
@ stdcall OpenEncryptedFileRawA(str long ptr)
@ stdcall OpenEncryptedFileRawW(wstr long ptr)
@ stdcall OpenEventLogA(str str)
@ stdcall OpenEventLogW(wstr wstr)
@ stdcall OpenProcessToken(long long ptr)
@ stdcall OpenSCManagerA(str str long)
@ stdcall OpenSCManagerW(wstr wstr long)
@ stdcall OpenServiceA(long str long)
@ stdcall OpenServiceW(long wstr long)
@ stdcall OpenThreadToken(long long long ptr)
@ stdcall OpenTraceA(ptr)
@ stdcall OpenTraceW(ptr)
@ stdcall PrivilegeCheck(ptr ptr ptr)
@ stdcall PrivilegedServiceAuditAlarmA(str str long ptr long)
@ stdcall PrivilegedServiceAuditAlarmW(wstr wstr long ptr long)
@ stdcall ProcessIdleTasks()
@ stdcall ProcessTrace(ptr long ptr ptr)
@ stdcall QueryAllTracesA(ptr long ptr)
@ stdcall QueryAllTracesW(ptr long ptr)
@ stdcall QueryRecoveryAgentsOnEncryptedFile(wstr ptr)
@ stdcall QueryServiceConfig2A(long long ptr long ptr)
@ stdcall QueryServiceConfig2W(long long ptr long ptr)
@ stdcall QueryServiceConfigA(long ptr long ptr)
@ stdcall QueryServiceConfigW(long ptr long ptr)
@ stdcall QueryServiceLockStatusA(long ptr long ptr)
@ stdcall QueryServiceLockStatusW(long ptr long ptr)
@ stdcall QueryServiceObjectSecurity(long long ptr long ptr)
@ stdcall QueryServiceStatus(long ptr)
@ stdcall QueryServiceStatusEx(long long ptr long ptr)
@ stdcall QueryTraceA(int64 str ptr)
@ stdcall QueryTraceW(int64 wstr ptr)
@ stdcall QueryUsersOnEncryptedFile(wstr ptr) 
@ stdcall ReadEncryptedFileRaw(ptr ptr ptr)
@ stdcall ReadEventLogA(long long long ptr long ptr ptr)
@ stdcall ReadEventLogW(long long long ptr long ptr ptr)
@ stdcall RegCloseKey(ptr) 
@ stdcall RegConnectRegistryA(str long ptr)
@ stdcall RegConnectRegistryW(wstr long ptr)
@ stdcall RegCreateKeyA(long str ptr)
@ stdcall RegCreateKeyExA(long str long ptr long long ptr ptr ptr)
@ stdcall RegCreateKeyExW(long wstr long ptr long long ptr ptr ptr)
@ stdcall RegCreateKeyW(long wstr ptr)
@ stdcall RegDeleteKeyA(long str)
@ stdcall RegDeleteKeyW(long wstr)
@ stdcall RegDeleteValueA(long str)
@ stdcall RegDeleteValueW(long wstr)
@ stdcall RegDisablePredefinedCache()
@ stdcall RegEnumKeyA(long long ptr long)
@ stdcall RegEnumKeyExA(long long ptr ptr ptr ptr ptr ptr)
@ stdcall RegEnumKeyExW(long long ptr ptr ptr ptr ptr ptr)
@ stdcall RegEnumKeyW(long long ptr long)
@ stdcall RegEnumValueA(long long ptr ptr ptr ptr ptr ptr)
@ stdcall RegEnumValueW(long long ptr ptr ptr ptr ptr ptr)
@ stdcall RegFlushKey(long)
@ stdcall RegGetKeySecurity(long long ptr ptr)
@ stdcall RegLoadKeyA(long str str)
@ stdcall RegLoadKeyW(long wstr wstr)
@ stdcall RegNotifyChangeKeyValue(long long long long long)
@ stdcall RegOpenCurrentUser(long ptr)
@ stdcall RegOpenKeyA(long str ptr)
@ stdcall RegOpenKeyExA(long str long long ptr)
@ stdcall RegOpenKeyExW(long wstr long long ptr)
@ stdcall RegOpenKeyW(long wstr ptr)
@ stdcall RegOpenUserClassesRoot(ptr long long ptr)
@ stdcall RegOverridePredefKey(long long)
@ stdcall RegQueryInfoKeyA(long ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr)
@ stdcall RegQueryInfoKeyW(long ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr)
@ stdcall RegQueryMultipleValuesA(long ptr long ptr ptr)
@ stdcall RegQueryMultipleValuesW(long ptr long ptr ptr)
@ stdcall RegQueryValueA(long str ptr ptr)
@ stdcall RegQueryValueExA(long str ptr ptr ptr ptr)
@ stdcall RegQueryValueExW(long wstr ptr ptr ptr ptr)
@ stdcall RegQueryValueW(long wstr ptr ptr)
@ stdcall RegReplaceKeyA(long str str str)
@ stdcall RegReplaceKeyW(long wstr wstr wstr)
@ stdcall RegRestoreKeyA(long str long)
@ stdcall RegRestoreKeyW(long wstr long)
@ stdcall RegSaveKeyA(long ptr ptr)
@ stdcall RegSaveKeyExA(long str ptr long)
@ stdcall RegSaveKeyExW(long str ptr long)
@ stdcall RegSaveKeyW(long ptr ptr)
@ stdcall RegSetKeySecurity(long long ptr)
@ stdcall RegSetValueA(long str long ptr long)
@ stdcall RegSetValueExA(long str long long ptr long)
@ stdcall RegSetValueExW(long wstr long long ptr long)
@ stdcall RegSetValueW(long wstr long ptr long)
@ stdcall RegUnLoadKeyA(long str)
@ stdcall RegUnLoadKeyW(long wstr)
@ stdcall RegisterEventSourceA(ptr ptr)
@ stdcall RegisterEventSourceW(ptr ptr)
@ stdcall RegisterIdleTask(long long ptr ptr)
@ stdcall RegisterServiceCtrlHandlerA(str ptr)
@ stdcall RegisterServiceCtrlHandlerExA(str ptr ptr)
@ stdcall RegisterServiceCtrlHandlerExW(wstr ptr ptr)
@ stdcall RegisterServiceCtrlHandlerW(wstr ptr)
@ stdcall RegisterTraceGuidsA(ptr ptr ptr long ptr str str ptr)
@ stdcall RegisterTraceGuidsW(ptr ptr ptr long ptr wstr wstr ptr)
@ stdcall RemoveTraceCallback(ptr)
@ stdcall RemoveUsersFromEncryptedFile(wstr ptr)
@ stdcall ReportEventA(long long long long ptr long long str ptr)
@ stdcall ReportEventW(long long long long ptr long long wstr ptr)
@ stdcall RevertToSelf()
@ stdcall SaferCloseLevel(ptr)
@ stdcall SaferComputeTokenFromLevel(ptr ptr ptr long ptr)
@ stdcall SaferCreateLevel(long long long ptr ptr)
@ stdcall SaferGetLevelInformation(ptr long ptr long ptr)
@ stdcall SaferGetPolicyInformation(long long long ptr ptr ptr)
@ stdcall SaferIdentifyLevel(long ptr ptr ptr)
@ stdcall SaferRecordEventLogEntry(ptr wstr ptr)
@ stdcall SaferSetLevelInformation(ptr long ptr long)
@ stdcall SaferSetPolicyInformation(long long long ptr ptr)
@ stdcall SaferiChangeRegistryScope(ptr long)
@ stdcall SaferiCompareTokenLevels(long long long)
@ stdcall SaferiIsExecutableFileType(wstr long)
@ stdcall SaferiPopulateDefaultsInRegistry(ptr long)
@ stdcall SaferiRecordEventLogEntry()
@ stdcall SaferiReplaceProcessThreadTokens(ptr ptr ptr)
@ stdcall SaferiSearchMatchingHashRules(long ptr long long ptr ptr)
@ stdcall SetAclInformation(ptr ptr long long)
@ stdcall SetEntriesInAccessListA(long ptr long str ptr ptr)
@ stdcall SetEntriesInAccessListW(long ptr long wstr ptr ptr)
@ stdcall SetEntriesInAclA(long ptr ptr ptr)
@ stdcall SetEntriesInAclW(long ptr ptr ptr)
@ stdcall SetEntriesInAuditListA(long ptr long str ptr ptr)
@ stdcall SetEntriesInAuditListW(long ptr long wstr ptr ptr)
@ stdcall SetFileSecurityA(str long ptr)
@ stdcall SetFileSecurityW(wstr long ptr)
@ stdcall SetInformationCodeAuthzLevelW()
@ stdcall SetInformationCodeAuthzPolicyW()
@ stdcall SetKernelObjectSecurity(long long ptr)
@ stdcall SetNamedSecurityInfoA(str long ptr ptr ptr ptr ptr)
@ stdcall SetNamedSecurityInfoExA(str long long str ptr ptr str str ptr)
@ stdcall SetNamedSecurityInfoExW(wstr long long wstr ptr ptr wstr wstr ptr)
@ stdcall SetNamedSecurityInfoW(wstr long ptr ptr ptr ptr ptr)
@ stdcall SetPrivateObjectSecurity(long ptr ptr ptr long)
@ stdcall SetPrivateObjectSecurityEx(long ptr ptr long ptr ptr)
@ stdcall SetSecurityDescriptorControl(ptr long long)
@ stdcall SetSecurityDescriptorDacl(ptr long ptr long)
@ stdcall SetSecurityDescriptorGroup(ptr ptr long)
@ stdcall SetSecurityDescriptorOwner(ptr ptr long)
@ stdcall SetSecurityDescriptorRMControl(ptr ptr)
@ stdcall SetSecurityDescriptorSacl(ptr long ptr long)
@ stdcall SetSecurityInfo(long long long ptr ptr ptr ptr)
@ stdcall SetSecurityInfoExA(ptr long long str ptr ptr str str ptr)
@ stdcall SetSecurityInfoExW(ptr long long wstr ptr ptr wstr wstr ptr)
@ stdcall SetServiceBits(long long long long)
@ stdcall SetServiceObjectSecurity(long long ptr)
@ stdcall SetServiceStatus(long long)
@ stdcall SetThreadToken(ptr ptr)
@ stdcall SetTokenInformation(long long ptr long)
@ stdcall SetTraceCallback(ptr ptr)
@ stdcall SetUserFileEncryptionKey(ptr)
@ stdcall StartServiceA(long long ptr)
@ stdcall StartServiceCtrlDispatcherA(ptr)
@ stdcall StartServiceCtrlDispatcherW(ptr)
@ stdcall StartServiceW(long long ptr)
@ stdcall StartTraceA(ptr str ptr)
@ stdcall StartTraceW(ptr wstr ptr)
@ stdcall StopTraceA(long long str ptr)
@ stdcall StopTraceW(long long wstr ptr)
@ stdcall SystemFunction001(ptr ptr ptr)
@ stdcall SystemFunction002(ptr ptr ptr)
@ stdcall SystemFunction003(ptr ptr)
@ stdcall SystemFunction004(ptr ptr ptr)
@ stdcall SystemFunction005(ptr ptr ptr)
@ stdcall SystemFunction006(ptr ptr)
@ stdcall SystemFunction007(ptr ptr)
@ stdcall SystemFunction008(ptr ptr ptr)
@ stdcall SystemFunction009(ptr ptr ptr)
@ stdcall SystemFunction010(ptr ptr ptr)
@ stdcall SystemFunction011(ptr ptr ptr) SystemFunction010
@ stdcall SystemFunction012(ptr ptr ptr)
@ stdcall SystemFunction013(ptr ptr ptr)
@ stdcall SystemFunction014(ptr ptr ptr) SystemFunction012
@ stdcall SystemFunction015(ptr ptr ptr) SystemFunction013
@ stdcall SystemFunction016(ptr ptr ptr) SystemFunction012
@ stdcall SystemFunction017(ptr ptr ptr) SystemFunction013
@ stdcall SystemFunction018(ptr ptr ptr) SystemFunction012
@ stdcall SystemFunction019(ptr ptr ptr) SystemFunction013
@ stdcall SystemFunction020(ptr ptr ptr) SystemFunction012
@ stdcall SystemFunction021(ptr ptr ptr) SystemFunction013
@ stdcall SystemFunction022(ptr ptr ptr) SystemFunction012
@ stdcall SystemFunction023(ptr ptr ptr) SystemFunction013
@ stdcall SystemFunction024(ptr ptr ptr)
@ stdcall SystemFunction025(ptr ptr ptr)
@ stdcall SystemFunction026(ptr ptr ptr) SystemFunction024
@ stdcall SystemFunction027(ptr ptr ptr) SystemFunction025
@ stdcall SystemFunction028(long long)
@ stdcall SystemFunction029(long long)
@ stdcall SystemFunction030(ptr ptr)
@ stdcall SystemFunction031(ptr ptr) SystemFunction030
@ stdcall SystemFunction032(ptr ptr)
@ stdcall SystemFunction033(long long)
@ stdcall SystemFunction034(long long)
@ stdcall SystemFunction035(str)
@ stdcall SystemFunction036(ptr long) # RtlGenRandom
@ stdcall SystemFunction040(ptr long long) # RtlEncryptMemory
@ stdcall SystemFunction041(ptr long long) # RtlDecryptMemory
@ stdcall TraceEvent(double ptr)
@ stdcall TraceEventInstance(long long ptr ptr ptr)
@ varargs TraceMessage(ptr long ptr long)
@ stdcall TraceMessageVa(long long long ptr long ptr)
@ stdcall TreeResetNamedSecurityInfoA(str ptr ptr ptr ptr ptr ptr long ptr ptr ptr)
@ stdcall TreeResetNamedSecurityInfoW(wstr long long ptr ptr ptr ptr long ptr long ptr)
@ stdcall TrusteeAccessToObjectA(str long str ptr long ptr)
@ stdcall TrusteeAccessToObjectW(wstr long wstr ptr long ptr)
@ stdcall UninstallApplication(ptr long)
@ stdcall UnlockServiceDatabase(ptr)
@ stdcall UnregisterIdleTask(long ptr ptr)
@ stdcall UnregisterTraceGuids(double)
@ stdcall UpdateTraceA(long long str ptr)
@ stdcall UpdateTraceW(long long wstr ptr)
@ stdcall WdmWmiServiceMain(ptr long)
@ stdcall WmiCloseBlock(ptr)
@ stdcall WmiCloseTraceWithCursor(ptr) 
@ stdcall WmiConvertTimestamp(long long long) 
@ stdcall WmiDevInstToInstanceNameA(ptr long str long)
@ stdcall WmiDevInstToInstanceNameW(ptr long wstr long)
@ stdcall WmiEnumerateGuids(long long)
@ stdcall WmiExecuteMethodA(long str long long long long long)
@ stdcall WmiExecuteMethodW(long wstr long long long long long)
@ stdcall WmiFileHandleToInstanceNameA(long long ptr long)
@ stdcall WmiFileHandleToInstanceNameW(long long ptr long)
@ stdcall WmiFreeBuffer(ptr)
@ stdcall WmiGetFirstTraceOffset(long long)
@ stdcall WmiGetNextEvent(long) 
@ stdcall WmiGetTraceHeader(long long long)
@ stdcall WmiMofEnumerateResourcesA(long long long)
@ stdcall WmiMofEnumerateResourcesW(long long long)
@ stdcall WmiNotificationRegistrationA()
@ stdcall WmiNotificationRegistrationW()
@ stdcall WmiOpenBlock(long long long)
@ stdcall WmiOpenTraceWithCursor(long long)
@ stdcall WmiParseTraceEvent(long long long long long)
@ stdcall WmiQueryAllDataA(long ptr ptr)
@ stdcall WmiQueryAllDataMultipleA(long long long ptr)
@ stdcall WmiQueryAllDataMultipleW(long long long ptr)
@ stdcall WmiQueryAllDataW(long ptr ptr)
@ stdcall WmiQueryGuidInformation(ptr ptr)
@ stdcall WmiQuerySingleInstanceA(long str ptr ptr)
@ stdcall WmiQuerySingleInstanceMultipleA(long long long long long)
@ stdcall WmiQuerySingleInstanceMultipleW(long long long long long)
@ stdcall WmiQuerySingleInstanceW(long wstr ptr ptr)
@ stdcall WmiReceiveNotificationsA()
@ stdcall WmiReceiveNotificationsW()
@ stdcall WmiSetSingleInstanceA(long str long long ptr)
@ stdcall WmiSetSingleInstanceW(long wstr long long ptr)
@ stdcall WmiSetSingleItemA(long str long long long ptr)
@ stdcall WmiSetSingleItemW(long wstr long long long ptr)
@ stdcall Wow64Win32ApiEntry(long long long)
@ stdcall WriteEncryptedFileRaw(ptr ptr ptr)

#Only on XP
@ stdcall CreateProcessAsUserSecure(ptr str str ptr ptr long long ptr str ptr ptr) advapibase.CreateProcessAsUserSecure;only on XP (needed for synchronization)
@ stdcall QueryWindows31FilesMigration(long) advapibase.QueryWindows31FilesMigration
@ stdcall SynchronizeWindows31FilesAndWindowsNTRegistry(long long long long) advapibase.SynchronizeWindows31FilesAndWindowsNTRegistry  ;only on XP (needed for synchronization)

#Missing on XP
@ stdcall CreateProcessWithTokenW(ptr long wstr wstr long ptr wstr ptr ptr) ;advapinew.CreateProcessWithTokenW
@ stdcall ElfReportEventAndSourceW(ptr long wstr long long long ptr wstr long long wstr ptr long ptr ptr) ;advapinew.ElfReportEventAndSourceW
@ stdcall I_QueryTagInformation(long long long) ;advapinew.I_QueryTagInformation	 ;native on Server 2003, but, missing on XP (needed for synchronization)
@ stdcall RegConnectRegistryExA(str ptr long ptr)  	;native on Server 2003, but, missing on XP (needed for synchronization)
@ stdcall RegConnectRegistryExW(wstr ptr long ptr) 	;native on Server 2003, but, missing on XP (needed for synchronization)
@ stdcall RegDeleteKeyExA(long str long long)	 ;native on Server 2003, but, missing on XP (needed for synchronization) 
@ stdcall RegDeleteKeyExW(long wstr long long) 	;native on Server 2003, but, missing on XP (needed for synchronization) 
@ stdcall RegDisableReflectionKey(ptr) 	;native on Server 2003, but, missing on XP (needed for synchronization) 
@ stdcall RegEnableReflectionKey(ptr) 	;native on Server 2003, but, missing on XP (needed for synchronization) 
@ stdcall RegQueryReflectionKey(ptr ptr)	 ;native on Server 2003, but, missing on XP (needed for synchronization) 

#Missing on Server 2003 RTM
@ stdcall RegDisablePredefinedCacheEx() advapinew.RegDisablePredefinedCacheEx
@ stdcall RegGetValueA(long str str long ptr ptr ptr) advapinew.RegGetValueA
@ stdcall RegGetValueW(long wstr wstr long ptr ptr ptr) advapinew.RegGetValueW

#Vista Functions implemented (without redirection)
@ stdcall EventActivityIdControl(long ptr)
@ stdcall EventEnabled(long long ptr)
@ stdcall EventProviderEnabled(int64 long long long)
@ stdcall EventRegister(ptr ptr ptr ptr)
@ stdcall EventUnregister(long long)
@ stdcall EventWrite(long long ptr long ptr)
@ stdcall EventWriteEndScenario(long long ptr long ptr)
@ stdcall EventWriteEx(long long ptr long long long ptr ptr long ptr)
@ stdcall EventWriteStartScenario(long long ptr long ptr)
@ stdcall EventWriteString(int64 long long long wstr)
@ stdcall EventWriteTransfer(int64 ptr ptr ptr long ptr)
@ stdcall AddMandatoryAce(ptr long long long ptr)
@ stdcall ProcessIdleTasksW() ProcessIdleTasks

#from Vista/Longhorn advapi32 (advapinew) 
@ stdcall AddUsersToEncryptedFileEx(long long long long)
@ stdcall AuditComputeEffectivePolicyBySid(ptr ptr long ptr)
@ stdcall AuditComputeEffectivePolicyByToken(ptr ptr long ptr)
@ stdcall AuditEnumerateCategories(ptr ptr)
@ stdcall AuditEnumeratePerUserPolicy(ptr)
@ stdcall AuditEnumerateSubCategories(ptr long ptr ptr)
@ stdcall AuditFree(ptr)
@ stdcall AuditLookupCategoryGuidFromCategoryId(ptr ptr)
@ stdcall AuditLookupCategoryIdFromCategoryGuid(ptr ptr)
@ stdcall AuditLookupCategoryNameA(ptr str)
@ stdcall AuditLookupCategoryNameW(ptr wstr)
@ stdcall AuditLookupSubCategoryNameA(ptr str)
@ stdcall AuditLookupSubCategoryNameW(ptr str)
@ stdcall AuditQueryPerUserPolicy(ptr ptr long ptr)
@ stdcall AuditQuerySecurity(long ptr)
@ stdcall AuditQuerySystemPolicy(ptr long ptr)
@ stdcall AuditSetPerUserPolicy(ptr ptr long)
@ stdcall AuditSetSecurity(ptr long)
@ stdcall AuditSetSystemPolicy(ptr long)
@ stdcall CheckAppInitBlockedServiceIdentity(long)
@ stdcall CloseThreadWaitChainSession(ptr)
@ stdcall ControlServiceExA(ptr long long ptr)
@ stdcall ControlServiceExW(ptr long long ptr)
@ stdcall CredBackupCredentials(long ptr ptr long long)
@ stdcall CredEncryptAndMarshalBinaryBlob(long long long)
@ stdcall CredFindBestCredentialA(str long long ptr) 
@ stdcall CredFindBestCredentialW(wstr long long ptr)
@ stdcall CredIsProtectedA(str ptr)
@ stdcall CredIsProtectedW(wstr ptr)
@ stdcall CredpConvertOneCredentialSize(long long)
@ stdcall CredpEncodeSecret(long ptr long long long)
@ stdcall CredProfileUnloaded()
@ stdcall CredProtectA(long str long str long ptr)
@ stdcall CredProtectW(long wstr long wstr long ptr)
@ stdcall CredReadByTokenHandle(long ptr long long long)
@ stdcall CredRestoreCredentials(ptr ptr long long)
@ stdcall CredUnprotectA(long str long str ptr)
@ stdcall CredUnprotectW(long wstr long wstr ptr)
@ stdcall EnableTraceEx(ptr ptr int64 long long long long long long long ptr) 
@ stdcall EnumerateTraceGuidsEx(long ptr long ptr long ptr)
@ stdcall EventAccessControl(ptr long ptr long long)
@ stdcall EventAccessQuery(ptr ptr ptr)
@ stdcall EventAccessRemove(ptr)
@ stdcall FlushEfsCache(ptr)
@ stdcall FreeEncryptedFileMetadata(ptr)
@ stdcall GetEncryptedFileMetadata(wstr ptr ptr)
@ stdcall GetThreadWaitChain(ptr long long long ptr ptr ptr)
@ stdcall I_ScQueryServiceConfig(long long long)
@ stdcall I_ScSendPnPMessage(long long long long long)
@ stdcall I_ScValidatePnPService(long long long)
@ stdcall InitiateShutdownA(str str long long long)
@ stdcall InitiateShutdownW(wstr wstr long long long)
@ stdcall IsValidRelativeSecurityDescriptor(ptr long long)
@ stdcall LogonUserExExW(str str str long long ptr ptr ptr ptr ptr ptr)
@ stdcall LsaManageSidNameMapping(long ptr ptr)
@ stdcall NotifyServiceStatusChange(ptr long ptr) 
@ stdcall NotifyServiceStatusChangeA(ptr long ptr) 
@ stdcall NotifyServiceStatusChangeW(ptr long ptr) NotifyServiceStatusChange
@ stdcall PerfAddCounters(ptr ptr long)
@ stdcall PerfCloseQueryHandle(ptr)
@ stdcall PerfCreateInstance(ptr ptr wstr long)
@ stdcall PerfDecrementULongCounterValue(ptr ptr long long)
@ stdcall PerfDecrementULongLongCounterValue(ptr ptr long long long)
@ stdcall PerfDeleteCounters(ptr ptr long)
@ stdcall PerfDeleteInstance(ptr ptr)
@ stdcall PerfEnumerateCounterSet(long ptr long long)
@ stdcall PerfEnumerateCounterSetInstances(long ptr ptr long long)
@ stdcall PerfIncrementULongCounterValue(ptr ptr long long)
@ stdcall PerfIncrementULongLongCounterValue(ptr ptr long long long)
@ stdcall PerfQueryInstance(ptr ptr wstr long)
@ stdcall PerfOpenQueryHandle(long ptr)
@ stdcall PerfQueryCounterData(ptr ptr long long)
@ stdcall PerfQueryCounterInfo(ptr ptr long long)
@ stdcall PerfQueryCounterSetRegistrationInfo(long long long long long long long)
@ stdcall PerfSetCounterSetInfo(ptr ptr long)
@ stdcall PerfSetCounterRefValue(ptr ptr long ptr)
@ stdcall PerfSetULongCounterValue(ptr ptr long long)
@ stdcall PerfSetULongLongCounterValue(ptr ptr long long long)
@ stdcall PerfStartProvider(ptr ptr ptr)
@ stdcall PerfStartProviderEx(ptr ptr ptr)
@ stdcall PerfStopProvider(ptr)
@ stdcall QuerySecurityAccessMask(long ptr)
@ stdcall OpenThreadWaitChainSession(long ptr)
@ stdcall RegCopyTreeA(ptr str ptr)
@ stdcall RegCopyTreeW(ptr str ptr)
@ stdcall RegCreateKeyExA(ptr str long ptr long long ptr ptr ptr) 
@ stdcall RegCreateKeyExW(ptr wstr long ptr long long ptr ptr ptr) 
@ stdcall RegCreateKeyTransactedA(ptr str long str long long ptr ptr ptr ptr ptr)
@ stdcall RegCreateKeyTransactedW(ptr wstr long wstr long long ptr ptr ptr ptr ptr)
@ stdcall RegDeleteKeyTransactedA(ptr str long long ptr ptr)
@ stdcall RegDeleteKeyTransactedW(ptr wstr long long ptr ptr)
@ stdcall RegDeleteKeyValueA(ptr str str)
@ stdcall RegDeleteKeyValueW(ptr wstr wstr) 
@ stdcall RegDeleteTreeA(long str)
@ stdcall RegDeleteTreeW(long wstr)
@ stdcall RegisterWaitChainCOMCallback(ptr ptr)
@ stdcall RegLoadAppKeyA(str ptr long long long)
@ stdcall RegLoadAppKeyW(wstr ptr long long long)
@ stdcall RegLoadKeyA(ptr str str)
@ stdcall RegLoadKeyW(ptr wstr wstr)
@ stdcall RegLoadMUIStringA(ptr str str long ptr long str)
@ stdcall RegLoadMUIStringW(ptr str str long ptr long str)
@ stdcall RegOpenKeyTransactedA(ptr str long long ptr ptr ptr)
@ stdcall RegOpenKeyTransactedW(ptr wstr long long ptr ptr ptr)
@ stdcall RegRenameKey(ptr wstr wstr)
@ stdcall RegSetKeyValueA(ptr str str long ptr long)
@ stdcall RegSetKeyValueW(ptr wstr wstr long ptr long)
@ stdcall SetEncryptedFileMetadata(wstr ptr ptr ptr long ptr)
@ stdcall SetSecurityAccessMask(long ptr)
@ stdcall SetUserFileEncryptionKeyEx(ptr long long ptr)
@ stdcall TreeSetNamedSecurityInfoA(str long long ptr ptr ptr ptr long)
@ stdcall TreeSetNamedSecurityInfoW(wstr long long ptr ptr ptr ptr long)
@ stdcall UsePinForEncryptedFilesA(long long long)
@ stdcall UsePinForEncryptedFilesW(long long long)#from Vista/Longhorn advapi32 (advapinew) 
@ stdcall AddUsersToEncryptedFileEx(long long long long)
@ stdcall AuditComputeEffectivePolicyBySid(ptr ptr long ptr)
@ stdcall AuditComputeEffectivePolicyByToken(ptr ptr long ptr)
@ stdcall AuditEnumerateCategories(ptr ptr)
@ stdcall AuditEnumeratePerUserPolicy(ptr)
@ stdcall AuditEnumerateSubCategories(ptr long ptr ptr)
@ stdcall AuditFree(ptr)
@ stdcall AuditLookupCategoryGuidFromCategoryId(ptr ptr)
@ stdcall AuditLookupCategoryIdFromCategoryGuid(ptr ptr)
@ stdcall AuditLookupCategoryNameA(ptr str)
@ stdcall AuditLookupCategoryNameW(ptr wstr)
@ stdcall AuditLookupSubCategoryNameA(ptr str)
@ stdcall AuditLookupSubCategoryNameW(ptr str)
@ stdcall AuditQueryPerUserPolicy(ptr ptr long ptr)
@ stdcall AuditQuerySecurity(long ptr)
@ stdcall AuditQuerySystemPolicy(ptr long ptr)
@ stdcall AuditSetPerUserPolicy(ptr ptr long)
@ stdcall AuditSetSecurity(ptr long)
@ stdcall AuditSetSystemPolicy(ptr long)
@ stdcall CheckAppInitBlockedServiceIdentity(long)
@ stdcall CloseThreadWaitChainSession(ptr)
@ stdcall ControlServiceExA(ptr long long ptr)
@ stdcall ControlServiceExW(ptr long long ptr)
@ stdcall CredBackupCredentials(long ptr ptr long long)
@ stdcall CredEncryptAndMarshalBinaryBlob(long long long)
@ stdcall CredFindBestCredentialA(str long long ptr) 
@ stdcall CredFindBestCredentialW(wstr long long ptr)
@ stdcall CredIsProtectedA(str ptr)
@ stdcall CredIsProtectedW(wstr ptr)
@ stdcall CredpConvertOneCredentialSize(long long)
@ stdcall CredpEncodeSecret(long ptr long long long)
@ stdcall CredProfileUnloaded()
@ stdcall CredProtectA(long str long str long ptr)
@ stdcall CredProtectW(long wstr long wstr long ptr)
@ stdcall CredReadByTokenHandle(long ptr long long long)
@ stdcall CredRestoreCredentials(ptr ptr long long)
@ stdcall CredUnprotectA(long str long str ptr)
@ stdcall CredUnprotectW(long wstr long wstr ptr)
@ stdcall EnableTraceEx(ptr ptr int64 long long long long long long long ptr) 
@ stdcall EnumerateTraceGuidsEx(long ptr long ptr long ptr)
@ stdcall EventAccessControl(ptr long ptr long long)
@ stdcall EventAccessQuery(ptr ptr ptr)
@ stdcall EventAccessRemove(ptr)
@ stdcall FlushEfsCache(ptr)
@ stdcall FreeEncryptedFileMetadata(ptr)
@ stdcall GetEncryptedFileMetadata(wstr ptr ptr)
@ stdcall GetThreadWaitChain(ptr long long long ptr ptr ptr)
@ stdcall I_ScQueryServiceConfig(long long long)
@ stdcall I_ScSendPnPMessage(long long long long long)
@ stdcall I_ScValidatePnPService(long long long)
@ stdcall InitiateShutdownA(str str long long long)
@ stdcall InitiateShutdownW(wstr wstr long long long)
@ stdcall IsValidRelativeSecurityDescriptor(ptr long long)
@ stdcall LogonUserExExW(str str str long long ptr ptr ptr ptr ptr ptr)
@ stdcall LsaManageSidNameMapping(long ptr ptr)
@ stdcall NotifyServiceStatusChange(ptr long ptr) 
@ stdcall NotifyServiceStatusChangeA(ptr long ptr) 
@ stdcall NotifyServiceStatusChangeW(ptr long ptr) NotifyServiceStatusChange
@ stdcall PerfAddCounters(ptr ptr long)
@ stdcall PerfCloseQueryHandle(ptr)
@ stdcall PerfCreateInstance(ptr ptr wstr long)
@ stdcall PerfDecrementULongCounterValue(ptr ptr long long)
@ stdcall PerfDecrementULongLongCounterValue(ptr ptr long long long)
@ stdcall PerfDeleteCounters(ptr ptr long)
@ stdcall PerfDeleteInstance(ptr ptr)
@ stdcall PerfEnumerateCounterSet(long ptr long long)
@ stdcall PerfEnumerateCounterSetInstances(long ptr ptr long long)
@ stdcall PerfIncrementULongCounterValue(ptr ptr long long)
@ stdcall PerfIncrementULongLongCounterValue(ptr ptr long long long)
@ stdcall PerfQueryInstance(ptr ptr wstr long)
@ stdcall PerfOpenQueryHandle(long ptr)
@ stdcall PerfQueryCounterData(ptr ptr long long)
@ stdcall PerfQueryCounterInfo(ptr ptr long long)
@ stdcall PerfQueryCounterSetRegistrationInfo(long long long long long long long)
@ stdcall PerfSetCounterSetInfo(ptr ptr long)
@ stdcall PerfSetCounterRefValue(ptr ptr long ptr)
@ stdcall PerfSetULongCounterValue(ptr ptr long long)
@ stdcall PerfSetULongLongCounterValue(ptr ptr long long long)
@ stdcall PerfStartProvider(ptr ptr ptr)
@ stdcall PerfStartProviderEx(ptr ptr ptr)
@ stdcall PerfStopProvider(ptr)
@ stdcall QuerySecurityAccessMask(long ptr)
@ stdcall OpenThreadWaitChainSession(long ptr)
@ stdcall RegCopyTreeA(ptr str ptr)
@ stdcall RegCopyTreeW(ptr str ptr)
@ stdcall RegCreateKeyTransactedA(ptr str long str long long ptr ptr ptr ptr ptr)
@ stdcall RegCreateKeyTransactedW(ptr wstr long wstr long long ptr ptr ptr ptr ptr)
@ stdcall RegDeleteKeyTransactedA(ptr str long long ptr ptr)
@ stdcall RegDeleteKeyTransactedW(ptr wstr long long ptr ptr)
@ stdcall RegDeleteKeyValueA(ptr str str)
@ stdcall RegDeleteKeyValueW(ptr wstr wstr) 
@ stdcall RegDeleteTreeA(long str)
@ stdcall RegDeleteTreeW(long wstr)
@ stdcall RegisterWaitChainCOMCallback(ptr ptr)
@ stdcall RegLoadAppKeyA(str ptr long long long)
@ stdcall RegLoadAppKeyW(wstr ptr long long long)
@ stdcall RegLoadMUIStringA(ptr str str long ptr long str)
@ stdcall RegLoadMUIStringW(ptr str str long ptr long str)
@ stdcall RegOpenKeyTransactedA(ptr str long long ptr ptr ptr)
@ stdcall RegOpenKeyTransactedW(ptr wstr long long ptr ptr ptr)
@ stdcall RegRenameKey(ptr wstr wstr)
@ stdcall RegSetKeyValueA(ptr str str long ptr long)
@ stdcall RegSetKeyValueW(ptr wstr wstr long ptr long)
@ stdcall SetEncryptedFileMetadata(wstr ptr ptr ptr long ptr)
@ stdcall SetSecurityAccessMask(long ptr)
@ stdcall SetUserFileEncryptionKeyEx(ptr long long ptr)
@ stdcall TreeSetNamedSecurityInfoA(str long long ptr ptr ptr ptr long)
@ stdcall TreeSetNamedSecurityInfoW(wstr long long ptr ptr ptr ptr long)
@ stdcall UsePinForEncryptedFilesA(long long long)
@ stdcall UsePinForEncryptedFilesW(long long long)

#Imports from wevtapibase (wevtapi from Longhorn Pre-Reset)
@ stdcall EvtAssertConfig() wevtapibase.EvtIntAssertConfig
@ stdcall EvtClearLog() wevtapibase.EvtIntClearLog
@ stdcall EvtClose() wevtapibase.EvtIntClose
@ stdcall EvtCompileTemplate() wevtapibase.EvtIntCompileTemplate
@ stdcall EvtCreateBookmark() wevtapibase.EvtIntCreateBookmark
@ stdcall EvtCreateMessageRenderContext() wevtapibase.EvtIntCreateMessageRenderContext
@ stdcall EvtCreateValuesRenderContext() wevtapibase.EvtIntCreateValuesRenderContext
@ stdcall EvtDeleteChannelConfig() wevtapibase.EvtIntDeleteChannelConfig
@ stdcall EvtExportLog() wevtapibase.EvtIntExportLog
@ stdcall EvtGetChannelConfigProperty() wevtapibase.EvtIntGetChannelConfigProperty
@ stdcall EvtGetEventMetadataProperty() wevtapibase.EvtIntGetEventMetadataProperty
@ stdcall EvtGetExtendedStatus() wevtapibase.EvtIntGetExtendedStatus
@ stdcall EvtGetMatchedQueryIds() wevtapibase.EvtIntGetMatchedQueryIds
@ stdcall EvtGetNamedObjectInformation() wevtapibase.EvtIntGetNamedObjectInformation
@ stdcall EvtGetPublisherMetadataProperty() wevtapibase.EvtIntGetPublisherMetadataProperty
@ stdcall EvtNext() wevtapibase.EvtIntNext
@ stdcall EvtNextBatch() wevtapibase.EvtIntNextBatch
@ stdcall EvtNextChannelPath() wevtapibase.EvtIntNextChannelPath
@ stdcall EvtNextEventMetadata() wevtapibase.EvtIntNextEventMetadata
@ stdcall EvtNextPublisherId() wevtapibase.EvtIntNextPublisherId
@ stdcall EvtOpenChannelConfig() wevtapibase.EvtIntOpenChannelConfig
@ stdcall EvtOpenChannelEnum() wevtapibase.EvtIntOpenChannelEnum
@ stdcall EvtOpenEventMetadataEnum() wevtapibase.EvtIntOpenEventMetadataEnum
@ stdcall EvtOpenPublisherEnum() wevtapibase.EvtIntOpenPublisherEnum
@ stdcall EvtOpenPublisherMetadata() wevtapibase.EvtIntOpenPublisherMetadata
@ stdcall EvtQueryLog() wevtapibase.EvtIntQueryLog
@ stdcall EvtRegisterSubscription() wevtapibase.EvtIntRegisterSubscription
@ stdcall EvtRender() wevtapibase.EvtIntRender
@ stdcall EvtRenderBookmark() wevtapibase.EvtIntRenderBookmark
@ stdcall EvtRetractConfig() wevtapibase.EvtIntRetractConfig
@ stdcall EvtSaveChannelConfig() wevtapibase.EvtIntSaveChannelConfig
@ stdcall EvtSeek() wevtapibase.EvtIntSeek
@ stdcall EvtSetChannelConfigProperty() wevtapibase.EvtIntSetChannelConfigProperty
@ stdcall EvtUpdateBookmark() wevtapibase.EvtIntUpdateBookmark
@ stdcall EvtUpdateSubscription() wevtapibase.EvtIntUpdateSubscription

#Imports from advapilong (advapi32 from Longhorn Pre-Reset)
@ stdcall EvtGetThreadCorrelationId()
@ stdcall EvtIsActive()
@ stdcall EvtRegisterPublisher()
@ stdcall EvtRegisterSubscriber()
@ stdcall EvtReport()
@ stdcall EvtReportText()
@ stdcall EvtScopePublisher()
@ stdcall EvtSetThreadCorrelationId()