@ stdcall DriverEntry(ptr ptr)
@ stdcall EngAcquireSemaphore(ptr)
@ stdcall EngAllocMem(long long long)
@ stdcall EngAllocPrivateUserMem(ptr ptr long)
@ stdcall EngAllocSectionMem(ptr long ptr long)
@ stdcall EngAllocUserMem(ptr long)
@ stdcall EngAlphaBlend(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall EngAssociateSurface(ptr ptr long)
@ stdcall EngBitBlt(ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr long)
@ stdcall EngBugCheckEx(long ptr ptr ptr ptr) NTOSKRNL.KeBugCheckEx
@ stdcall EngCheckAbort(ptr)
@ stdcall EngClearEvent(ptr)
@ stdcall EngComputeGlyphSet(long long long)
@ stdcall EngControlSprites(ptr long)
@ stdcall EngCopyBits(ptr ptr ptr ptr ptr ptr)
@ stdcall EngCreateBitmap(long long long long long ptr)
@ stdcall EngCreateClip()
@ stdcall EngCreateDeviceBitmap(ptr long long long)
@ stdcall EngCreateDeviceSurface(ptr long long long)
@ stdcall EngCreateDriverObj(ptr ptr ptr)
@ stdcall EngCreateEvent(ptr)
@ stdcall EngCreatePalette(long long long long long long)
@ stdcall EngCreatePath()
@ stdcall EngCreateSemaphore()
@ stdcall EngCreateWnd(ptr ptr ptr long long)
@ stdcall EngDebugBreak() NTOSKRNL.DbgBreakPoint
@ stdcall EngDebugPrint(ptr ptr ptr)
@ stdcall EngDeleteClip(ptr)
@ stdcall EngDeleteDriverObj(ptr long long)
@ stdcall EngDeleteEvent(ptr)
@ stdcall EngDeleteFile(ptr)
@ stdcall EngDeletePalette(ptr)
@ stdcall EngDeletePath(ptr)
@ stdcall EngDeleteSafeSemaphore(ptr)
@ stdcall EngDeleteSemaphore(ptr)
@ stdcall EngDeleteSurface(ptr)
@ stdcall EngDeleteWnd(ptr)
@ stdcall EngDeviceIoControl(ptr long ptr long ptr long ptr)
@ stdcall EngDitherColor(ptr long long long)
@ stdcall EngDxIoctl(long ptr long)
@ stdcall EngEnumForms(ptr long ptr long ptr ptr)
@ stdcall EngEraseSurface(ptr ptr long)
@ stdcall EngFileIoControl(ptr long ptr ptr ptr ptr ptr)
@ stdcall EngFileWrite(ptr ptr ptr ptr)
@ stdcall EngFillPath(ptr ptr ptr ptr ptr long long)
@ stdcall EngFindImageProcAddress(ptr ptr)
@ stdcall EngFindResource(ptr long long ptr)
@ stdcall EngFntCacheAlloc(long long)
@ stdcall EngFntCacheFault(long long)
@ stdcall EngFntCacheLookUp(long ptr)
@ stdcall EngFreeMem(ptr)
@ stdcall EngFreeModule(ptr)
@ stdcall EngFreePrivateUserMem(ptr ptr)
@ stdcall EngFreeSectionMem(ptr ptr)
@ stdcall EngFreeUserMem(ptr)
@ stdcall EngGetCurrentCodePage(ptr ptr)
@ stdcall EngGetCurrentProcessId() NTOSKRNL.PsGetCurrentProcessId
@ stdcall EngGetCurrentThreadId() NTOSKRNL.PsGetCurrentThreadId
@ stdcall EngGetDriverName(ptr)
@ stdcall EngGetFileChangeTime(ptr ptr)
@ stdcall EngGetFilePath(ptr ptr)
@ stdcall EngGetForm(ptr ptr long ptr long ptr)
@ stdcall EngGetLastError()
@ stdcall EngGetPrinter(ptr long ptr long ptr)
@ stdcall EngGetPrinterData(ptr ptr ptr ptr long ptr)
@ stdcall EngGetPrinterDataFileName(ptr)
@ stdcall EngGetPrinterDriver(ptr ptr long ptr long ptr)
@ stdcall EngGetProcessHandle()
@ stdcall EngGetTickCount()
@ stdcall EngGetType1FontList(ptr ptr long ptr ptr ptr)
@ stdcall EngGradientFill(ptr ptr ptr ptr long ptr long ptr ptr long)
@ stdcall EngHangNotification(ptr ptr)
@ stdcall EngInitializeSafeSemaphore(ptr)
@ stdcall EngIsSemaphoreOwned(ptr)
@ stdcall EngIsSemaphoreOwnedByCurrentThread(ptr)
@ stdcall EngLineTo(ptr ptr ptr long long long long ptr long)
@ stdcall EngLoadImage(ptr)
@ stdcall EngLoadModule(ptr)
@ stdcall EngLoadModuleForWrite(ptr long)
@ stdcall EngLockDirectDrawSurface(ptr)
@ stdcall EngLockDriverObj(ptr)
@ stdcall EngLockSurface(ptr)
@ stdcall EngLpkInstalled()
@ stdcall EngMapEvent(ptr ptr ptr ptr ptr)
@ stdcall EngMapFile(ptr long ptr)
@ stdcall EngMapFontFile(ptr ptr ptr)
@ stdcall EngMapFontFileFD(ptr ptr ptr)
@ stdcall EngMapModule(ptr ptr)
@ stdcall EngMapSection(ptr long ptr ptr)
@ stdcall EngMarkBandingSurface(ptr)
@ stdcall EngModifySurface(ptr ptr long long ptr ptr long ptr)
@ stdcall EngMovePointer(ptr long long ptr)
@ stdcall EngMulDiv(long long long)
@ stdcall EngMultiByteToUnicodeN(ptr long ptr ptr long) NTOSKRNL.RtlMultiByteToUnicodeN
@ stdcall EngMultiByteToWideChar(long ptr long ptr long)
@ stdcall EngNineGrid(ptr ptr ptr ptr ptr ptr ptr ptr ptr)
@ stdcall EngPaint(ptr ptr ptr ptr long)
@ stdcall EngPlgBlt(ptr ptr ptr ptr ptr ptr ptr ptr ptr ptr long)
@ stdcall EngProbeForRead(ptr long long) NTOSKRNL.ProbeForRead
@ stdcall EngProbeForReadAndWrite(ptr long long) NTOSKRNL.ProbeForWrite
@ stdcall EngQueryDeviceAttribute(ptr long ptr long ptr long)
@ stdcall EngQueryLocalTime(ptr)
@ stdcall EngQueryPalette(ptr ptr long ptr)
@ stdcall EngQueryPerformanceCounter(ptr)
@ stdcall EngQueryPerformanceFrequency(ptr)
@ stdcall EngQuerySystemAttribute(long ptr)
@ stdcall EngReadStateEvent(ptr)
@ stdcall EngReleaseSemaphore(ptr)
@ stdcall EngRestoreFloatingPointState(ptr)
@ stdcall EngSaveFloatingPointState(ptr long)
@ stdcall EngSecureMem(ptr long)
@ stdcall EngSetEvent(ptr)
@ stdcall EngSetLastError(long)
@ stdcall EngSetPointerShape(ptr ptr ptr ptr long long long long ptr long)
@ stdcall EngSetPointerTag(ptr ptr ptr ptr long)
@ stdcall EngSetPrinterData(ptr ptr long ptr long)
@ stdcall EngSort(ptr long long ptr)
@ stdcall EngStretchBlt(ptr ptr ptr ptr ptr long long ptr ptr ptr long)
@ stdcall EngStretchBltROP(ptr ptr ptr ptr ptr long long ptr ptr ptr long ptr long)
@ stdcall EngStrokeAndFillPath(ptr ptr ptr ptr ptr ptr ptr ptr long long)
@ stdcall EngStrokePath(ptr ptr ptr ptr ptr ptr ptr long)
@ stdcall EngTextOut(ptr ptr ptr ptr ptr ptr ptr ptr ptr long)
@ stdcall EngTransparentBlt(ptr ptr ptr ptr ptr ptr long long)
@ stdcall EngUnicodeToMultiByteN(ptr long ptr ptr long) NTOSKRNL.RtlUnicodeToMultiByteN
@ stdcall EngUnloadImage(ptr)
@ stdcall EngUnlockDirectDrawSurface(ptr)
@ stdcall EngUnlockDriverObj(ptr)
@ stdcall EngUnlockSurface(ptr)
@ stdcall EngUnmapEvent(ptr)
@ stdcall EngUnmapFile(ptr)
@ stdcall EngUnmapFontFile(ptr)
@ stdcall EngUnmapFontFileFD(ptr)
@ stdcall EngUnsecureMem(ptr)
@ stdcall EngWaitForSingleObject(ptr ptr)
@ stdcall EngWideCharToMultiByte(long ptr long ptr long)
@ stdcall EngWritePrinter(ptr ptr long ptr)

#Vista Functions
@ stdcall EngCombineRgn(ptr ptr ptr long)
@ stdcall EngCreateRectRgn(long long long long)
@ stdcall EngDeleteRgn(ptr)
@ stdcall EngGetRgnData(ptr long ptr)
@ stdcall EngOffsetRgn(ptr long long)
@ stdcall EngSetRectRgn(ptr long long long long)
@ stdcall EngQueryW32kCddInterface(ptr long long long long)