[WMI,
 guid("{C105BB0D-C2D8-415B-9B0D-91A29979EBDD}")]
class NVMe_DataType
{
    [WmiDataId(1)] sint32   Id;
    [WmiDataId(2)] uint64   u64;
};

[WMI,
 Dynamic,
 Description("Sample to Query WMI data from the NVMe  Device Driver"),
 Provider("WmiProv"),
 guid("{0F70DA81-FD3F-40CB-8EF1-52385F31DB2F}")]
class NVMe_QueryDevInfo
{
  [key]                         // providers always need these 3 fields
  string  InstanceName;
  boolean Active;

  [WmiDataId(1)] uint32 maxDataXferSize;
  [WmiDataId(2)] uint32 numberOfNamespaces;
  [WmiDataId(3)] NVMe_DataType Data;
};

[WMI,
 Dynamic,
 Description("Sample to invoke methods on WMI class"),
 Provider("WmiProv"),
 guid("{3865DDFA-7774-4CF4-B5CA-B7569A28FBB4}")]
class NVMe_Method
{
  [key]
  string  InstanceName;
  boolean Active;

  [Implemented, WmiMethodId(1)]
  void GetControllerInfo(
        [out]  uint16 pciVendorId,
        [out]  uint16 pciSsVendId
        );  


 [Implemented, WmiMethodId(2)]
  void GetNameSpaceInfo(
        [in]   uint32  lunId,
        [out]  uint64  nSize,
        [out]  uint64  nCap
        );
};



