@ stdcall DllInstall(long wstr)
1 stdcall PdhPlaGetLogFileNameA(str str ptr long ptr str)
@ stdcall PdhAdd009CounterA(ptr str ptr ptr)
@ stdcall PdhAdd009CounterW(ptr wstr ptr ptr)
@ stdcall PdhAddCounterA(ptr str long ptr)
@ stdcall PdhAddCounterW(ptr wstr long ptr)
@ stdcall PdhAddEnglishCounterA(ptr str long ptr)
@ stdcall PdhAddEnglishCounterW(ptr wstr long ptr)
@ stdcall PdhBindInputDataSourceA(ptr str)
@ stdcall PdhBindInputDataSourceW(ptr wstr)
@ stdcall PdhBrowseCountersA(ptr)
@ stdcall PdhBrowseCountersHA(ptr)
@ stdcall PdhBrowseCountersHW(ptr)
@ stdcall PdhBrowseCountersW(ptr)
@ stdcall PdhCalculateCounterFromRawValue(ptr long ptr ptr ptr)
@ stdcall PdhCloseLog(ptr long)
@ stdcall PdhCloseQuery(ptr)
@ stdcall PdhCollectQueryData(ptr)
@ stdcall PdhCollectQueryDataWithTime(ptr ptr)
@ stdcall PdhCollectQueryDataEx(ptr long ptr)
@ stdcall PdhComputeCounterStatistics(ptr long long long ptr ptr)
@ stdcall PdhConnectMachineA(str)
@ stdcall PdhConnectMachineW(ptr)
@ stdcall PdhCreateSQLTablesA(str)
@ stdcall PdhCreateSQLTablesW(str)
@ stdcall PdhEnumLogSetNamesA(str str ptr)
@ stdcall PdhEnumLogSetNamesW(wstr wstr ptr)
@ stdcall PdhEnumMachinesA(str str ptr)
@ stdcall PdhEnumMachinesHA(str str ptr)
@ stdcall PdhEnumMachinesHW(wstr wstr ptr)
@ stdcall PdhEnumMachinesW(wstr wstr ptr)
@ stdcall PdhEnumObjectItemsA(str str str ptr ptr ptr ptr long long)
@ stdcall PdhEnumObjectItemsHA(ptr str str str ptr str ptr long long)
@ stdcall PdhEnumObjectItemsHW(ptr wstr wstr str ptr str ptr long long)
@ stdcall PdhEnumObjectItemsW(wstr wstr wstr ptr ptr ptr ptr long long)
@ stdcall PdhEnumObjectsA(str str str ptr long long)
@ stdcall PdhEnumObjectsHA(ptr str str ptr long long)
@ stdcall PdhEnumObjectsHW(ptr wstr wstr ptr long long)
@ stdcall PdhEnumObjectsW(wstr wstr wstr ptr long long)
@ stdcall PdhExpandCounterPathA(str ptr ptr)
@ stdcall PdhExpandCounterPathW(wstr ptr ptr)
@ stdcall PdhExpandWildCardPathA(str str ptr ptr long)
@ stdcall PdhExpandWildCardPathHA(ptr str str ptr long)
@ stdcall PdhExpandWildCardPathHW(ptr wstr wstr ptr long)
@ stdcall PdhExpandWildCardPathW(wstr wstr ptr ptr long)
@ stdcall PdhFormatFromRawValue(long long long long ptr ptr ptr)
@ stdcall PdhGetCounterInfoA(ptr long ptr ptr)
@ stdcall PdhGetCounterInfoW(ptr long ptr ptr)
@ stdcall PdhGetCounterTimeBase(ptr ptr)
@ stdcall PdhGetDataSourceTimeRangeA(str ptr ptr ptr)
@ stdcall PdhGetDataSourceTimeRangeH(ptr ptr ptr ptr)
@ stdcall PdhGetDataSourceTimeRangeW(wstr ptr ptr ptr)
@ stdcall PdhGetDefaultPerfCounterA(str str str str ptr)
@ stdcall PdhGetDefaultPerfCounterHA(ptr str str str ptr)
@ stdcall PdhGetDefaultPerfCounterHW(ptr wstr wstr wstr ptr)
@ stdcall PdhGetDefaultPerfCounterW(str wstr wstr wstr ptr)
@ stdcall PdhGetDefaultPerfObjectA(str str str ptr)
@ stdcall PdhGetDefaultPerfObjectHA(ptr str str ptr)
@ stdcall PdhGetDefaultPerfObjectHW(ptr wstr wstr ptr)
@ stdcall PdhGetDefaultPerfObjectW(wstr wstr wstr ptr)
@ stdcall PdhGetDllVersion(ptr)
@ stdcall PdhGetFormattedCounterArrayA(ptr long ptr ptr ptr)
@ stdcall PdhGetFormattedCounterArrayW(ptr long ptr ptr ptr)
@ stdcall PdhGetFormattedCounterValue(ptr long ptr ptr)
@ stdcall PdhGetLogFileSize(ptr ptr)
@ stdcall PdhGetLogFileTypeA(str ptr)
@ stdcall PdhGetLogFileTypeW(wstr ptr)
@ stdcall PdhGetLogSetGUID(ptr ptr)
@ stdcall PdhGetRawCounterArrayA(ptr ptr ptr ptr)
@ stdcall PdhGetRawCounterArrayW(ptr ptr ptr ptr)
@ stdcall PdhGetRawCounterValue(ptr ptr ptr)
@ stdcall PdhIsRealTimeQuery(ptr)
@ stdcall PdhListLogFileHeaderA(str wstr long)
@ stdcall PdhListLogFileHeaderW(str wstr long)
@ stub PdhLogServiceCommandA
@ stub PdhLogServiceCommandW
@ stub PdhLogServiceControlA
@ stub PdhLogServiceControlW
@ stdcall PdhLookupPerfIndexByNameA(str str ptr)
@ stdcall PdhLookupPerfIndexByNameW(wstr wstr ptr)
@ stdcall PdhLookupPerfNameByIndexA(str long ptr ptr)
@ stdcall PdhLookupPerfNameByIndexW(wstr long ptr ptr)
@ stdcall PdhMakeCounterPathA(ptr ptr ptr long)
@ stdcall PdhMakeCounterPathW(ptr ptr ptr long)
@ stdcall PdhOpenLogA(str long ptr ptr long str ptr)
@ stdcall PdhOpenLogW(wstr long ptr ptr long wstr ptr)
@ stdcall PdhOpenQuery(wstr long ptr)
@ stdcall PdhOpenQueryA(str long ptr)
@ stdcall PdhOpenQueryH(ptr ptr ptr)
@ stdcall PdhOpenQueryW(wstr long ptr)
@ stdcall PdhParseCounterPathA(str ptr ptr long)
@ stdcall PdhParseCounterPathW(str ptr ptr long)
@ stdcall PdhParseInstanceNameA(str str ptr str ptr ptr)
@ stdcall PdhParseInstanceNameW(wstr wstr ptr wstr ptr ptr)
@ stdcall PdhPlaAddItemA(str str str)
@ stdcall PdhPlaAddItemW(wstr str str)
@ stdcall PdhPlaCreateA(str str long)
@ stdcall PdhPlaCreateW(wstr wstr long)
@ stdcall PdhPlaDeleteA(str str)
@ stdcall PdhPlaDeleteW(wstr wstr)
@ stdcall PdhPlaEnumCollectionsA(str ptr ptr)
@ stdcall PdhPlaEnumCollectionsW(wstr ptr ptr)
@ stdcall PdhPlaGetInfoA(str str ptr ptr)
@ stdcall PdhPlaGetInfoW(wstr wstr ptr ptr)
@ stdcall PdhPlaGetLogFileNameW(wstr long ptr ptr ptr ptr)
@ stdcall PdhPlaGetScheduleA(str str long long long)
@ stdcall PdhPlaGetScheduleW(wstr wstr long long long)
@ stdcall PdhPlaRemoveAllItemsA(str str)
@ stdcall PdhPlaRemoveAllItemsW(wstr wstr)
@ stdcall PdhPlaScheduleA(str str ptr ptr)
@ stdcall PdhPlaScheduleW(wstr wstr ptr ptr)
@ stdcall PdhPlaSetInfoA(str str long)
@ stdcall PdhPlaSetInfoW(wstr wstr long)
@ stdcall PdhPlaSetItemListA(str str ptr)
@ stdcall PdhPlaSetItemListW(wstr wstr ptr)
@ stdcall PdhPlaSetRunAsA(str str ptr ptr)
@ stdcall PdhPlaSetRunAsW(wstr wstr ptr ptr)
@ stdcall PdhPlaStartA(str str)
@ stdcall PdhPlaStartW(wstr wstr)
@ stdcall PdhPlaStopA(str str)
@ stdcall PdhPlaStopW(wstr wstr)
@ stdcall PdhPlaValidateInfoA(str str long)
@ stdcall PdhPlaValidateInfoW(wstr wstr long)
@ stdcall PdhReadRawLogRecord(ptr ptr ptr ptr)
@ stdcall PdhRelogA(ptr str)
@ stdcall PdhRelogW(ptr wstr)
@ stdcall PdhRemoveCounter(ptr)
@ stdcall PdhSelectDataSourceA(ptr long str ptr)
@ stdcall PdhSelectDataSourceW(ptr long wstr ptr)
@ stdcall PdhSetCounterScaleFactor(ptr long)
@ stdcall PdhSetDefaultRealTimeDataSource(long)
@ stdcall PdhSetLogSetRunID(ptr long)
@ stdcall PdhSetQueryTimeRange(ptr ptr)
@ stdcall PdhTranslate009CounterA(str ptr long)
@ stdcall PdhTranslate009CounterW(wstr ptr long)
@ stdcall PdhTranslateLocaleCounterA(str ptr long)
@ stdcall PdhTranslateLocaleCounterW(wstr ptr long)
@ stdcall PdhUpdateLogA(ptr str)
@ stdcall PdhUpdateLogFileCatalog(ptr)
@ stdcall PdhUpdateLogW(ptr wstr)
@ stdcall PdhValidatePathA(str)
@ stdcall PdhValidatePathExA(ptr str)
@ stdcall PdhValidatePathExW(ptr wstr)
@ stdcall PdhValidatePathW(wstr)
@ stdcall PdhVbAddCounter(ptr str ptr)
@ stdcall PdhVbCreateCounterPathList(long str)
@ stdcall PdhVbGetCounterPathElements(str str str str str str long)
@ stdcall PdhVbGetCounterPathFromList(ptr str long)
@ stdcall PdhVbGetDoubleCounterValue(ptr long)
@ stdcall PdhVbGetLogFileSize(ptr long)
@ stdcall PdhVbGetOneCounterPath(str long long str)
@ stdcall PdhVbIsGoodStatus(long)
@ stdcall PdhVbOpenLog(str long ptr ptr long str ptr)
@ stdcall PdhVbOpenQuery(ptr)
@ stdcall PdhVbUpdateLog(ptr str)
@ stdcall PdhVerifySQLDBA(str)
@ stdcall PdhVerifySQLDBW(wstr)
@ stdcall PdhiPla2003SP1Installed(wstr ptr)
@ stdcall PdhiPlaFormatBlanksA(str ptr)
@ stdcall PdhiPlaFormatBlanksW(str ptr)
@ stdcall PdhiPlaGetVersion(wstr ptr)
@ stdcall PdhiPlaRunAs(wstr wstr ptr)
@ stdcall PdhiPlaSetRunAs(wstr ptr wstr wstr)
@ stdcall PlaTimeInfoToMilliSeconds(ptr ptr)
@ stdcall PdhPlaDowngradeW()
@ stdcall PdhPlaUpgradeW()
@ stdcall PdhiPlaDowngrade()
@ stdcall PdhiPlaUpgrade()