@ stdcall CM_Delete_Class_Key(ptr long) cfgmgr32.
CM_Delete_Device_Interface_KeyW
@ stdcall CM_Delete_DevNode_Key(long long long)
@ stdcall CM_Disable_DevNode(long long)
@ stdcall CM_Enable_DevNode(long long)
@ stdcall CM_Get_Child(ptr long long)
CM_Get_Class_Property_Keys
CM_Get_Class_PropertyW
CM_Get_Class_Registry_PropertyW
CM_Get_Depth
CM_Get_Device_ID_List_SizeW
CM_Get_Device_ID_ListW
CM_Get_Device_ID_Size
CM_Get_Device_IDW
CM_Get_Device_Interface_List_SizeW
CM_Get_Device_Interface_ListW
CM_Get_Device_Interface_Property_KeysW
CM_Get_Device_Interface_PropertyW
CM_Get_DevNode_Property_Keys
CM_Get_DevNode_PropertyW
CM_Get_DevNode_Registry_PropertyW
CM_Get_DevNode_Status
CM_Get_Parent
CM_Get_Sibling
CM_Locate_DevNodeW
CM_Open_Class_KeyW
CM_Open_Device_Interface_KeyW
CM_Open_DevNode_Key
CM_Query_And_Remove_SubTreeW
CM_Register_Notification
CM_Set_Class_PropertyW
CM_Set_Class_Registry_PropertyW
CM_Set_Device_Interface_PropertyW
CM_Set_DevNode_PropertyW
CM_Set_DevNode_Registry_PropertyW
CM_Setup_DevNode
CM_Uninstall_DevNode
CM_Unregister_Notification
